### ISSUE TITLE
"Not Allowed" messages

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1006]
When i go to any production replay, i see "Not allowed", which looks to be coming from `DisallowEverything::ownKeys` [link](https://github.com/RecordReplay/devtools/blob/master/src/protocol/utils.ts#L98-L101) 

My hunch is that one of the classes that mixes them in is running into an issue e.g. RuleFront

https://replay.io/view?id=0da3ff73-e351-4b0f-b34f-e3452df83441

<img width="728" alt="Screen Shot 2020-11-12 at 6 51 10 PM" src="https://user-images.githubusercontent.com/254562/99022805-2aa79280-2518-11eb-8eae-1c99599fd8a8.png">

**Comment by jasonLaster** [comment]
looks like something funky is happening with `ownKeys`

**Comment by jasonLaster** [comment]
I'd like to see why we don't have the logs in development. My guess here is that there is something funny happening with the instrument.js layer in Sentry/LogRocket accessing the keys

**Comment by hbenl** [comment]
The reason is that the LogRocket redux middleware inspects all redux actions and the redux state and some components add `*Front` objects to the actions or even to the state, but these objects can't be inspected because of the `DisallowEverythingProxyHandler`.
I have found 2 culprits so far:
- the rules view adds `RuleFront`s and `StyleFront`s to the `UPDATE_RULES` action, but the corresponding reducer transforms them to simple json objects before adding them to the state
- the console puts `NodeFront`s (for message parameters) in the `MESSAGES_ADD` action and the corresponding reducer copies them to the state

Possible fixes:
- disable the log messages by either removing LogRocket's redux middleware or the `DisallowEverythingProxyHandler` - in both cases we'd be losing some information that helps finding and fixing bugs in our devtools
- fix our redux actions and reducers - that's easy for the rules view (we just need to move the existing transformation from the reducer to the action creator) but a little harder for the console. We could also think about following the recommendations for redux state more closely: currently we put non-serializable objects into the state and modify instead of replacing parts of the state (the console is an example of both: it puts `NodeFront`s and several `Map`s and a `Set` into the state and doesn't replace those)

> I'd like to see why we don't have the logs in development.

To see the logs in development, remove the `skipTelemetry` check [here](https://github.com/RecordReplay/devtools/blob/8a3b28b74d15043f948d9a0e34c1f3838df9267c/src/ui/utils/bootstrap/bootstrapStore.js#L78).

**Comment by jasonLaster** [comment]
Thanks @hbenl I like the idea of refactoring the reducers to not use the fronts. 

happy to compromise as well. For instance, refactor easy actions, but also whitelist difficult actions.
