### ISSUE TITLE
[Timeline] Hovering on the timeline is slow

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1111]
This appears to have been caused by [this commit](https://github.com/RecordReplay/devtools/commit/86c6ea2a5a81066c4de71b9adad5458af4441345).

The mousemove event associated with hovering on the timeline used to take <10ms, now it takes over 350ms. The new sanitize util also runs after every paint, slowing it down more.

**Comment by jasonLaster** [comment]
My hunch is that the `instanceof` check is fast, but the fact that `sanitize` is recursive means we're doing a lot of checks.

This is a great example of how the profiler can show where we're slow as well.

**Comment by hbenl** [comment]
Not only is `sanitize` recursively looking at the state and actions, it recursively creates a copy (because we shouldn't change the original state). That becomes a performance problem as soon as the state or an action becomes several megabytes large - which happens when you open a large file (usually a bundle) in the debugger: the `SET_SYMBOLS` action is several megabytes large and its payload is then copied to the state. I'll disable sanitizing this action and the `ast` slice of the state (that's where the symbols end up) tomorrow.
