### ISSUE TITLE
We appear to force-switch to the breakpoints pane whenever we stop playing?

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#1334]
1. Open a recording
2. Ensure you are at the end of the recording
3. Select the sources pane
4. Press play to start from the beginning

Expected: Continue showing sources pane
Actual: Force-switched to the breakpoint pane as soon as recording starts playing

Similarly:

1. Open a recording
2. Jump to the middle of a recording
3. Select the sources pane
4. Press play
5. Wait until player reaches the end

Expected: Continue showing sources pane
Actual: Force-switched to the breakpoint list as soon as playing hits end of the timeline

Third:

1. Open a recording
2. Jump to somewhere early enough you can hit pause
3. Select the sources pane
4. Press play
5. Press pause

Expected: Continue showing sources pane
Actual: Force-switched to the breakpoint list as soon as playing is paused

**Comment by jaril** [comment]
Good catch. 

A few weeks ago we made it so that we automatically switch the sidebar to show the breakpoint panel whenever a pause is hit. This way, when a user is looking at a replay and they pause somewhere, they're not stuck looking at the sources panel. That usually happens because they don't realize they're paused and can look at pause info.

https://github.com/RecordReplay/devtools/blob/master/src/devtools/client/debugger/src/actions/pause/paused.js#L49

The play/pause mechanism must be triggering a new pause which explains the panel behavior. That's clearly not what we wanted for it to do. I'll take a look at it later and correct that!

**Comment by jaril** [comment]
Related issue: When we load a replay and it's done loading, we pause at the last point in the recording. This forces a switch from the default sidebar panel (explorer with editor/outline) to the pause info sidebar with breakpoints.
