### ISSUE TITLE
Show a notification when a recording is deleted

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1359]
**Description:**
when you delete your replays from your dashboard, there is no confirmation or indication they have successfully deleted. sometimes they're removed, other times you have to refresh, seems like it just takes a while.

**Steps to Reproduce:**
1. go to your account page
2. click edit
3. select a replay
4. click the "1 item selected" dropdown next to the "Done" button
5. click "Delete 1 item"
6. notice the replay becomes unchecked and you aren't notified of whether or not it worked

**Expected Result:**
replays you've deleted would disappear form the list and you receive a toast notification saying you've successfully deleted them (or otherwise if there was some error). you shouldn't have to refresh to find out if it worked. 
if it's going to take a while the replay rows could either gray out with some loading indicator to show that we're working on it, or maybe a toast could show up telling the user to hang on, then another to let them know it's done.

**Loom:**
in this loom i started with a fresh refresh, tried to delete a few and only some were removed. there is one replay that won't delete at all and produces an error in the console that i'll post below the loom. i believe this is the replay id "2bf2d299-6468-4766-ad7c-d65ba913954a"
https://www.loom.com/share/09ac1333d886437b80d83043701ee015

`Error: Foreign key violation. update or delete on table "recordings" violates foreign key constraint "comments_recording_id_fkey" on table "comments`
![image](https://user-images.githubusercontent.com/19538307/103105035-e5c74f00-45df-11eb-8adc-cec575e34495.png)

this error occurs in webpack:///./node_modules/@apollo/client/errors/index.js
![image](https://user-images.githubusercontent.com/19538307/103105059-068fa480-45e0-11eb-868e-fefb20a24c06.png)

**Replay:**
https://replay.io/view?id=6ede005e-0889-4218-a807-e319b6bf3b33

**Comment by loganfsmyth** [comment]
I fixed the database portion of this by going to https://graphql.replay.io/console/data/schema/public/tables/comments/modify and changing "On Delete Violation" on the comment -> recording foreign key to "cascade". That means that deleting a recording will also delete all of the comments for the recording. As it was, you'd be unable to delete any recording that had comments.

<img width="733" alt="Screen Shot 2020-12-24 at 12 23 38 PM" src="https://user-images.githubusercontent.com/132260/103105462-db5a8480-45e2-11eb-9156-c4bfd4942c75.png">

**Comment by loganfsmyth** [comment]
I fixed the database portion of this by setting the database to "cascade" deletes for recordings to the comments. As it was, deleting a recording would fail of there were comments on the recording because it didn't want to leave comments pointing at a recording that didn't exist.

**Comment by jasonLaster** [comment]
Jon, it'd be great to have a visual for a toast / notification that the event succeeded or failed. It could be fairly general too as i'm sure we'll be doing more of this

**Comment by jonbell-lot23** [comment]
Hey @jaril I'll do a precise visual treatment later, but in the meantime here's the design point of view:

When you've selected multiple Replays,

1. Instead of "x items selected" let's change that to "Delete x items?"
2. Let's make the button red
3. Let's change the Done button to a white background/blue stroke and say "Cancel"
4. Clicking it should through a modal that says "This will delete three items, are you sure?"
5. After clicking through the model, pop back out of edit mode. (As if you have hit the Done button)
6. To the left of the Done icon, a single line of red text that says "3 items deleted" is fine.
7. In a perfect world, there would be an undo button here. It's probably hard, but it has been drilled into me that destructive actions must always have confirmation and undo whenever possible  :)

**Comment by jasonLaster** [comment]
closing as we can get to notifications once we have regular users
