### ISSUE TITLE
Loading flow v2

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1365]
[This description written by Jon even though it looks like it was written by Jason :) ] 

When we did the [Resiliency Audit](https://www.notion.so/replayio/Resiliency-Audit-237fe5ca5c1c4593890295088eada520) we spotted some areas where we need loading screens to do a better job explaining status.

Currently, this item has a few goals:

* A more descriptive upload screen
* A more consistent handoff from the purple animation loader to the blue background loader to the final UI

Follow along here in Figma:

* [Figma Design Doc](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=1526%3A477) in the page called "Exploration - Loading flow v2"

**Comment by jonbell-lot23** [comment]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/9154902/103240132-55f51c80-49b4-11eb-9a56-535326ff9b76.png">

This work is also aligning to our hover states work, as shown here. We want to expose new users to our visual vocabulary in any way we can, and the loader is a great way to do that.

**Comment by jonbell-lot23** [comment]
![Diana - loading](https://user-images.githubusercontent.com/9154902/104769871-cf727480-57d4-11eb-84f3-c9cb554a2a05.png)

Here's the proposed design for our loading screen. A simple skeleton loader where we use the timeline on the bottom as a progress bar.

**Comment by jonbell-lot23** [comment]
Here's an animated version of the design. https://share.descript.com/view/z9u62MTrNeT

Here's what we need to draw/animate:

1. Render the different grey boxes as a skeleton
2. Put the title and logo at the top left
3. Animate the progress bar with floating "loading..." text above it
4. The playback region should start dark grey but then transition to our normal dark background

**Comment by jonbell-lot23** [comment]
Here's the view for Ellen. It has a different layout, so it gets a different skeleton visual:

![Ellen - loading](https://user-images.githubusercontent.com/9154902/104789828-eaf07600-57fa-11eb-99c7-f9f1caf15e0a.png)

**Comment by jonbell-lot23** [comment]
Uploading is an interesting state. We need to toggle across different messages:

1. Hang on a second
2. Uploading
3. Uploading is complete
4. Now we're preparing your Replay
5. Ok done

So rather than go from #1 to #2 and then switching over to an entirely different view, I propose having an upload screen that drops you straight into the product experience without changing the visuals. To discuss further. Here are a few treatments for discussion:

* Utilitarian text versus copy with personality
* Off-white background versus big blue gradient

![Uploading 9](https://user-images.githubusercontent.com/9154902/104790047-4fabd080-57fb-11eb-8f9a-65c3cec3099c.png)

![Uploading 5](https://user-images.githubusercontent.com/9154902/104790040-4b7fb300-57fb-11eb-9a86-99330ac19c6d.png)

![Uploading 7](https://user-images.githubusercontent.com/9154902/104790042-4c184980-57fb-11eb-9eea-72c1698f5e07.png)

![Uploading 1](https://user-images.githubusercontent.com/9154902/104790038-4a4e8600-57fb-11eb-9d72-7ab36de9f868.png)

**Comment by jonbell-lot23** [comment]
As discussed in our meeting today, we can consider this done for now. Will get to upload screens later: #1554
