### ISSUE TITLE
[UX] Add right-click to Playback region

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1405]
This task was originally here: https://github.com/RecordReplay/devtools/issues/1310

Description:
This is a shortcut to adding a comment that will act exactly like comments act today. It's based on the pause, not on a specific element. We're not leaving behind a marker.

As part of Comments Everywhere we're going to think through how this feature should work in a more robust way. But for now this is a basic MVP to get things rolling.

**Comment by jaril** [comment]
Requirements are left vague so leaving questions here to clarify:

General questions:
- What does clicking "Add a comment" do? Should it add a new comment (A) similar to the ones we can add from the timeline? Or should it add a new type of comment (B) that's anchored to a specific x/y position for that pause point?
- Where should the input box go for the new comment?
- How should the input box behave? Should it be similar to our existing comment editor which is opened when you add a new comment from the timeline? Or should it behave differently?
- What happens to the comment once saved? Should it behave similarly to other comments (show a corresponding marker on timeline and transcript)? Or is there anything different?

B-type comment specific questions:
- How does the UI look differently before and after the new comment is saved?
- Should there be a marker on the video screen? What should that look like?
- Should the timeline markers for these comments look different to other comments in the timeline? How so?
- Should the transcript entries for these comments look different to other comments in the timeline? How so?

So far, we've only allowed one comment per timeline point. This is easy to enforce right now–since all new comments are added through the timeline. If one already exists for that point, we simply don't show the user the new comment button. Related questions here are:
- Should we start allowing multiple comments per point in the timeline?
- If so, how should multiple comments for the same point be treated in the transcript? And in the timeline?

![image](https://user-images.githubusercontent.com/15959269/103327886-84aadb80-4a24-11eb-9c79-718d893e4755.png)

**Comment by jonbell-lot23** [comment]
Great questions! I had thought through some details, but not all. The short answer is: this is just a shortcut to adding a comment to the timeline for now. Nothing special.

* Clicking add comment will bring up the input box on the bottom, exactly like clicking the add comment icon works today.
* Input box acts exactly the same.
* Save flow works exactly the same.
* The UI shouldn't change. The right-click menu goes away, and no marker is left behind.

The multiple comment point is an important one I hadn't considered. Eventually we're going to have to design this out. In the meantime, we can have the behaviour work the same way as today, but the right-click menu should say "View comment."
