### ISSUE TITLE
e2e test failures

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1444]
Here's a recent run:
https://github.com/RecordReplay/devtools/actions/runs/456664989

The inspector tests look like legitimate issues getting applied rules and computed properties. The stepping and breakpoint tests look like other backend issues

* Failure inspector-03.js https://replay.io/view?id=3e6bbb29-1834-426e-84e8-2d5ba9c4f8c3&test=inspector-03.js
* Failure inspector-06.js https://replay.io/view?id=88e6d46e-d4ad-47cf-8711-35914a368007&test=inspector-06.js
* Failure inspector-07.js https://replay.io/view?id=eb166a1d-6bf1-4794-935d-3b1c7441b1b7&test=inspector-07.js  
* Failure stepping-05.js https://replay.io/view?id=0c61305d-e436-4d52-9e37-15816af9824f&test=stepping-05.js 
* Failure breakpoints-05.js https://replay.io/view?id=b2230d1b-1f6f-4ab4-8559-f8e547bfbba7&test=breakpoints-05.js

**Comment by jasonLaster** [comment]
https://github.com/RecordReplay/devtools/actions/runs/462399926

**Comment by loganfsmyth** [comment]
Started out looking at stepping-05 and it seems like what is happening is that we add a breakpoint and then to `resumeToLine(8)`, but we step to somewhere that does not have any JS frames, so we sit forever waiting for the frames to appear until it times out. I'll have to dig in more to figure out why we stop somewhere else unexpectedly.

**Comment by loganfsmyth** [comment]
Here's my current analysis:

* inspector-03.js
  * Stuck at https://github.com/RecordReplay/devtools/blob/394e762cadb696c0af8c2ebc69fef03041c774a7/test/scripts/inspector-03.js#L8 forever
  * The preview shows a page with styles, but none of the backend is not returning any of the rules that the test expects
  * Seems more like a backend bug somewhere
* inspector-06.js
  * Similar to 03, preview shows styling but backend sent no rules back
* inspector-07.js
  * Similar to 03, preview shows styling but backend sent no rules back

* stepping-05.js
  * Flakey because the timer races with "mapped_minified.js" loading (This I'll post a PR for)
  * Also seems to fail sometimes with an assertion failure in `_chooseSourceId` because the code assumes that any minified file is _guaranteed_ to have a pretty version, which may not be true?

* breakpoints-05.js
  * I don't know if this one is broken? The link you posted shows "TestFinished" properly

**Comment by loganfsmyth** [comment]
So the two primary things are:
* Why does the stepping test _sometimes_ get a position that has no mapped location, and is that expected? If so, the client needs to handle that, otherwise the backend needs to fix it
* Why do we sometimes get no rules from the backend when the page view clearly shows a styled page.

**Comment by bhackett1024** [comment]
@loganfsmyth the inspector tests above should be fixed in the latest browser, e.g. https://github.com/RecordReplay/devtools/actions/runs/467538160

https://github.com/recordreplay/devtools/issues/1447 has information about what the problem here was.

**Comment by bhackett1024** [comment]
Oh, and if there is a pretty printed version of a source then the backend should always generate locations that include both the normal and pretty-printed location (i.e. the pretty print source map can map between any locations in the two sources).

**Comment by loganfsmyth** [comment]
Ah darn, I wish I'd seen that before. At least that cuts out the biggest issue.

That just leaves the pretty-print weirdness, I'll plan to dig into that then.

**Comment by loganfsmyth** [comment]
Yeah, I get why that's ideal and that's definitely the bug here, I just have mixed feelings about the frontend explicitly asserting that instead of falling back to the non-pretty version in that case, since that's what the backend is (erroneously) telling it to do.

**Comment by bhackett1024** [comment]
There's definitely room for disagreement here, and it would be nice if the frontend could handle this case robustly, but I think this is a reasonable invariant which the protocol ought to enforce.  If the backend doesn't return a pretty printed location then the client will need to use the one in the minified code, and I feel it's a good heuristic that any time we are showing minified code to a user we are making a mistake.

**Comment by loganfsmyth** [comment]
That's fair. I think stuff like this is why I'm not a fan of our current usage of arrays to represent positions. It seems like ideally it would be something with a more explicit structure so that we could define relations and clearly assert what types of positions are returned when.

**Comment by bhackett1024** [comment]
Sure, having a more structured way to represent locations would be a nice improvement, the handling for this in thread.ts is pretty unsightly.

**Comment by loganfsmyth** [comment]
I just had an inspector-02 failure in https://github.com/RecordReplay/devtools/pull/1503/checks?check_run_id=1670380745 (https://replay.io/view?id=2e84c9f5-2354-4509-891d-0ae6dae3d133&test=inspector-02.js), if you open the recording that it was debugging (https://replay.io/view?id=b4db9f15-10cd-4a23-94ea-2f25b17f637e&test=inspector-02.js), the bounding boxes on hover are wrong, so that's one outstanding issue that must still be flakey.

**Comment by loganfsmyth** [comment]
@bhackett1024 Would you want to look at this `inspector-02` failure? `node test/run.js --pattern inspector-02.js --record-all` is enough to repro consistently for me. It looks like the bounding boxes for the iframes aren't coming through properly, so I'd guess that this is also related to the stuff mentioned in https://github.com/RecordReplay/devtools/issues/1444#issuecomment-756338736

**Comment by bhackett1024** [comment]
Sure, I can look later today.

**Comment by loganfsmyth** [comment]
Looks like @hbenl filed a backend-specific bug at https://github.com/RecordReplay/backend/issues/895 so maybe we should close this and use that one?

**Comment by loganfsmyth** [comment]
I think we're good to close this.
