### ISSUE TITLE
The console pause line should update while the video is playing

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1449]
One of the primary UX goals is to keep all of the panels in sync. A great example of this is while the video is playing, we should update the console.

https://www.loom.com/share/0775e7ebb7fa45a890263b6897ddc848

**Comment by jaril** [comment]
We already do this: https://share.descript.com/view/qrLXCxp4QXk.

It might be that it was broken at the time of that original recording and something changed this week that fixed it. Or there was a specific bug related to that recording that prevented the console's pause line from advancing during playback.

One thing we could do better here is to scroll the console during the playback. Otherwise the pause line might be advancing outside of the visible scroll area. Will spin up a patch for that quickly.
