### ISSUE TITLE
[UX] Panels should be in-sync on hover/pause/play

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1463]
### Playing the video should update the panels 
- [x] viewer should update
- [ ] console pause line should update and stay in focus
- [x] breakpoint widgets progress bar should update

### Hovering on a marker should update the other markers
- [ ] hovering on a breakpoint widget marker should update (console message, timeline marker, viewer)
- [ ] hovering on a timeline marker should update (console message, bp widget, viewer)
- [ ] hovering on a console message should update (bp widget, timeline marker, viewer)

### Hovering on a location should show markers for that location
- [x] hovering on the gutter
- [ ] hovering on a console message #1399

**Comment by jaril** [comment]
Needed help wrapping my head around this so mapped it out on a table. Green cells makes sense, and Orange cells need to be resolved:

Hovered on | Console Message | Console Message (siblings) | Timeline Marker | Timeline marker (siblings) | Widget marker | Widget
| - | - | - | - | - | - | - | 
Console Message | ⬜️ | ✅ | ✅ | ✅ | 🟧 | 🟧 |
Timeline Marker | ✅ | ✅ | ⬜️ | ✅ | 🟧 | 🟧 |
Widget Marker | ✅ | ✅ | ✅ | ✅ | ⬜️ | 🟧 |

Hover interactions are supposed to be light. Opening the source file and scrolling to the location to do "proper" highlighting of a widget feels heavy. Options for widget highlighting:
1) **Full highlighting of the widget marker and widget**: Force the widget into view and apply highlight styles.
2) **Partial highlighting of widget marker and widget**: Apply highlight styles, but don't force the widget into view.
3) **No highlighting of the widget marker and widget**: Self-explanatory.

**Comment by jaril** [comment]
Adding detailed requirements here so I can follow along easily.

### Console message hover interactions

1) ❌ Hovering on a console message should highlight its corresponding **timeline marker and its siblings**.
- [ ] Store `hoveredConsoleMessage` in Redux.
- [ ] Highlight the timeline marker if `marker.time === hoveredConsoleMessage.time`.
- [ ] Highlight the timeline marker (siblings) if `marker.key === hoveredConsoleMessage.key`.

2) ❌ Hovering on a console message should highlight its corresponding **breakpoint widget and marker**.
- [ ] Open the marker's corresponding message's location in the editor.
- [ ] Highlight the widget marker if `marker.time === hoveredConsoleMessage.time`.
- [ ] Highlight the widget if `widget.key === hoveredConsoleMessage.key`.

3) ❌ Hovering on a console message should highlight all of its **sibling console messages**.
- [ ] Highlight all console messages where `message.key === hoveredConsoleMessage.key`.

4) ✅ Hovering on a console message should update the **video**.

### Timeline marker hover interactions

1) ❌ Hovering on a timeline marker should highlight its corresponding **console message and its siblings**.
- [ ] Store the `hoveredTimelineMarker` in Redux.
- [ ] Highlight the console message if `message.time === hoveredTimelineMarker.time`.
- [ ] Highlight the console message (siblings) if `message.key === hoveredTimelineMarker.key`.
- [ ] Make sure that the highlighted console message is visible in the console.

2) ❌ Hovering on a timeline marker should highlight its corresponding **breakpoint widget and marker**.
- [ ] Open the marker's corresponding message's location in the editor.
- [ ] Highlight the widget marker if `message.time === hoveredTimelineMarker.time`.
- [ ] Highlight the widget if `widget.key === hoveredTimelineMarker.key`.

3) ❌ Hovering on a timeline marker should highlight all of its **sibling timeline markers**.
- [ ] Make each timeline marker aware of its corresponding key.
- [ ] Highlight all timeline markers where `marker.key === hoveredTimelineMarker.key`.

4) ✅ Hovering on a console message should show the **tooltip**.

### Widget marker hover interactions

1) ❌ Hovering on a widget marker should highlight its corresponding **console message and its siblings**.
- [ ] Store the `hoveredWidgetMarker` in Redux.
- [ ] Highlight the console message if `message.time === hoveredTimelineMarker.time`.
- [ ] Highlight the console message (siblings) if `message.key === hoveredTimelineMarker.key`.
- [ ] Make sure that the highlighted console message is visible in the console.

2) ❌ Hovering on a widget marker should highlight its corresponding **timeline marker and its siblings**.
- [ ] Highlight the timeline marker if `marker.time === hoveredWidgetMarker.time`.
- [ ] Highlight the timeline marker (siblings) if `marker.key === hoveredWidgetMarker.key`.

3) ❌ Hovering on a widget marker should update the **video.**
- [ ] Attach mouseenter event to widget marker that updates the video preview.
- [ ] Attach mouseleave event to widget marker that resets the video preview.

### Playback interactions

1) ❌ Playback should update what's displayed in the console.
- [ ] Use the `currentTime` instead of `pausedExecutionPoint` for `getClosestMessage`.
- [ ] Make the console scroll during playback such that the purple pause line is centered.
- [ ] Prevent console message "debug" bookmark from being rendered while in playback.
