### ISSUE TITLE
Consider combining source explorer and pause information panels

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1612]
While using replay I've found the separate source explorer and pause information panels to be pretty awkward to use.  These were initially confusing, and even after learning them I keep running into problems:

1. Trying to step but being in the wrong panel
2. Not being able to see the breakpoints when in the source explorer.
3. Wanting to see the sources in the same directory as the one I'm viewing, but being in the wrong panel.

I think it would be nicer if these were combined into one panel, maybe laid out like:

* Command bar
* Frame timeline (when paused in a frame)
* Sources
* Outline
* Breakpoints
* Call stack (when paused in a frame)
* Scopes (when paused in a frame)

Showing the sources and outline in the pause view doesn't seem like it would add too much clutter, and we'd be able to reclaim a lot of screen real estate by removing the panel selectors on the left side.

**Comment by jasonLaster** [comment]
Hmm interesting, this seems like something we can experiment with behind a flag. It's pretty easy to model in code...

I have felt this before too, but personally prefer the simpler UI. Pause panels are comfortable for us, but most folks will actually stick with print statements, which is okay too.

CC @jonbell-lot23 @jaril

**Comment by jonbell-lot23** [comment]
Wow, so we'd be doing it without tabs? I'd love to see a sketch of how it could be laid out, because if possible that could be really interesting.

Also a perfect example of something I can test via user research.

**Comment by jaril** [comment]
I personally prefer the no tabs. 

Tabs are cleaner visually, but functionally I don't see a strong enough argument for only being able to see either the source/outline vs breakpoints/callstack/scope – I like having the option of seeing them all the time. If it gets too distracting, perfectly capable of collapsing specific panels (e.g. source, outline).

It also simplifies the UI (one big list instead of tabs), which has the added benefit of sidestepping the question of whether we should force-open specific tabs in response to some action (e.g. pause => force open pause info). Less opinionated so the user can figure out what works best for them.

For next steps, let's discuss how to prioritize this when we discuss frontend things (Monday?) and then go from there. Given the split in opinion, Jon can take both versions to users and see which tests better.

**Comment by jasonLaster** [comment]
Following up on this discussion: It would be nice to offer a setting where users could combine these two panels

#1845
