### ISSUE TITLE
Refactor Markup view loading

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1707]
**Description:**
Looking at individual request [performance](http://admin.replay.io/performance/GetDocument), the markup view should be must faster than it is. Lets investigate where we're spending time and how to improve it.

**Comment by hbenl** [comment]
The markup view seems to be reasonably fast as long as the backend is fast for the requests that it needs (the ones in `NodeFront.ensureLoaded()`). Currently these requests are quite fast as long as they don't fail. However, every failed request seems to slow everything down by about 1 second and in some recordings there can be dozens of failed requests (depending on the recording _and_ the selected pause).
* I think we need to get the number of failed requests down (currently I'm seeing a lot of failures for `DOM.getBoxModel`, `DOM.getBoundingClientRect` and `CSS.getAppliedRules`)
* Notwithstanding that, the frontend could get a significant performance boost from a little refactoring:
  * we don't need all the information from `NodeFront.ensureLoaded()` for the markup view: only two of these requests (`CSS.getComputedStyle` and `DOM.getEventListeners`) are needed for the markup view, the others are only needed for the side panels (Rules/Layout/Computed), so we don't need to make them until the user selects the corresponding node in the markup view (which also means that we could make a lot less requests overall, since most nodes in the markup view are never selected by the user)
  * we don't necessarily need to wait even for those 2 requests: they're only used to show the "flex"/"grid"/"event" badges (and for showing a node in grey if it's not displayed) and we could start showing the node without these badges until the requests return
  * this would, however, require some refactoring: currently the entire Elements panel assumes that the information from those requests can be accessed synchronously for every node that is being displayed, this needs to be replaced by async logic

**Comment by jasonLaster** [comment]
closing as the elements panel is not a priority
