### ISSUE TITLE
[UX] Left Wing UI polish

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1734]
- [X] Timeline comment should be on the timeline, not underneath it -> Punting for now
- [X] Title of transcript should be "User Actions" -> Punting for now
- [x] Mouse events shouldn't have a border around them
- [x] On mouseover, "Mouse Click" and icon should turn blue
- [x] On click, "Mouse Click" and icon should turn purple
- [x] "Add a comment" text should be the same font size as "Mouse Click"
- [ ] Timeline shouldn't dim on hover #1672 
- [x] Only select one highlighted row
- [ ] The event should go above the comment
- [x] Change the overflow menu from three dots to the word "Edit"
- [x] Timestamp should use standard font, not monospaced

**Comment by jasonLaster** [comment]
@jonbell-lot23 could you add some figma examples for 

- [ ] Mouse events shouldn't have a border around them
- [ ] Timeline comment should be on the timeline, not underneath it

I think in general, we should scrutinize how markers look when they're close together. We always have the option of arbitrarily hiding some markers so we have more space.

**Comment by jaril** [comment]
Some follow-up questions for me – though we can discuss these at the meeting later:

> Title of transcript should be "User Actions"

What's the motivation behind this? When I'm in an app and I'm looking for comments, I expect it to be its own "Comments X/Panel/Window". I'd be confused if it was buried in a different window. And if we're going to be adding API calls/Network Events, "User Actions" would be inaccurate.

> Only select one highlighted row

Wanted to clarify the specifics here. Right now our select state is the same as our paused state. This is because clicking on a "card" (comment/event) seeks there, so by default, a select is a pause. 

And should that selected card be whatever the user clicked on last? In which case, the selected card will always be paused. But paused doesn't always mean selected, in the case of multiple cards per pause. What should the hover behavior look like for a selected card vs paused card?

**Comment by jaril** [comment]
Adding more discussion items related to the new Left Wing UI:
- A few weeks ago, we've made a change before to make it so that the timeline would either show 1) Transcript Events, or 2) Console messages. With the new change, it's possible for both the transcript and the console to be open at the same time. What happens to the timeline now?
- Would we want users to be able to leave a reply directly on an event? So click to seek+select an event, then right underneath it we would show "Type a comment ..." UI exactly like we would when you click on a comment.

Some opinionated takes:
- The timestamp on the right looks like an afterthought. Makes it very easy to make the mistake of thinking that the transcript is a message history sorted oldest -> newest by post date. Like Discord/Slack.

**Comment by jonbell-lot23** [comment]
![](https://user-images.githubusercontent.com/9154902/106662478-4e561280-6607-11eb-9ec5-0ba3eafe3f66.png)

Original reference for comments being on the same line and how mouse events shouldn't have a border.

**Comment by jonbell-lot23** [comment]
Key discussion items:

- [ ] What should the title be? Log + Comments?
- [ ] Selecting highlighted row bit
- [ ] What shows in timeline when you have comments and console open?
- [ ] Should we be able to add a comment to an event? (I think so, yup)

**Comment by jonbell-lot23** [comment]
I'd just like to say how excited I am to see these changes landing!
