### ISSUE TITLE
Windowing UX

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1737]
With the work planned in https://github.com/RecordReplay/backend/issues/1022, it is becoming more important to have a strong notion of windowing in the UI.

We should:

1. make sure that users can zoom in the timeline
2. ensure that zooming properly windows the console and breakpoint timeline
3. Add support for backend imposed windows, such as the last 10 minutes
4. Let the user set a new window 

[Notion page](https://www.notion.so/replayio/Replay-Windowing-UX-23764afe6a3940c9bb298f2ba4ab2826)

**Comment by jonbell-lot23** [comment]
Notion page -> https://www.notion.so/replayio/Replay-Windowing-UX-23764afe6a3940c9bb298f2ba4ab2826

**Comment by jonbell-lot23** [comment]
As I work on this, I'm going to take a step back and separate the insight from the implementation.

The insight is that we'll be taking steps on the backend to prune branch processes, and this has implications in the UI. Implementation-wise, we may well implement 1-4 above. But we should explore the space a bit first, because it's possible we address the insight with a slightly different implementation.

**Comment by jasonLaster** [comment]
closing as it is not a priority at the moment. the card will remain in planning and we can always re-open
