### ISSUE TITLE
Investigate alternatives to Auth0

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1761]
### Description

Auth0 has a couple of hurdles built in, but the biggest at the moment is the 3 day inactive window. There are several other options we could consider

1. clerk.dev a startup built with our usecases in mind
2. amplify + cognito an AWS option that is cheap and flexible 
3. memberstack another startup with other use cases as well

This decision can wait. What we have is okay for the time being.

### clerk

* works out of the box
* would offer multiple accounts easily
* would need to add an endpoint for temporary signed tokens

### Cognito

Hasura's setup docs are great: https://hasura.io/docs/1.0/graphql/core/guides/integrations/aws-cognito.html
dev.to turorial: https://dev.to/hasurahq/using-amplify-cli-for-adding-auth-to-your-hasura-graphql-engine-23f9

https://docs.amplify.aws/lib/auth/getting-started/q/platform/js
https://docs.amplify.aws/start/getting-started/auth/q/integration/react
https://www.youtube.com/watch?v=JaVu-sS3ixg

**Comment by jasonLaster** [comment]
A framework like next-auth might be nice to look at for best practices

https://next-auth.js.org/

**Comment by hbenl** [comment]
It looks like Cognito doesn't allow us to add custom fields to the access token (only to the ID token, but that doesn't help): https://stackoverflow.com/questions/56970499/aws-cognito-add-custom-claim-attribute-to-jwt-access-token

Actually it would be really nice if we didn't have to add custom fields to the access token, the only reason we need that is that Hasura won't take session variables from HTTP headers when you authenticate with an access token. We're not the only ones who would like to use HTTP headers for session variables: https://github.com/hasura/graphql-engine/issues/1601 - our lives (and those of others who also want to put a row ID in a session variable) would become so much easier if they implemented that.

**Comment by hbenl** [comment]
Features we need or want in an auth solution:
* using Google or other "social providers" as the Identity Provider.
* adding custom claims to the access token. We currently need this in our database permissions to protect the `recording_id` field.
* specifying callback URLs containing dynamic request parameters (in our case a recordingId) so that after authentication users can be redirected back to the recording they were viewing.
* not requiring users to login to Replay again every day.

**Comment by hbenl** [comment]
Memberstack doesn't support login with Google or other social providers: https://help.memberstack.com/en/articles/4487016-unsupported-use-cases , https://future.memberstack.com/problems/p/social-login-gmailgoogle

**Comment by hbenl** [comment]
I just realized that we may be able to drop the requirement for adding custom claims to the access token if we use Hasura's [authentication using webhooks](https://hasura.io/docs/latest/graphql/core/auth/authentication/webhook.html), which gives us more control.

**Comment by hbenl** [comment]
The requirement "specifying callback URLs containing dynamic request parameters" is considered potentially insecure and the spec explicitly forbids this.
Instead, a `state` parameter for the authentication process was introduced to make such a redirect possible.
In Auth0, this can be accessed using the [`RedirectLoginOptions.appState` property](https://auth0.github.io/auth0-react/interfaces/auth0_context.redirectloginoptions.html#appstate), which we get back in [`onRedirectCallback`](https://auth0.github.io/auth0-react/interfaces/auth0_provider.auth0provideroptions.html#onredirectcallback).
However, implementing the desired behavior is currently complicated by the fact that we need to initialize Auth0 with a `recordingId` (so that it is added to the access token), but can only get the correct `recordingId` *after* Auth0 was initialized. One more reason to consider using Hasura's webhooks so that we don't need to add the `recordingId` to the access token anymore.

**Comment by jasonLaster** [comment]
After @hbenl investigated, it looks like we can make significant improvements with auth0 and it is not worth switching at the moment
