### ISSUE TITLE
[UX] Add a settings pane

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1845]
**Description:**

It is time to finally have the conversation about user settings

1. enable experimental features
2. customize the ui in specific ways: for example show the source tree and pause data in one panel #1612 
3. there should be a toggle for whether recordings are public/private by default

**Comment by jonbell-lot23** [comment]
Making progress!

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/9154902/109446649-f5af5380-7aa6-11eb-8d70-61620773fd51.png">

This is a foundational element because it's fixed to the navigation, so I'm making sure I'm designing something that scales.

In this design, selecting Sharing pops the same dialog that we have today, and settings has a similar pattern.

**Comment by jasonLaster** [comment]
Wow! There are so many details here that I love

**Comment by jonbell-lot23** [comment]
Alrighty, here's the pattern and general layout. Exact details up for discussion.

<img width="916" alt="Appearance" src="https://user-images.githubusercontent.com/9154902/109571796-10d69d80-7b51-11eb-843b-0a85dac3fec8.png">

<img width="916" alt="Team" src="https://user-images.githubusercontent.com/9154902/109571804-146a2480-7b51-11eb-8767-eeee5f21be11.png">

<img width="916" alt="Privacy" src="https://user-images.githubusercontent.com/9154902/109571818-19c76f00-7b51-11eb-9951-303c22902948.png">

<img width="916" alt="Experimental" src="https://user-images.githubusercontent.com/9154902/109571847-2946b800-7b51-11eb-933f-80159dbce00b.png">

<img width="916" alt="Support" src="https://user-images.githubusercontent.com/9154902/109571863-2d72d580-7b51-11eb-8db9-3422c3a45b09.png">

**Comment by jonbell-lot23** [comment]
Wooooooooo!
