### ISSUE TITLE
Open Sharing preferences is empty for accounts

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1864]
![](https://cdn.discordapp.com/attachments/798693728999047203/812328632327733268/unknown.png)

**Comment by hbenl** [comment]
It's interesting that it's empty for you - for me it shows this (in Firefox, Chrome and Brave):
![Screenshot_2021-02-26_12-30-06](https://user-images.githubusercontent.com/16060807/109295191-95ae7800-782e-11eb-98c6-6d47f150bee8.png)

Currently the reason is that the SharingModal tries to access the recordings table directly, which produces the error `\"x-hasura-recording-id\" header is expected but not found` due to the permissions on the recordings table referencing that header.
But even without those permissions the SharingModal doesn't work in the Accounts page because it uses the global `recordingId` property from redux, which is only set when viewing a recording.
