### ISSUE TITLE
Variables show up as optimized away

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2058]
STR

1. Visit this replay: https://replay.io/view?id=1c67639b-0ff0-4825-be7d-aa71bcdcd840

2. Set a breakpoint on node_modules/lodash/lodash.js line 3268, and jump to one of the points (I also set a comment on one of these points, but clicking on it doesn't work due to https://github.com/RecordReplay/devtools/issues/2057).

3. Look at the scopes pane, and see that all variables are optimized out.

4. Hover over the variables or evaluate them in the console, and see that their correct values are available.

Expected

The variables should not be optimized out.

**Comment by hbenl** [comment]
Here's a recording of that recording, with comments showing the scopes that are loaded from the backend: first the generated scope chain is loaded, in which all values are available, then the original scope chain with all values marked as unavailable: https://replay.io/view?id=f78a67f6-b32e-44d3-80f3-b70fcf61cbe8
So I guess this is a sourcemapping issue.

**Comment by loganfsmyth** [comment]
This is happening because Webpack by default generates line-based mappings. Only code run through Babel ends up with token-level mappings, and line-based mappings are way to low-res for us to map them in a useful way. Generally `node_modules` files are skipped for Babel processing (like Lodash here).

I'll look into adding some logic to fall back to the generated scopes properly so that we don't just show all-optimized-away.

Here's an example of the mappings of this function:
<img width="1041" alt="Screen Shot 2021-03-16 at 6 11 11 PM" src="https://user-images.githubusercontent.com/132260/111399863-75324a80-8683-11eb-8d0b-16e16d53b869.png">

so as you can see, there's no variable-level mappings, every mapping is a whole line with potentially many variables references by the same mapping.

**Comment by hbenl** [comment]
> I'll look into adding some logic to fall back to the generated scopes properly so that we don't just show all-optimized-away.

Should this be done in the backend or in devtools?

**Comment by loganfsmyth** [comment]
I'm planning to change the backend to not send original scopes if the scopes are all line mappings.

**Comment by loganfsmyth** [comment]
@bhackett1024 @kannanvijayan  With this, the main thing that's tripping me up is that we send `originalScopeChain` when the frame is created, which means we either need to send scope IDs that then later could fail to return a scope (if mapping failed), or else the client would have to know that it could get a scope back with useless bindings or something. It's already not necessarily trivial to parse the original file for each frame (I'd imagine), and the additional logic I'll have to add here to ignore original scoping if things aren't mapped is likely to make things slower, so I'm concerned that this will slow down creating of Pause objects.

I'm wondering if it might be cleaner to have a separate API endpoint to get the original scope chain of a frame, like `Pause.getOriginalScopeChain({ frameId })` or something. 

Thoughts?

**Comment by bhackett1024** [comment]
The idea behind the way the API is currently designed is that the backend should eagerly send information about original sources (locations, scopes) to the client, because (a) that is almost certainly what the client is interested in, and (b) using separate commands to get original data requires an additional round trip between the client and server, which adds an unavoidable delay of potentially hundreds of milliseconds before the client has what it needs to start rendering.  If computing original data adds significant delays, that is at least something we can optimize entirely within the controller.

**Comment by loganfsmyth** [comment]
Fair enough, I can make the changes I need and we can worry look into the perf if it seems noticeable.
