### ISSUE TITLE
Excalidraw: zoom is not undefined

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2158]
**Description:**

The sourcemaps have two issues:
1. `zoom` should map to `e`
2. `deltaX` should map to deltaX and not `appState` 😂 

**Steps to Reproduce:**

1. go to [https://replay.io/view?id=3a3c7c94-7dca-4a6b-82fa-a12a776006f0](https://replay.io/view?id=3a3c7c94-7dca-4a6b-82fa-a12a776006f0) 
2. go to App.tsx:3977 for `"bug", zoom` 
3. Notice how zoom is undefined, even though in the generated code it is in scope as e
4. Notice how `deltaX` returns `appState`

**Replay:**

https://replay.io/view?id=241d5430-0755-4381-bb01-7f2a82a66504

**Comment by hbenl** [comment]
I've also seen wrong sourcemapping of scope variables in #1815

**Comment by loganfsmyth** [comment]
This is minification confusing things. The breakpoint on that line is just _after_ the `setState` function at the return location of the function here https://github.com/excalidraw/excalidraw/blob/32427c355c0913c784e49c487a78a2ac45b2dca0/src/components/App.tsx#L3977 so `zoom` is not in scope there, but the sourcemaps are mapping the return position as part of `value,`.

<img width="1224" alt="Screen Shot 2021-03-22 at 1 28 43 PM" src="https://user-images.githubusercontent.com/132260/112054241-8e6b4900-8b12-11eb-9db7-19c5851ec4e4.png">

Note how the right-hand range starts way back at 254367, but the actual breakpoint we're hitting is at column 25476 (might be off by one, not sure if these numbers are 0-based or 1-based, but close enough). Since that's right in the middle of the mapped range, it gets treated as having the same location as `value`.

A lot of sourcemap generators don't bother assigning a mapping location to a function's final `}`, so this is probably gonna be kind of common. I'm not sure what we can do about it except potentially excluding implicit-return positions from the set of step points.

**Comment by jasonLaster** [comment]
It looks like excalidraw uses `react-scripts: 4.0.3`. Perhaps we can file a bug report there with a minimal test case?

This way we can hopefully treat the problem at the source, webpack etc...

**Comment by loganfsmyth** [comment]
Most likely this is something that would have to be addressed in terser, assuming that's what is doing the minification here.

**Comment by jcmorrow** [comment]
For now, going to close this in favor of the Issue page for Source Maps (which tracks work that is valid, but not currently on the immediate roadmap): https://www.notion.so/replayio/Source-Map-Issues-e761f8ac000d4bcd94adb9a8c2f74d38
