### ISSUE TITLE
Replay crashing reliably

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2238]
Here's the source URL: https://deck.gl/examples/geojson-layer-paths/
Here's the Replay: https://replay.io/view?id=9c18bc86-ac18-4491-aefb-67f950eaa408

Mentioned in discord by wuweiweiwu

**Comment by bhackett1024** [comment]
The problem here is that while we prevent creation of WebGL canvas contexts there are also WebGL2 canvas contexts which can be created and are causing these crashes.  https://github.com/RecordReplay/gecko-dev/commit/0b806a08ff3b26f2a8505a9804eacb76e5c11c32 fixes this and the page now records/replays reliably, though the canvas isn't rendered at all when recording.

**Comment by bhackett1024** [comment]
This works in the latest browser now, here is a replay: https://replay.io/view?id=159264fc-e5c8-44b2-bfd8-866cd13fead5
