### ISSUE TITLE
Can't view recording I uploaded

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2279]
I created a recording with authentication disabled so that I could record another problem I was seeing running the devtools locally.  Trying to view that recording shows a "This replay is uploading, try again in a moment" error, even though the recording actually *has* uploaded.  Checking out cdbff4adec1e955649bb7bf0b395b16c84993752 and trying to view the recording with that version of the devtools works fine.  Here is a replay:

https://replay.io/view?id=3a1db395-e1e0-449c-82a4-44fbaaf34898

**Comment by jasonLaster** [comment]
It looks like we should be able to handle the case where a replay does not have an associated user, by showing the DraftScreen when a replay is not initialized and doesn't have a user_id. 

With that said, I am not sure we want to. Many of the exceptions we have seen over the past week have come from the fact that our types assume the data is stricter than it is. For instance, from a product perspective, it is reasonable to assume that recordings will be associated with a user, since users have to be logged in to create a recording. 

Let's discuss this and then figure out what we want to do here

here is a replay with the change and comments
https://replay.io/view?id=56ca4a2e-9b5e-4237-8568-09e63eeb50ea&point=7139408181691504139136720560983418&time=3744.8870285810926&hasFrames=true

**Comment by bhackett1024** [comment]
The frontend absolutely has to be robust enough to deal with any recording it encounters.  We can't assume that recordings were created with a user.  Many of our automated tests have no associated user, and requiring that would be a pain to support.  We're building a toolkit here, and have to deal with the full breadth of applications of those tools.

**Comment by bhackett1024** [comment]
Oh, and I don't know what the draft screen is, but we need to show the recording itself.  Why was I not involved when we were making these huge changes to the workflow around creating and viewing recordings?

**Comment by jasonLaster** [comment]
> Many of our automated tests have no associated user

That's a good point. We should not break existing workflows. I think it is a good idea for our automations to have an associated user/account. We do this in an adhoc way now for our e2e tests [here](https://github.com/RecordReplay/gecko-dev/blob/webreplay-release/devtools/server/actors/replay/connection.js#L391-L398), but we should have a proper approach.  

Alternatively, we can also explore a simple devtools app that does not have authentication and is just for replaying a recording. This might be useful going forward as the frontend will be increasingly user/team centric.

> draft screen

The draft screen was documented [here](https://github.com/RecordReplay/devtools/issues/2176), discussed in #design, and the planning calls. We noticed the friction as well and the draft screen will be folded into the viewer soon [issue](https://github.com/RecordReplay/devtools/issues/2255).

**Comment by hbenl** [comment]
This has been fixed in the meantime.
