### ISSUE TITLE
Sources can take awhile to load on first click

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2383]
**Description:**

**Steps to Reproduce:**

1. go to https://replay.io/view?id=dfc5229d-18ae-43f5-a21d-26c106f565f1&point=4867778305863999227200989678272648&time=3616.9841624743804&hasFrames=true
2. go to devtools
3. click on the setupTelemetry link 
4. wait awhile
5. click again, it loads

**Comment by hbenl** [comment]
Just tried your STR, but the source loaded pretty fast for me (~2 seconds on the first try, on the second try the source was there as soon as the devtools UI showed up).

**Comment by jasonLaster** [comment]
Ooh, sorry I never included a replay of what i was seeing. Will go get one

**Comment by jasonLaster** [comment]
Here's a replay https://replay.io/view?id=1afb1e5b-efd5-484c-95a0-771c50afa7fd

**Comment by hbenl** [comment]
The underlying cause was that we didn't open the comment's source location directly, but only seeked to the comment's ExecutionPoint and relied on some general logic to fetch the frames for that ExecutionPoint and open the source location of the top frame. But fetching the frames took a long time in that case because `Session.createPause` was slow. See also RecordReplay/backend#1034.

**Comment by jasonLaster** [comment]
Thanks! Love this write up
