### ISSUE TITLE
Viewer does not fetch new screens

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2463]
**Description:**

When I seek in the viewer initially, the canvas does not update. After playing the video, seeking works though

https://replay.io/view?id=6e09bd8d-3238-4f8d-ba42-e3f1686e4ed5&point=36670596567646705257392725829878848&time=15511.104643557881&hasFrames=true

**Comment by jasonLaster** [comment]
This might be fixed

**Comment by hbenl** [comment]
When I try to investigate in that recording, I get a lot of "This part of the recording has been unloaded" errors.
But when I open `ui/actions/timeline.ts` and set logpoints at lines 131, 133 and 134, it looks like some screenshot downloads took a long time and then they weren't painted because the current time has changed (i.e. another click in the timeline happened) in the meantime.
Anyway, I couldn't reproduce this and the code in question has been heavily rewritten in the meantime, so I assume this is fixed.
