### ISSUE TITLE
Invalid breakpoint locations

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2482]
**Description:**
I noticed while playing with a replay of checkly that breakpoints in one of the files kept throwing invalid location

orignal replay: https://replay.io/view?id=447862fb-8716-454c-9df5-d9170561fbea&point=36995115119955335297599016873754794&time=13407.019675125219&hasFrames=true

Replay: https://replay.io/view?id=9a84a016-45d2-4637-a6cd-f69a942365c1&point=86646453860603916231275196140488022&time=39661.53658274155&hasFrames=true

**Comment by loganfsmyth** [comment]
This appears to be because the frontend is breaking assumptions we make on the backend around round-tripping source file locations. The client is only supposed to send the backend original locations if the locations came from the backend originally, which means that it is unsafe to for instance get a position on one original source, and apply it to an different original source (even if they have the same URL and same content). That is exactly what is happening in this case with https://github.com/RecordReplay/devtools/blob/78165d6295d4fc95a9b8cadefc0c5503854880d3/src/protocol/logpoint.ts#L318

because a given URL may have multiple source actors for the given URL, but you can't give an arbitrary position for a URL unless the position came from the server first. That function in its present form seems to be inherently unsafe. 

When getting possible breakpoint positions, the frontend should query _all_ server-side sources for associated with the frontend's "source", and when you click on a line to analyze, we should be getting the set of `locations` to send in the analysis by getting the position for each server-side source, instead of getting the list of IDs and creating the list of positions based on the response for just one of the sources.

The quick fix here is probably that we can send `getPossibleBreakpointPositions` for every source but ignore the result and hope it is the same and it'll probably work, but it's a bit ugly and is very much relying on side-effects

In general the fact that the frontend tries to unify the views of multiple sources into one here is causing this confusion. Even if the frontend wants to present multiple files as a single file, it should still be individually performing operations on the individual sources or else things are going to crop up like this.

**Comment by loganfsmyth** [comment]
I don't know if I'm the right person to dig into this more or if you want to look at it @hbenl

**Comment by hbenl** [comment]
The root cause for this seems to be that we throw away the location's `sourceId` and then all we have to work with is the `sourceUrl`, and there are only 2 options in this case: try with all `sourceId`s for the given `sourceUrl` (even if that means potentially running into some errors) or give up straight away.
Luckily, we have the `sourceId` initially, it just gets thrown away here if we have a `sourceUrl`:
https://github.com/RecordReplay/devtools/blob/b99206410885593c2aff9620fff2de240e99efeb/src/devtools/client/debugger/src/utils/breakpoint/index.js#L62-L66
I have created a minimal PR for this, but I think the code could be further simplified, in fact I think the `makeBreakpointLocation` method is a superfluous holdover from Firefox devtools because the `sourceId` and `sourceUrl` that it computes should always be identical to the `sourceId` and `sourceUrl` that it gets from its `location` argument (at least they were in my experiments).
@bhackett1024 Do you think this is correct or do you know any use cases where the code in `makeBreakpointLocation` does something useful?

> That is exactly what is happening in this case with https://github.com/RecordReplay/devtools/blob/78165d6295d4fc95a9b8cadefc0c5503854880d3/src/protocol/logpoint.ts#L318
> 
> because a given URL may have multiple source actors for the given URL, but you can't give an arbitrary position for a URL unless the position came from the server first. That function in its present form seems to be inherently unsafe.

@bhackett1024 I have seen similar code in `ThreadFront.setBreakpointByURL()` - are there legitimate use cases for this or should we work towards getting rid of this code?
