### ISSUE TITLE
Add back opening replays in a new tab

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2578]
We used to have this as a feature that showed up on hover. 

Hovering on a replay in the library used to show an "Open in New Tab" button to the right of its title. It would be nice to bring it back to keep users from unintentionally navigating away from the library.

**Comment by jonbell-lot23** [comment]
I'm going to reverse myself on this one, I think because I misread it the first time. There are a few approaches:

1. Make everything in the library open a new tab
2. Make everything in the library use the same window (you can always command-click to a new tab)
3. Add a new button for "open in new tab"

I don't like to recreate standard browser behaviour in UI. I'd rather stick with standard web patterns (click goes to a new page, and you can command-click to open a new tab) for now. We're also bringing the back button back to the nav, which will help.
