### ISSUE TITLE
Dragging breaks the timeline

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2601]
**Description:**

I think it is possible to drag the progress bar head outside of the bounds of the viewport and then have the timeline be meaningless.

Also, viewing that replay url is bad, so it probably has something to do with the saved time

STR:
1. drag the timeline off the current browser viewport
2. click around in the timeline

notice the time is off

**Comment by hbenl** [comment]
I think the real issue is that dragging the timeline can inadvertently trigger our timeline zoom feature (due to how it is implemented in https://github.com/RecordReplay/devtools/blob/master/src/ui/components/Timeline/ScrollContainer.tsx).
We should probably disable that feature for now and bring it back sometime after launch with a better UX.

**Comment by loganfsmyth** [comment]
Also just ran into this. 
![Kapture 2021-06-04 at 11 25 51](https://user-images.githubusercontent.com/132260/120846980-ba01ab00-c527-11eb-9a6c-433155d59a19.gif)

**Comment by jasonLaster** [comment]
Makes sense. Zoom will require more thought
