### ISSUE TITLE
New comment is adding to line of code rather than x,y value

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2636]
Discord:

Hey @Jaril here's a funny bug. Person A files a bug on a line of code and shares Replay with Person B. Person B clicks on the video to add a comment and it jumps to that line of code rather than an x, y value as expected: https://share.descript.com/view/Z6O7XIvdBdR

**Comment by jonbell-lot23** [comment]
https://replay.io/view?id=5e9ce074-4037-4622-aa6c-78680af24777&point=11358149378062223495372010325803081&time=6168.359307359307&hasFrames=true the Replay is here

**Comment by jaril** [comment]
Good catch! Can be a bug/feature, depending on how you look at it.

In this case, you happen to be paused at a line of code. That's why adding a comment, regardless of the entry point (breakpoint widget, video), ends up attaching to that line of code.

I see how it could be seen as unexpected behavior ("I just wanted to leave a comment on this part of the video, why is there a line of code here?"). This can be especially confusing for non-technical folks.

That said I'm hesitant to take the behavior out. It's possible for both pieces of information (x/y and line of code) to be relevant to the comment (e.g. "Right before we check the DOM for <HTMLElement>, the <HTMLElement> is not where it's supposed to be"). It's not ideal if a non-technical person ends up in this scenario, but the UX paths leading there are limited (Have to click on a line-of-code comment to navigate, then add a comment via video).

Thoughts? @jonbell-lot23 @jasonLaster

**Comment by jonbell-lot23** [comment]
Great points! This is a fun one. Here are some insights/principles:

* People click on comments as a way to navigate the video playback.
* Un-selecting all comments is not an easy action. (You can click another comment, but you have to go down to the timeline to jump to another point in time to shake off the currently selected comment and be left comment-less.)
* The tooltip (and resulting ebbing marker) provides an extremely powerful signal that we're referring to a point in time

So I'll pause there for now. But that's the starting point. It's easy to get into this state by accident, and very hard to explain why it's appropriate to attach to a line of code. But the devil is in the details, of course. Stay tuned

**Comment by jonbell-lot23** [comment]
@jaril I've thought about it and here's what I think:

#1 We could keep as-is: not possible to add x/y when on a line of code
#2 We could make it impossible to add a line of code by clicking on an x/y
#3 We could provide a dialog (Did you want to attach this to a line of code? Y/N)

I think the best solution is #3. The other two feel broken based on the use case. I'd recommend going with #2 for now, then gathering data to see how it feels, then probably ending up at #3. Thoughts?

**Comment by jasonLaster** [comment]
Ooh, funny. I might be coming at it from the completely different perspective.

I feel like comments will have some attributes (x/y, time, source location), great! keep em coming. If that's the case we just have to be strategic about how we show the right attributes in the card.

**Comment by jonbell-lot23** [comment]
For this item, let's change the text of the comment to "Add a comment to this line of code" so at least it doesn't feel like a bug/surprise. Then we can handle a more robust solution later.

**Comment by jasonLaster** [comment]
Yep. Or add a bit of an explainer in the card the first time you do this. 

IF entrypoint == video and location exists, SHOW tooltip...

**Comment by jonbell-lot23** [comment]
Re-upping this item as part of my polish refresh. Jaril, for now let's do this:

* Change the text to "Add a comment to this line of code"

The problem with tooltips is they're easily clicked through and forgotten. I want the text to be clear about what it's going to do, every time. Bedrock rule of UX: explain the implications of a potential user action.
