### ISSUE TITLE
Error shown during a recording but not otherwise

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2653]
Check out this Replay: https://replay.io/view?id=677e6336-b931-459e-b8b7-0511f0aea580

(Currently private and only viewable by @jaril @jasonLaster )

Brett is seeing this error but only when recording:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/9154902/118738367-0055d980-b89b-11eb-8a3d-346b53386bbb.png">

**Comment by bhackett1024** [comment]
This will be hard to fix without STR

**Comment by jonbell-lot23** [comment]
Will reach out to get more details

**Comment by 01brett** [comment]
After talking with my CTO, I think this is actually a "me" problem and not Replay. I suspect the fancy proxy whiz-biz to dev locally in HTTPS is causing this. I tried to reproduce the error and found cases where I couldn't reach the server due to HTTP/S mismatch. We apply the certs for that locally (somehow) to Firefox. I think we can safely close this issue.

**Comment by jonbell-lot23** [comment]
Thanks @01brett !
