### ISSUE TITLE
Comments are appearing twice

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2707]
Here's a Replay of it happening:
https://replay.io/view?id=d6f3ab9a-e239-4327-af9f-d3c3c4507a62&point=63281117965750637592966732904924625&time=24230&hasFrames=false

Optimistic comments seem to have a bug

**Comment by jaril** [comment]
Yes, this is related to optimistic comments. Specifically, it occurs when you have both optimistic comments and comment polling (every X seconds) in place. 

Based on my limited digging, it looks to be some problem with Apollo not being aware that the optimistic comment and the new comment appearing after a poll is the same. Will need to debug it more.

**Comment by jonbell-lot23** [comment]
Thanks for the info! From a UX standpoint, here are the best and second best approaches:

1. Have it appear immediately and never double up
2. Throw a spinner until we're 100% sure it's posted correctly

**Comment by ryanjduffy** [comment]
@jaril little more data for you ... I added a `setTimeout` to defer landing the committed data which helped repro the duplicate comment from polling.

https://replay.io/view?id=304ea995-fcf9-49dd-8fab-135c7ec432fa&point=48028745945354581787087575348937557&time=22175.681922547068&hasFrames=true

Will be curious if apollo has any feedback but I expect that we'll need to send an extra data element to the backend to facilitate merging on polling. I don't see how else the front end (either our code or apollo) can know to merge the optimistic data with the real data. for example, add a method for generating semi-unique id and set that as the `id` for the optimistic data and the `clientId` for both the optimistic and data sent to the server so that you can reliably merge on `clientId`.

The other option would be to pause polling (or at least enqueue polled responses) while waiting on an optimistic response. We could do some version of this in our code but likely could be handled more elegantly in apollo code since it could index polling queries on the `__typename` and manage them internally.
