### ISSUE TITLE
Add e2e test for showing mouse events

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2718]
See https://github.com/RecordReplay/devtools/issues/2680

We should make sure that mouse events are drawn to the screen when present in the recording.  I don't think there is an easy way to add mouse information when recording using our current test runner, but it seems like we could fake some mouse info using the test harness when replaying and make sure they end up being drawn.

**Comment by hbenl** [comment]
@bhackett1024 How can I create a test recording that contains mouse events? I tried some variations of `document.dispatchEvent(new MouseEvent("mousedown"))` but those events don't show up in the recording.

**Comment by bhackett1024** [comment]
I don't think there is a way to create recordings with mouse events included.  Would it be reasonable for the test script to add dummy mouse events to the thread front and then check that those mouse events are actually rendered?  This would let us test the functionality within the devtools at least.  An alternative would be to add a way to fabricate mouse events when recording like we do with the `dump("RecReplaySendAsyncMessage Example__Finished")` hack, but that will require more plumbing.  Longer term I'm hoping we can switch to use playwright for our test harness, which should make it easier to fabricate mouse inputs (among other things).

**Comment by hbenl** [comment]
I'm getting increasingly doubtful about how useful this test can be. We'd be testing that some only-used-in-tests code can transmit data to some other only-used-in-tests code. We would _not_ be testing that mouse events are recorded or that recorded mouse events are shown.
If we used playwright, we could at least test that mouse events are recorded. But if we're not analyzing the canvas content, we're not testing that they are shown. In particular, such a test would _not_ catch #2680 (which was the original motivation for writing that test), because in that case the mouse events were actually drawn, but the canvas drawing operations were done in the wrong order, so the screenshot was drawn over the mouse pointer.

**Comment by hbenl** [comment]
The next step will be to use tailwind in our e2e tests.
