### ISSUE TITLE
New onboarding screens for team name, invite, and domain

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2720]
Welcome to Replay:
https://play.tailwindcss.com/eQU2UemdTa
![image](https://user-images.githubusercontent.com/9154902/120123377-afcb6e00-c202-11eb-9dca-10fc2811cdfa.png)

(the margin is too wide around the helper here, we should tighten it)

Add people:
https://play.tailwindcss.com/hDe6G60qbo
![image](https://user-images.githubusercontent.com/9154902/120123389-bc4fc680-c202-11eb-832d-be93b2c80efa.png)

(Might as well use the same add/invite control we use elsewhere here)

**Comment by jonbell-lot23** [comment]
Welcome to Replay:
https://play.tailwindcss.com/eQU2UemdTa
![image](https://user-images.githubusercontent.com/9154902/120123377-afcb6e00-c202-11eb-9dca-10fc2811cdfa.png)

(the margin is too wide around the helper here, we should tighten it)

Add people:
https://play.tailwindcss.com/hDe6G60qbo
![image](https://user-images.githubusercontent.com/9154902/120123389-bc4fc680-c202-11eb-832d-be93b2c80efa.png)

(Might as well use the same add/invite control we use elsewhere here)

**Comment by jaril** [comment]
1) PLAYER ONE (#2720)

They click a link from their e-mail (because they were invited to Replay)
Sign in 
See the modal prompting them to create a team (Don't show the current new replay modal)
Create a team
Invite people to the new team (step 2)
Given an invite link (step 3) [DON'T DO THIS YET: SECURITY IMPLICATIONS]
Optional: Show checkbox for allowing any similar domain folks to be automatically invited to the team. (step 4)
Show them that team

**Comment by jonbell-lot23** [comment]
I'm looking through our onboarding tasks and this is a note to say Jaril and I discussed this today. It's getting close!

**Comment by jaril** [comment]
The main part of this onboarding screen is finished. Going to split out the remaining work into two issues:
- Allow the user the invite team members during the team leader flow #2801 
- Add support for invite links #2802
