### ISSUE TITLE
[Inspector] Breadcrumbs fail

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#277]
It looks like there is a simple issue with the breadcrumbs ui failing because of `KeyShortcuts` not being defined

https://webreplay.io/view?id=0d103e3d-3f46-4a6a-8994-a2f3b9daeab5

**Comment by hbenl** [comment]
`KeyShortcuts` is `undefined` because it is imported using `loader.lazyRequireGetter()`, which doesn't work in this project.
But this doesn't seem to be the only problem: if I uncomment the body of `initKeyShortcuts()` (which contains the only reference to `KeyShortcuts`), the error message doesn't appear anymore, but clicking the breadcrumbs still doesn't work...

**Comment by jasonLaster** [comment]
Oh interesting, i thought i fixed the KeyShortcuts issue. 

But yeah, that's what i found too... one theory i had is that there is now some new async paths that didn't exist earlier. 

Another theory was that for some reason breadcrumbs were no longer wired up
