### ISSUE TITLE
Improve Events

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2900]
[Note: this is outdated, stay tuned]

We're going to be updating the Console Events with these steps:

- [ ] Console and Events will now be split into separate tabs
- [ ] Jason mentioned that we should remove events we're not tracking
- [ ] Events will get a new sidebar filter

----

- [ ] Show keyboard and navigation events  https://github.com/RecordReplay/gecko-dev/issues/440

**Comment by jonbell-lot23** [comment]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/9154902/122690785-88a31200-d27f-11eb-83f4-b6d1ff04e59a.png">

Let's go in this direction:

* Put the events into their own tab/pane
* Toggle triggers accordion to show granular filters
* As a follow-up task, we should add counts

**Comment by jonbell-lot23** [comment]
* Jon to put together video to get buy-in
* Notes: this is a landing page thing!

**Comment by jonbell-lot23** [comment]
Note: this is now outdated, stay tuned.

**Comment by jasonLaster** [comment]
Here is the description from 2490

Starting a conversation here around how we let users filter/view types of console messages (errors, warnings, logs, exceptions) etc

Here are a couple UX things
- [ ] re-style the dropdown to be consistent with tailwind dropdowns
- [ ] badge the cog so that it is clear things are selected
- [ ] show counters next to options so we can see how many items are in each bucket
- [ ] separate exceptions into their own group since they're not console.x messages



<img width="458" alt="Screen Shot 2021-05-03 at 10 07 06 AM" src="https://user-images.githubusercontent.com/254562/116908170-6f72d300-abf7-11eb-81c6-52c082d42cbf.png">

**Comment by jonbell-lot23** [comment]
This issue got very messy. Declaring bankruptcy and starting fresh over here: https://github.com/RecordReplay/devtools/issues/3203
