### ISSUE TITLE
[Replaying] json is not in the local scope

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#291]
STR:

1. go to https://webreplay.io/view?id=6aaa4aa7-b55c-46f8-9d5c-b58c3bc91df2
2. set a breakpoint in `lib/user.js#25` 
3. rewind to the last hit

Notice that `json` returns a value in the console, but is not visible in scopes
Looking at the generated code it is definitely in the scope, but the mappings are pretty bad. 

Expanding the first scope, `user` is in arguments, but it is declared in the generated code and should map to the original. 

Note, the mappings are better in firefox nightly

---

### Original Scopes
<img width="1193" alt="Screen Shot 2020-07-31 at 8 14 11 AM" src="https://user-images.githubusercontent.com/254562/89049918-d7ae2480-d306-11ea-9d88-cc509ee2a9ff.png">

### Generated scopes
<img width="1483" alt="Screen Shot 2020-07-31 at 8 15 46 AM" src="https://user-images.githubusercontent.com/254562/89049914-d7158e00-d306-11ea-935a-8b3e11cd30a0.png">

### Nightly

<img width="993" alt="Screen Shot 2020-07-31 at 8 20 08 AM" src="https://user-images.githubusercontent.com/254562/89049906-d3820700-d306-11ea-8188-7af434b783ee.png">

#### Getting the app setup locally

This app is the POC recordings app. The setup is 

1. go to https://github.com/miriambudayr/web-replay-test
2. clone the repo
3. npm install; npm run dev
4. go to localhost:3000 and signup with a fake account I used my email with a `+1` at the end
5. add a breakpoint in `lib/user.js#25`

**Comment by bhackett1024** [comment]
This issue is tricky.  So, our current behavior is that when we see scopes that include bindings both with and without original names, we only show the ones with original names (except "arguments", see getBindingVariables in getVariables.js).  In this case that hurts us, because the "json" variable is the same in the generated and original sources, so it won't have rename entries in the source map and won't have an original name in the final scope, and we ignore it.

I see a couple ways forward:

a) There isn't really a great way to deal with this using our current strategy --- we either don't show the "json" variable, or we show it along with all the other junk variables in the generated scope which we can't tell apart from "json".  Both of these are suboptimal, but we could default to one and have a checkbox or something to switch to the other.  This option is pretty unappealing.

b) Parse the original source to figure out the structure of the scopes and the names that the user will actually be interested in.  This is what Firefox is doing, so it can show "json" without the junk variables.  This also lets Firefox determine the structure of the scopes and how that differs from the actual generated scopes, so it can show the actual original scopes instead of the generated scopes with names mapped to their original versions.  The downside of doing something similar to Firefox is that Firefox's scope mappings are unusably slow in a lot of cases, so they're off by default.  We should be able to avoid that by not parsing the generated source: we have more information than the Firefox devtools as we track the source location of each in scope variable now, and if that's not enough we can modify spidermonkey to give us whatever we need.  Even if we still need to parse the generated source we can leverage the compute power in the cloud to make sure performance stays good.  This option is much more appealing, but it's also a substantial project.

It would be interesting to see what this looks like in Chrome.

**Comment by bhackett1024** [comment]
We now have a babel-based system in place in the backend for constructing original scopes, per (b) above.  The original scopes in this recording look pretty good now.  One thing here is that we never show the window as part of the original scopes now.  I could fix that, but it seems alright to leave as is --- when using source maps the window properties aren't generally relevant.

<img width="927" alt="Screen Shot 2020-08-13 at 9 43 55 AM" src="https://user-images.githubusercontent.com/1062578/90179763-aa6f6680-dd49-11ea-81bd-66b44e72864d.png">

**Comment by jasonLaster** [comment]
Happy not having window. Perhaps down the road we can show all of the user defined global fields, but at the moment it feels like overkill
