### ISSUE TITLE
Does SOURCE 27 have a filename?

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2987]
@andarist is pretty sure source 27 should have a filename. Let's see what's going on here

> This doesn't show a filename or anything useful. I know it might even be coming from eval or some other esoteric stuff so that might be expected - but I have a feeling that it's not. Can't be sure though. In addition to that - this source doesn't get prettified which is a problem becasue I can't setup breakpoints in it.

https://replay.io/view?id=a486a6d4-c30d-4391-b140-5f583cdf3a08&point=74963785911711832975260339536921895&time=28224&hasFrames=false

**Comment by Andarist** [comment]
Well, im not 100% sure but its a production site so i suspect that this should have a filename. And even if it doesnt - this could be displayed/labeled better, right now SOURCE X is pretty enigmatic and confusing for users as they are not familiar with this scheme.

The second weird issue is that this doesnt get pretty printed.

**Comment by loganfsmyth** [comment]
This is caused by https://github.com/RecordReplay/devtools/blob/f1c5ed464a97dc8abb41abde95a71e36c532234f/src/devtools/client/debugger/src/actions/sources/newSources.js#L216 because the file being viewed _has_ a pretty version, but @Andarist was viewing the non-pretty version.

Seems like maybe that code needs to move somewhere else.

**Comment by hbenl** [comment]
This source should never have appeared in the search results since a pretty printed version of it is available. The linked PR fixes the detection of minified sources in global text searches.
