### ISSUE TITLE
Devtools do not load if recording ID is not a valid UUID

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#3005]
STR

1. Visit https://replay.io/view?id=foobar

AR: Devtools stay white, no error message.  There are apollo errors in the console.
ER: Devtools should show an error message indicating the ID is invalid.

This happens with any ID that isn't a valid UUID, and could be triggered pretty easily by a copy-paste error.

**Comment by bhackett1024** [comment]
Here is a recording, though it doesn't have source maps: https://replay.io/view?id=1013ff0b-8667-4f9e-9eef-91e74959b21a

**Comment by bhackett1024** [comment]
I thought this was going to be a fun way to add a mock test and fix a hole in the UI, but I'm going to give up on this for now.  I ran into two problems earlier today while working on this:

1. Fixing this isn't as simple as adding a try/catch somewhere.  When we make a query() call into Apollo and it gets back an error from the server (I think?), the promise returned by that query() call never resolves or rejects.  I started looking into Apollo's guts to see what is going on but it didn't seem a good use of time.  See the comment in this recording:

https://app.replay.io/?id=05ee1379-0a01-4eaa-9d6e-3611fc936fc7&point=7463926735121094394000040922185810&time=12706.013420089468&hasFrames=true

2. Generating a GraphQL error in the responses for a mock test (following the instructions in https://www.apollographql.com/docs/react/development-testing/testing/) causes Apollo to behave differently than in the live case, logging an "undefined" error in a different place.  If Apollo behaves differently in the live vs. mock cases we can't really have a reliable unit test for this behavior.  See this mock test recording, also the WIP PR I'll attach in a few minutes.

https://app.replay.io/?id=0e86c2bf-9343-41b3-8c7b-e969a50391a2&point=9735556610775103066237094865142014&time=6383&hasFrames=true

**Comment by hbenl** [comment]
> the promise returned by that query() call never resolves or rejects

Actually it does, you just didn't wait long enough: we configure the Apollo client to retry failed requests up to 5 times.
The documentation for `RetryLink` states that requests are only retried if they fail due to a network error but not if they fail due to a GraphQL error, but it turns out that it treats our GraphQL errors as network errors. I have found a workaround for that.

> Generating a GraphQL error in the responses for a mock test causes Apollo to behave differently than in the live case

That was because I had forgotten to add the `RetryLink` and `ErrorLink` components to the `MockedProvider`, so the error behaviour was different.

In the attached PR, I have added error handling to the GraphQL requests in the initialization code. Furthermore, the `recordingId` is now checked to be a valid UUID, so that we can show a less technical error message if it isn't. I have also added tests for both of these.
