### ISSUE TITLE
[Replay] Replace `recordreplay-gecko`

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#301]
`recordreplay-gecko` can be pretty confusing and certainly does not roll off the tongue.

We use it in a couple of places:

1. in the download url
2. in the browser name

In general, we should try to have consistent naming conventions that are based off of Replay. 

One proposal would be to use "Web Replay" and "Node Replay". We could also start with "Replay" and see if the context is sufficient.

I have not given the solutions too much thought. So I'm curious what others think

<img width="722" alt="Screen Shot 2020-08-08 at 6 08 08 PM" src="https://user-images.githubusercontent.com/254562/89722903-2d886980-d9a4-11ea-889f-856a793a7038.png">

**Comment by bhackett1024** [comment]
gecko replay or replay gecko or something like that would be fine.  We can't use "web replay" and I don't want to just use "replay" because we won't be able to distinguish it from our other products like node etc.  We also can't use anything that includes "firefox" because that's a mozilla trademark.

**Comment by jasonLaster** [comment]
Thanks. That's good context.

This could be a good topic to discuss on our next group call as well.

**Comment by jasonLaster** [comment]
closing as we're going with the simple Replay option for now
