### ISSUE TITLE
Replays are loading at the end rather than the beginning

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3045]
If you record a minute long Replay, you'd expect loading the Replay to take you to 0:00, but instead it's loading at 1:00.

(This is a regression that seems to come up a lot. Maybe it came back when we did the move to video?)

**Comment by hbenl** [comment]
> Maybe it came back when we did the move to video?

Good catch, that's exactly what happened.

@Jaril after seeing Jon's comment I knew exactly where to look, so I took over this issue - I hope you didn't spend any time on it yet. The issue was that `getGraphicsAtTime()` [now returns an `undefined` screenshot](https://github.com/RecordReplay/devtools/blob/0d292864d2f45843b23f5aaf2adfc61922769695/src/protocol/graphics.ts#L325-L329) when asked for a screenshot to be used for playback.
