### ISSUE TITLE
Show unloaded regions after we're done loading

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3070]
We're currently using the dotted line treatment when we're loading the replay which gives the impression that dotted lines are related to loading. I think we should only show them when we're done loading so it's clearer.

**Comment by bhackett1024** [comment]
I don't understand the change which is being proposed here.  I think we currently use the dotted lines for parts that are in the loading state but are not yet loaded.  I'd originally thought of the dotted line as showing only parts of the recording that are unloaded, so if the backend never unloads anything the timeline will always be solid.  Is that what you mean here?

**Comment by jasonLaster** [comment]
>  I'd originally thought of the dotted line as showing only parts of the recording that are unloaded, so if the backend never unloads anything the timeline will always be solid. Is that what you mean here?

That's correct.

**Comment by jonbell-lot23** [comment]
Just adding some UX colour for historical reasons:

The 80% case for people (if not 99%) is seeing a solid colour with only three variations, mirroring the YouTube model:
* Blue to show where the current playhead has gotten to
* Light gray to show content that hasn't buffered
* Slightly darker gray to show content that has buffered, and would play immediately if you jumped to it

<img width="227" alt="image" src="https://user-images.githubusercontent.com/9154902/126713808-681433b7-b672-4500-ba56-18e46bc5b408.png">

We want to make sure that "not buffered" and "unloaded" states are visually different because are different concepts. But more importantly, we want to hide complexity from the user until we absolutely need to show it. By combining unloaded and unbuffered states in our visual vocabulary, we can increase confusion.
