### ISSUE TITLE
UI for managing API keys tied to users and workspaces

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#3072]
**Description:**

The API currently has 
```
{
  viewer { 
    apiKeys { 
      id 
      createdAt 
      label 
      scopes 
    } 
  }
}
``` 
and 
```
{
  workspace(uuid:"") { 
    apiKeys { 
      id 
      createdAt 
      label 
      scopes 
    } 
  }
}
```
to list the API keys for a given user and workspace. Each also has `createUserAPIKey` and `createWorkspaceAPIKey` and `deleteXX` versions for deleting keys. Note also that the `createXX` mutations return a `{ key, keyValue }` pair, where `key` is the same object you'd get when querying, and `keyValue` is the actual API key string for users to use. 

The key string isn't queryable later so the UI will need need to explicitly have a way to present the newly-created key in a special way and should remind the user that this is their one chance to copy the key and save it somewhere.

The `label` is something the user would ideally enter themselves so they can look back later.

Finally, `scopes` is a list of internal permission names and is a bit opaque, so for now I think we'll want to expose it to the user as either read-only text description of what the key is allowed to do, or as two checkboxes e.g. ("Upload Recording", and "Upload Sourcemap"). Also "Upload Sourcemap" is only supported for workspace API keys, not user keys, so the UI for user keys will be slightly simpler.

**Comment by ryanjduffy** [comment]
@jaril , @jonbell-lot23 - I'm just starting on wiring this up today and tomorrow. I was going to start with creating a new section in settings for API keys. I didn't see anything in Figma for it but if either of you have another location in mind, please let me know! You've both put more thought into the taxonomy than I. :)

The general flow seems to be:

* Include a list of API keys which can be deleted. Deleting probably requires a confirmation dialog of some sort.
* Include a text field and button to create a new API key. The field captures the user-defined label.
* Clicking the button will send a request to the backend to create the API. When it returns, the API will be presented to the user with some copy to let them know they need to record it because it'll go away and not be retrievable after this time. I expect we'll want to hide the list at this point so the user can focus on recording their new API key.

Another question - should this feature (managing API keys) be behind a feature flag of some sort or should it be generally available now for users? cc: @loganfsmyth , @jasonLaster

**Comment by jonbell-lot23** [comment]
@ryanjduffy an API Keys section in settings sounds good to me. Thanks!

**Comment by ryanjduffy** [comment]
:+1: Here's the rough version as of just now :) Will continue to clean it up tomorrow.

![image](https://user-images.githubusercontent.com/788456/126592267-b0c9016c-226f-4123-a3d4-acbc8f311b3c.png)

**Comment by loganfsmyth** [comment]
The "upload source maps" part only applies to keys for a workspace, not a user, so the copy will have to vary depending on which type of key you are creating. On the workspace side, we'll want to allow users to select which of the 2 operations a given key can do. A single key can definitely do both if users want it to, but they could absolutely create separate keys for each case too.

**Comment by loganfsmyth** [comment]
@jonbell-lot23 If we're looking for inspiration, there's also https://github.com/settings/tokens

When you first create a key, the list shows the following:
<img width="784" alt="Screen Shot 2021-07-22 at 11 42 50 AM" src="https://user-images.githubusercontent.com/132260/126692168-2edafea2-8d6a-4683-baa6-798c7c9b8535.png">

and then once you refresh you get

<img width="735" alt="Screen Shot 2021-07-22 at 11 44 17 AM" src="https://user-images.githubusercontent.com/132260/126692282-5376b2d3-c804-4cbc-92c1-65058392edd7.png">

**Comment by bhackett1024** [comment]
One additional concern here is that it would be really nice to have a URL we can send people to for viewing the API key UI, just like that github URL.  When someone is trying to use replay-node or replay-playwright or whatever, they'll need to generate an API key first, and giving them a URL to visit instead of some complicated instructions would be clean.

**Comment by jasonLaster** [comment]
Agreed. Routing is currently a weakness, but is something we should consider improving as we do more with settings: billing, notifications, ....

We actually support navigating to settings if it is a query param, but that should be a proper top-level route. e.g. https://app.replay.io/?id=63ef565b-ecc4-42b7-9645-9c43a3b1c904&settings=1

**Comment by ryanjduffy** [comment]
Agreed. This was discussed in part on the frontend arch ticket. Expanding the routes to include the sub menus make sense to me.
