### ISSUE TITLE
[Debugger] Step over skips some locations

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#310]
Recording
https://replay.io/view?id=7cff91f0-f62e-473a-bf78-378c7205106c

STR:
1. go to https://replay.io/view?id=41f7dec2-54f1-4e19-b652-58b642f4d2a7
2. open timeline/index.js 
3. set a breakpoint on line 24 
4. rewind
5. step out
6. step over through `timeWarp`

**Comment by jasonLaster** [comment]
This recording shows it
https://replay.io/view?id=7cff91f0-f62e-473a-bf78-378c7205106c

I don't have comments, but if you play the last 1/3 you should see it

**Comment by jasonLaster** [comment]
Here's another recording where that happens
https://www.loom.com/share/1ef03d1e57ef4e5d8010baf60bfeec23

STR:

1. go to https://replay.io/view?id=a1922a50-df2a-4954-88e8-b4671ea131a8
2. add a bp in breadcrumbs.js:502
3. rewind and step over

**Comment by bhackett1024** [comment]
Hmm, I think this is happening due to the transformations which webpack made.  In the breadcrumbs case, this is the original code:

```
  handleEvent: function (event) {
    if (event.type == "click" && event.button == 0) {
      this.handleClick(event);
    } else if (event.type == "mouseover") {
      this.handleMouseOver(event);
    } else if (event.type == "mouseout") {
      this.handleMouseOut(event);
    } else if (event.type == "focus") {
      this.handleFocus(event);
    }
  },
```

And this is the generated code:

```
    handleEvent: function(e) {
      "click" == e.type && 0 == e.button ? this.handleClick(e) : "mouseover" == e.type ? this.handleMouseOver(e) : "mouseout" == e.type ? this.handleMouseOut(e) : "focus" == e.type && this.handleFocus(e)
    },
```

The places we go when stepping come from whichever step positions spidermonkey came up with when parsing the generated code.  When transformations like this are made, the resulting stepping behavior can be unintuitive.  This is a hard problem to fix in general and I don't think that chipping away at it would be a good use of time for me right now.  Stepping in optimized source mapped code is kind of odd in all browsers, but because we can step backwards and skip around the frame with the frame timeline, the experience with replay should be much less frustrating.

Stepping over at the beginning of handleEvent goes to the end of the function, and it's kind of unfortunate that this location gets source mapped to the start of the following function.  That does seem like a bug, but it will be a lot easier to investigate when we are able to record the backend.

**Comment by jasonLaster** [comment]
Sounds good. Happy to file bugs against babel/webpack as well
