### ISSUE TITLE
Breakpoint comments should never look disabled

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3112]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/9154902/126272651-8edd2973-78c5-48f4-9235-4f37853127ff.png">

When you create a breakpoint, the experience feels broken because the comment button isn't yet active. The functionality lights up if you click the tiny forward arrow, but that's too hidden.

I propose we always select the first hit unless there's a reason not to.

**Comment by jonbell-lot23** [comment]
Good discussion over here:
https://github.com/RecordReplay/devtools/issues/2615

**Re-stating my point:**
If I'm at 29 seconds, and I make a breakpoint that was evaluated at 2 seconds, then there are two options:

1. Keep me at 29 seconds, and show me an inert breakpoint (what we do today)
2. Jump me to 2 seconds, and now the breakpoint is actionable

If we pick option 1, then adding a comment is going to pin it to 29 seconds and not pair it with the moment in time I just clicked through to. That is a fragile relationship between action and reaction, and confusing. I don't recommend it.

I think option 2 is a good idea. Yes, we're jumping the person to where something evaluated. But the person did click it.

**Comment by jaril** [comment]
I'm not a fan of option 2. The intention behind adding a breakpoint could be:
- I'm trying to see how the hits for that line are distributed over time.
- I'm trying to see those hits logged in the console.
- I'm trying to add a comment.

My take is that optimizing for the add a comment use case is too opinionated a UI behavior. Yanking a person to a pause point when they're just adding breakpoints, essentially window shopping, would trip my usual workflow a lot. 

If the reason we want a breakpoint widget to be actionable (read: user can immediately leave a comment) in this way, I think there's better ways to do it. 

### Summary
We should have separate entry points for different code-related comments.

### Requirements
- Allow a user to leave a comment on a line of code (not associated with a hit)
- Allow a user to leave a comment on a line of code (associated with a hit)

### Use cases
We can delineate cases based on the stimulus required that triggers the user to want to leave a comment:
- **Things they could point out just by reading the code:** The comment-able information comes from simply looking at the line of code or the function. They could have pointed this out just by reading the code, not even in Replay e.g. this code has a syntax error, this variable is wrong, this was written incorrectly, etc. This is like a comment on a GitHub PR — pretty straightforward.
- **Things associated with the number of times the code ran:** The comment-able information is tied to how many times this code ran. Perhaps they expected it to be 0, but upon adding a breakpoint we see it ran four times. In that case, they want to leave a comment indicating that.
- **Things associated with a particular hit:** The user adds a breakpoint, sees a bunch of hits, and wants to point out something that's specific to one of those hits based on either 1) the breakpoint logs they're printing in the console, or 2) something they evaluated in the console while paused on one of those hits.

### Concept
Right now we use the `Add a comment` button in the breakpoint widget for all of these cases, and it _kinda_ works, but it's not the best tool for any of those particular use cases.

Instead, we should address each of those comment use cases specifically—what is the user trying to leave a comment on, and how do we get a +comment button as close to that thing as possible.
1) **Things they could point out just by reading the code:** These are plain code comments. The user didn't need to add a breakpoint to know that they want to leave a comment on this line. Therefore, there should be a +comment button beside the line. Clicking on it should leave a comment on that line.
2) **Things associated with the number of times the code ran:** These are after-adding-a-breakpoint comments. The user doesn't know they needed to leave a comment here until they added a breakpoint, and saw some aggregate hits information. Therefore, there should be a +comment button in the breakpoint widget.
3) **Things associated with a particular hit:** These are after seeing something in the console comments, whether that's a breakpoint log or something they evaluated. Therefore there should be a +comment specifically on the log message.

### In practice
- If a user wanted to leave a comment on a line of code, they don't have to first add a breakpoint to it. They'll be able to add a comment on the line immediately.
- If a user adds a breakpoint and wants to note `"hey this should be 5 instead of 3"`, they should be able to leave a comment on it immediately. This can be what the current add a comment button can be used for.
- If a user adds a breakpoint and sees something noteworthy in the console (e.g. `"this hit #5 for line X looks wrong"`), they should be able to add a comment on that console message immediately.

### Jaril comments
- Use case 2 is not compelling. I think in practice this can be folded into use case 1 or 3.
- Right now, we have certain expectations for what would happen when you click on a comment in the comments panel. It's not clear what the behavior should be when a user clicks on a comment for use case 1/3. For use case 1, I think it's uncontroversial to expect that the editor would open up and we would show them that line without jumping to it. 
- Use case 3 is less clear. If we want to be consistent with "Click a comment and we'll give you the context that the commenter was looking at that triggered them to leave that comment", then that would mean we would open the editor to that line of code and jump to that hit. If they commented on a hit's breakpoint log, then we would have to add that breakpoint for them. If they commented on a console evaluation with a hit, then we would have to evaluate that for them in the console and focus it for them.

**Comment by jonbell-lot23** [comment]
This is awesome, thank you!

Here are some items for the short term:

* I agree that option 2 is untenable
* I agree that we need a different way to think about entry points

And more long term:

* I agree we should make a new comment entry point

--

So the next question is: when should we do this? Let me noodle on this on the UX side and I'll get back when I have a proposal. Then we'll slot it into our priorities list.

**Comment by jonbell-lot23** [comment]
Hello! So we spent some time exploring other issues, which was time well spent. But let's get back to the original intention of this issue: the "add comment" button should never feel disabled.

@jaril , @jasonLaster and I just chatted about this today. We're going with the "floating comment" idea. So we just pick a point in time (based on where you are) and add a comment to that point in time when you click the button.
