### ISSUE TITLE
"All Replays"  should not show un-initialized replays

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3127]
**Description:**

We should not show un-initialized replays in the "All Replays" view. We could add a new filter for "Draft Replays" if folks want to have access to them later, but I also think it's fine to not show them since people explicitly discarded them.

**Comment by loganfsmyth** [comment]
Do we have any thoughts on setting an expiration on uninitialized recordings, or do we expect someone to be able to save the ID and come back to initialize the recording in 6 months?

At the moment a recording will be around forever even if it is uninitialized and I don't see anything wrong with that per-se, but seems worth clarifying, since it's certainly not clear to me as a user what to expect.

**Comment by bhackett1024** [comment]
We need a limit for how long we will keep recordings around, I just filed https://github.com/RecordReplay/backend/issues/2710 for this.  When that is done I don't see a reason to distinguish initialized vs. uninitialized replays, at least for now.
