### ISSUE TITLE
[Replaying] Improve React click event mapping

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#333]
STR:

1. go to https://replay.io/view?id=67c70aa2-3ce4-4de5-8408-44cceedb3a0c
2. enable mouse > click events
3. go to the console

<img width="1883" alt="Screen Shot 2020-08-13 at 5 28 23 PM" src="https://user-images.githubusercontent.com/254562/90199728-6cdefd80-dd8a-11ea-9780-bf115bcafedc.png">

**Comment by jasonLaster** [comment]
Here's another example

STR:
1. go to https://replay.io/view?id=23e6f91d-3d03-408c-b469-0c11090e4fe3
2. enable click events
3. note that most of the clicks are not mapped

**Comment by bhackett1024** [comment]
Hmm, from what I can tell things are behaving as expected in these recordings.  When we show React click events, we also show the regular browser events which those clicks are related to.  In the screenshot below, all these events are associated with the same click.

<img width="1149" alt="Screen Shot 2020-08-17 at 9 13 50 AM" src="https://user-images.githubusercontent.com/1062578/90435110-3ba44d00-e06a-11ea-96aa-c769e0ac7373.png">

The first one is a fullstory handler, it looks like it is keeping tracks of clicks on the page.  The second one is a dummy no-op handler which React installs on individual elements to workaround a safari bug IIRC.  The third one is the main React event handler which it installs on the window itself.  The fourth one is the mapped event call which we deciphered and added.

AFAICT all the clicks in both of these recordings have a mapped event handler associated with them, except for the last click in https://replay.io/view?id=67c70aa2-3ce4-4de5-8408-44cceedb3a0c.  In that case only the React main handler ran, which I think means that the element being targeted doesn't have a React handler associated with it, so we shouldn't be missing anything.

We could improve things here so that we don't show the main or no-op React handlers, but we'll need a way to identify them in order to filter them.  I don't know how we could do that reliably, and looking at either the URL or the structure of the handlers could lead to false positives or negatives.  It seems better to have a way to show React events specifically, and not show calls to regular handlers at all.  Maybe that could be part of the event listener pane, like have a separate category for React events?

**Comment by jasonLaster** [comment]
Thanks I wonder if we can do something good from a product perspective to group the handlers and show the most useful event first... some of this is easy because handers in node_modules are not that useful typically.

CC @jaril

**Comment by jaril** [comment]
If we can, I'd prefer to avoid grouping and introducing more hierarchy in the console. Adding comment grouping in the console would make the UI more complex. We already have collapse/expand for objects, and adding another hierarchy alongside that looks cluttered. 

We _could_ play with changing how we represent events altogether in the console and make grouping work. There should be a way to make it look and work well. But even then, I don't think it would do as good a job as just having an events timeline UI that takes care of the grouping outside of the console.

I like the idea of filtering instead. It seems like an easy fix to have some way to indicate whether or not the user is interested in displaying handlers in node_modules. We could put it in the event listener panel, or even the console. We can even enable it by default, since I agree that they're not useful typically.

It also gets extra points for cleaning up the console for demos, since I've noticed that about 30% of the error/warnings on a typical recording come from node_modules.

**Comment by jasonLaster** [comment]
Agreed!

Pehaps an easy next step would be to blackbox `node_modules` messages by default and add an option in the console settings dropdown to toggle it.

But yeah, especially now i'd like to only show the "good" stuff!

**Comment by jasonLaster** [comment]
We added hide 3rd party handlers, which will address this once we also support blackboxing 3rd party libraries while logging
