### ISSUE TITLE
Breakpoint widget loads funny

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3340]
This replay shows a couple of funny loading states for breakpoints

1. the log is missing 
2. the next/prev probably isn't needed
3. loading... could be centered
4. do we want to show the add comment button

https://app.replay.io/recording/e10e2e14-3f7e-4094-9ad7-58ac6a72dec4?point=141814607952702021779324188728756692&time=47864&hasFrames=false

**Comment by jonbell-lot23** [comment]
The key for a smooth loading state is for it to feel smooth between the two states. This is the same effect people go for when they use the skeleton loader pattern.

![image](https://user-images.githubusercontent.com/9154902/136136377-1d7b3670-8e0f-40e8-8bf7-75af1e473796.png)

In this case, the issues I see are:

1. The window needs to be taller, as tall as the fully loaded one will be
2. There should be a skeleton loader style big grey button in the top right, where the comment will be

* The arrows should stay where they are
* The loading text should stay in the bottom right, because it's echoing the treatment we use there on load
* Separately, we should think about what to show here if it's super slow to load. That'll be another ticket.

**Comment by jonbell-lot23** [comment]
* Progress bar woo
* Active comment button woo
* Is there a drawback to showing the expression? I can't envision how that would work in a loading state, but I'm into it

**Comment by jasonLaster** [comment]
Awesome, i dont think there are any drawbacks. only upside
