### ISSUE TITLE
Improve the error screen support flow

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3359]
**Description:**

We currently show this

> Unexpected session error :: The session has closed due to an error. Please refresh the page.

It would be nice to show users we care about them by doing one or many of these things

1. suggesting they email support
2. suggesting they discuss in discord
3. showing the intercom issue chatbot
4. sending a ping to intercom so that intercom can send an automated we're on it email.

<img width="1552" alt="Screen Shot 2021-08-27 at 9 36 58 AM" src="https://user-images.githubusercontent.com/254562/131136031-08a27678-bcd7-4325-a023-fcd057192627.png">

**Comment by jaril** [comment]
I get that we want users to feel like we're not just ignoring whatever caused the error in the first place. But is there anything actionable on our end if they did happen to do any of those 4 things?

I'm all for adding it, but these all look like extra work that the user would have to do. And even if they do the extra work, I'm not confident that we could provide a satisfactory/timely response. Even then, I don't imagine that talking to the user would reveal anything relevant to fixing the session error that we wouldn't already know about from logging (though correct me if I'm wrong). Maybe it would allow the user to vent, but that's about it.

If we did want to do anything about it, I'd differentiate it between:
1) **One-off errors that disappear after refreshing** — Suggesting extra work when they can sweep the error under the rug and do what they need to do sounds like an anti-pattern. I'd imagine we keep the current "Lol idk just refresh I guess" approach. Anything else would definitely just get in the way.
2) **Persistent errors** - There's no winning here since there's nothing we can do in the short term to fix the user's debugging session. Best we could do is mitigate the disappointment by setting expectations, i.e. "This is gonna keep happening so we're screwed for now. But trust us, we're tracking it now and we'll fix it as soon as possible. Sorry for the inconvenience".

1 is already handled, somewhat. 2 would require a copy change. In either case, we don't risk irking them because we're already getting in the way of their debugging and then asking them do something else for us on top of that.
