### ISSUE TITLE
Support trimming in the frontend

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3396]
[Written by Jon]

Here's the document explaining the design POV: 
https://www.notion.so/replayio/Trimming-UX-ca5e0332e9734cefac8bcf2327f381c8

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/9154902/137062190-870b5c3b-9008-480b-b170-b766d3d76d89.png">

**Comment by jonbell-lot23** [comment]
Totally agree. This is post-launch, agree?

**Comment by jasonLaster** [comment]
yep. We'll get back to it soon

**Comment by jaril** [comment]
Circling back to this now. We have this up for October 2021, and this will require tag-teaming it with @jonbell-lot23.

**Comment by jonbell-lot23** [comment]
I've set up a meeting in a few days to get my brain rolling on this task.

**Comment by jonbell-lot23** [comment]
Cc'ing @jaril and @jasonLaster. This has graduated to design-discussion.

Read the Notion doc to see the results we discussed in July, and the design I'm proposing we proceed with. Exciting!

**Comment by jasonLaster** [comment]
re-opening since this has not shipped. The work is currently being tracked in https://github.com/RecordReplay/devtools/issues/4128

Moving trimming to December because we should first focus on onboarding and engagement.

**Comment by jaril** [comment]
Merging the polish item here since it doesn't make sense to have a polish issue for something that hasn't shipped.

From #4128.
https://www.loom.com/share/3022c650f1784ef2972e65cbf78755aa

- [ ] mouse up is lost when not in the footer
- [ ] Update toggle button states
- [ ] dragging past the timeline should not affect the width
- [ ] should not feel sluggish
- [ ] initial size should be the current trim
- [ ] clicking the mask should cancel with a prompt
- [ ] scrolling up down should zoom in and out
- [ ] scrolling left/right or with shift should pan left and right
- [ ] escape should cancel

**Comment by jaril** [comment]
Trimming notes: https://www.notion.so/replayio/Trimming-UX-c8458eb5d8ba406ab803744af15b7cb6

**Comment by jaril** [comment]
Trimming notes:
- Remove x-axis translate on drag and drop
- allow navigation on the timeline while trimming
- return the clown nose
