### ISSUE TITLE
Limit debugging features for non-devs

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3408]
**Description:**

The teams account has three roles: users, devs, and admins. Users (free tier) should be able to collaborate with devs/admins, but have a couple of limitations on the debugging side that would encourage them to pay a monthly fee to be able to use.

The two most obvious features that are incredibly useful for debugging, but wouldnt be needed for general inspecting are:
1. editing breakpoint logs
2. evaluating expressions in the console

If on day one, we limited these features I think we'd be in a good spot

<img width="1532" alt="editing a log" src="https://user-images.githubusercontent.com/254562/131557958-f1f11384-0131-4b9c-96f8-0cb4cceea7b4.png">

<img width="1532" alt="evaluating an expression" src="https://user-images.githubusercontent.com/254562/131557951-d166b917-ab89-41d7-9723-98c0819d232d.png">

**Comment by jonbell-lot23** [comment]
Here's a set of explorations for the logpoints:

![image](https://user-images.githubusercontent.com/9154902/131618166-36fb1c38-ec8c-4f86-8630-9ad639fdb901.png)

Proposal 1 and 2 assumes you have to hover over the text field before showing that it's a paid feature. But I like proposal 3 because the UI doesn't need to reload or jump around. By always showing a lock, it's clear right away that something is not possible. Clicking on the lock would load a billing modal.

**Comment by jonbell-lot23** [comment]
Here's a proposal for evals:

![image](https://user-images.githubusercontent.com/9154902/131618851-138f3559-901a-45d6-b822-71bd591c3249.png)

The design re-uses the padlock icon we use elsewhere and uses the same font face/size used in the console. The text may be bold as shown here, or there may be a different background color.

**Comment by jasonLaster** [comment]
@jonbell-lot23 Good call

1. I like option #3 that shows paid badge
2. I like making the log more obviously editable. Two options here are two show the pencil on the right or the text cursor.

tried my hand at a Jon style design proposal for editing (https://www.loom.com/share/b3e92955a5614dc2991c346341a95fb8). Kudos to Jon for keeping his to 1-2 mins :)


### editing a log expression
<img width="2935" alt="edit log" src="https://user-images.githubusercontent.com/254562/131680710-16a66ba4-15a3-4c2d-a4a5-24275cd7c463.png">

**Comment by jasonLaster** [comment]
Agreed! Thanks

**Comment by ryanjduffy** [comment]
Thinking through permissions:

* If a user creates a recording and it's in their library, they have full access to all features for that recording.
* If a recording is shared with a user, they have full access.
* If a user is a "Developer" or "Admin" in a team, they have full access to any recordings saved to that team.
* If a user is a "User" in a team, they have limited access to those recordings (per this ticket)

But ... If a user is a "User" but a team recording was shared with them explicitly, which role do they take: collaborator or "user"?

**Comment by ryanjduffy** [comment]
Also, should the "User" role be unable to add new recordings to the team? I'd expect so but want to confirm.

**Comment by bhackett1024** [comment]
> But ... If a user is a "User" but a team recording was shared with them explicitly, which role do they take: collaborator or "user"?

I feel in this case that because the recording is associated with the team, and because the user has limited access to the team's recordings, that they should not have full access to the recording in this case.

If another team member made a private replay and added the user as a collaborator without associating it with the team, the user would have full access to it, however.  Essentially, the recording being part of the team preempts other factors that control access.

Another case is that if the replay is associated with a team and is shared with someone outside the team, that person would have full access to debug it.

Would it be reasonable to not allow adding collaborators to recordings that are part of a team?  Then we would have three different cases to consider:

* public replays: accessible to everyone, can't have collaborators
* team replays: accessible to people on team, can't have collaborators
* private replays: accessible to original creator and any collaborators that were added explicitly

**Comment by bhackett1024** [comment]
> Also, should the "User" role be unable to add new recordings to the team? I'd expect so but want to confirm.

I think people with the "User" role need to be able to add new recordings the team, since that's one of the main values they get from being on the team --- they can create new recordings, add those to the team and comment on them, then attach those recordings to githu/jira/etc. tickets so that developers can look into them.

**Comment by ryanjduffy** [comment]
> > Also, should the "User" role be unable to add new recordings to the team? I'd expect so but want to confirm.
> 
> I think people with the "User" role need to be able to add new recordings the team, since that's one of the main values they get from being on the team --- they can create new recordings, add those to the team and comment on them, then attach those recordings to githu/jira/etc. tickets so that developers can look into them.

Yup. That makes sense. I wasn't thinking of the QA/PM side when I first mentioned it. Agree that "User" should be able to add recordings.

**Comment by ryanjduffy** [comment]
> If another team member made a private replay and added the user as a collaborator without associating it with the team, the user would have full access to it, however. Essentially, the recording being part of the team preempts other factors that control access.

:+1:

> Would it be reasonable to not allow adding collaborators to recordings that are part of a team? Then we would have three different cases to consider:
> 
> * public replays: accessible to everyone, can't have collaborators
> * team replays: accessible to people on team, can't have collaborators
> * private replays: accessible to original creator and any collaborators that were added explicitly

I think it would be reasonable to (gently) message that you can't add your team members as collaborators (in some post-launch work) but I don't think we should prevent adding collaborators to teams in general since they might want to share across teams or to users outside their org.
