### ISSUE TITLE
Re-add print statement conditions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3638]
**Description:**

We removed the condition field for print statements a couple of weeks ago in order to improve the print statement ux. 

Now that print statements are improved we would like to bring back the functionality, but in a not as prominent way as before.

**Comment by jasonLaster** [comment]
Okay!

Pretty excited about these designs, they're still wireframes, but I think they achieve the primary goals

1. don't mess with what's working. Print statements are great now, they should not be worse
2. let users add a condition and easily see what the condition is and have the space to edit it
3. show the condition in view mode along side the print statement with minimal chrome (code-like)

### Print Statements

We preserve the 99% case, nothing changes, just one new button



<img width="481" alt="Frame 7" src="https://user-images.githubusercontent.com/254562/134432234-f5a4c9d1-577e-46fb-b321-e759cede686e.png">


### Conditions

Adding a condition, is simple. It's not as pretty, but it is clear what is expected. This is similar to before, but atleast the user has opted into this more advanced mode

<img width="481" alt="Frame 5 (1)" src="https://user-images.githubusercontent.com/254562/134432326-687158be-87fa-4b6b-924b-89caf5fea72d.png">

### Multiple Conditions

This is a fun feature, definitely candy, but it is cool because it shows off what is possible with replay. We will need to do something on the backend to pull it off, but i think it is doable.

What I think is *great* about this design is it leans on learnable and does not add any extra chrome. Users would add a comma in the same way they add multiple log params. Here we show the highlighted hits on hover, but we could also do some other interactions similar to our old idea of primary / secondary colors from the winter... again this is candy


<img width="481" alt="Frame 6 (1)" src="https://user-images.githubusercontent.com/254562/134432345-b1c3a969-3e5b-4eee-98e2-1f7e2c8dc050.png">

**Comment by jonbell-lot23** [comment]
**Concerns with this model**

1. Top one doesn't mention log, bottom one does. Not the end of the world, but different.
2. Grey boxes as input look disabled. A border is a much better treatment, but then we're back where we started with two boxes boxes in a box. The visual design is going to affect the flow/usability more than it seems like in wires.
3. Left-aligning the input boxes and text-aligning "if" and "log" to the left makes an awkward visual
4. Screens #2 and #3 look like they're from different planets. They're too different from each other, and even how real code looks

**Feedback about the feature in earlier iterations** 
Kannan: "it might be good to be consistent and structure the print line as print("...", ...) in the same style."

Andarist: "hm, i think I like the explicitness - especially that we are going closer to code-like here and comma is an operator so it has a special meaning
and with explicit call i have no doubts for what it does - it will log both arguments
i feel like u probably can just shorten that to log()" and also talked about liking the "if" on the top, which you've done

**Jon's proposal**
Here's the model when you stick with the concept of the top region being editable, our big breakthrough a week or two ago. You stick with code conventions, which immediately demonstrate to developers what they're dealing with and make things like multiple conditions as simple as a &&

<img width="742" alt="image" src="https://user-images.githubusercontent.com/9154902/134435052-cd3d764d-79ca-4b99-85f6-3eae44a0f059.png">


It's the same design but without boxes or changing the layout between modes. It's as close to modeless as possible.

**Comment by jasonLaster** [comment]
1. inconsistencies: there will be some because it is important to cater to the 99%
2. visual treatments: good call on right aligning labels, inputs backgrounds, etc... not trying to be visually precise here
3. code/modeless: indentation and parens feels uncanny valley to me. there are a lot of structured editors, theyre tough to get right
4. 
<img width="481" alt="Frame 8" src="https://user-images.githubusercontent.com/254562/134435650-e0adb90b-3255-4534-b530-9d47b0b30148.png">

**Comment by jonbell-lot23** [comment]
Hello! So we've been talking about syncing on this tomorrow, so this is just me sifting through some topics in preparation for that.

**We're almost there**
The broad brush strokes are there. We think the filter button is best, we believe in the feature, and now it's just a matter of working through the last items to land a single design. This is the joy of design work! I see three topics:

1. Saved state: one line or two?
2. Borders on fields or no?

**Question 1: save state - one line or two?**
<img width="991" alt="image" src="https://user-images.githubusercontent.com/9154902/134442537-4464ede3-c6ab-4f22-9e2d-14b6c27f13e2.png">

I struggle with the first one for two reasons: it doesn't look like real code, and when I click in, the entire view is going to shift on me. It's nice to take less vertical space, but I don't like the jump.

The second one is interesting because at least it's real code. (Correct me if I'm wrong, maybe the first one is valid or maybe the second one isn't) But, again, clicking into it makes the whole UI shift. I don't think that's a good tradeoff.

The third one does take more vertical space, but gosh it's elegant. You'd put your cursor over a line, click, edit, hit enter, and it always looks the same. I would love that.

Which brings us to...

**Question 2: borders on fields or no?**
Jason, you drew this up, which I think can work. Maybe we even put a more obvious border in on both, not just the one being edited.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/9154902/134442898-e8bf1c60-fe07-4e28-8814-e68da03bcc8f.png">


**Jazz hands**
So if we went with my favourites, it'd be two lines with borders, and it could work like this. I've also added the one line version at the bottom, with the addition of curly braces to make it read better. (But if the non-curly brace version is valid code, then that could work too)

<img width="759" alt="image" src="https://user-images.githubusercontent.com/9154902/134443737-563dea31-e101-4d0a-8c2f-ffc6dd7d0823.png">

**Comment by jasonLaster** [comment]
Couple of quick thoughts on small things:

1. in JS, it's totally valid to write `if (foo) log(2)` in fact nobody would write `if (foo) { log(2) }` it's understood that you drop the curlies
2. in many languages, the parens are not used for keywords like `if`, so `if foo  log 2` while it might seem weird without styling is not crazy

**Comment by jonbell-lot23** [comment]
1. Ah ha! I am wrong and stupid.
2. See number 1
3. Roger that sir

**Comment by jonbell-lot23** [comment]
Jason and I had a great chat and here's where we ended up. Pretty much the same, but we're tucking the filter into the bottom-right corner, replacing the badge.

![image](https://user-images.githubusercontent.com/9154902/134602363-c27d23c3-c832-4f9d-ad7f-c0eb0a7040c5.png)
