### ISSUE TITLE
Error loading chunk

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3640]
**Description:**

Just got this error and there were no vercel deploys at the time!

`Error: "Loading chunk 82 failed after 2 retries. (82.c8f206708e7c1ad316fd.js)"`

https://app.replay.io/recording/d4b9dada-9c81-4626-9abb-b5bdaba2f4f8?point=1298074214663062594482923620007975&time=914&hasFrames=false

here's what i see when i try to view the asset
<img width="1052" alt="Screen Shot 2021-09-16 at 9 10 29 PM" src="https://user-images.githubusercontent.com/254562/133723094-c6b12758-d67b-486b-9e5d-ef9492bd57f0.png">

**Comment by hbenl** [comment]
The file that the browser tried to get is from [this deployment](https://vercel.com/recordreplay/devtools/FDQQucXDv7NKT8whf7yLQtd6fGRB) (the Build Logs contain the names of the generated files). There were several production deployments between that one and the time that this recording was made. So the browser must have used a cached `index.html`, which is interesting because we serve that file with a `cache-control: public, max-age=0, must-revalidate` header, so AFAIK the browser should not use that file without asking the server first if it is still current.

**Comment by jasonLaster** [comment]
Yep - i can see that in the source explorer

<img width="969" alt="Screen Shot 2021-09-17 at 7 39 16 AM" src="https://user-images.githubusercontent.com/254562/133801469-be51acee-5e79-4022-8fa0-f4b9570e8897.png">
