### ISSUE TITLE
Library should show a Free Trial badge 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3651]
**Description:**

Users should see a badge with Free Trial and the # of days in the library until they add a credit card.

**Comment by jonbell-lot23** [comment]
![image](https://user-images.githubusercontent.com/9154902/134083663-0281c266-16ab-41a6-9311-73185aba9c32.png)

![image](https://user-images.githubusercontent.com/9154902/134083669-7fd8d764-7492-4a01-b7f1-1e5c34fad1b2.png)

**Comment by jasonLaster** [comment]
Thanks Jon. Seeing this version, I'm wondering if we can get away with a significantly lighter touch version

1. a badge color that is low contrast with the sidebar
2. no expiration date. This might be controversial, but I am curious how many people will sign up without the nudge.

High level, we might want to go with something like this in a couple of weeks, but in the early days when folks are just figuring it out, i am curious if lighter could do the job.

**Comment by jonbell-lot23** [comment]
I'm cool with lighter. So are we talking about no second line at all? If so, here's a less bold badge with no text:
![image](https://user-images.githubusercontent.com/9154902/134111817-2b44fd9c-1c7e-4046-b321-3bfcacb99810.png)

But then thinking through the gear, here's how the gear could work when the team is selected:
![image](https://user-images.githubusercontent.com/9154902/134111837-7cb8d5c8-089a-4385-9454-e976b5939a05.png)

And then of course we could do the lightest possible touch and clean up our gear collisions but just making it text only:
![image](https://user-images.githubusercontent.com/9154902/134111884-08e7f9d6-9381-4063-aa9c-557770e6270c.png)

And here's how the text could look with a splash of colour:
![image](https://user-images.githubusercontent.com/9154902/134111929-d9a81853-8d14-4428-aef1-7d18050eb78b.png)

**Comment by jasonLaster** [comment]
Thanks for going lightest touch to show the extremes. I think i fall in the middle...

thoughts?

<img width="1580" alt="trial" src="https://user-images.githubusercontent.com/254562/134253858-d303cc5f-3697-46b9-b271-9b4b62fc464c.png">

**Comment by jonbell-lot23** [comment]
* Sounds like we agree with not having the "x days remaining" line
* We know we're doing a broader exploration around what happens when you run out of time, so we can punt on some of the details
* I'd be fine with the label on the right, but the gear does make it clumsy. I'd rather have the Trial text as part of the team name, because then we're handling two elements (Name + cog) rather than three (Name + trial label + cog)
* So let's ship this for now but address the broader issues around trial expiration in another ticket:

![image](https://user-images.githubusercontent.com/9154902/134254333-30362268-1abf-4274-a608-1953edab9868.png)

**Comment by jaril** [comment]
Got #3715 to get the basic parts of this in. 

@jonbell-lot23 How do you want to handle the follow-up to this?

**Comment by jonbell-lot23** [comment]
Here's the ticket for the next iteration, and we'll address next week:
https://github.com/RecordReplay/devtools/issues/3699
