### ISSUE TITLE
Tabs should remember last state

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3655]
**Problem**
When you're in DevTools and the page reloads, you're brought back to Viewer, causing you to navigate back to where you were. This happens after a timeout, a socket error, or anything else that reloads the page.

**Background**
This is contrary to core UX best practices. Hitting reload on a GitHub task does not take you to the top of the repo. Going to a Replay URL doesn't take you to the Library. Launching Xcode, VS Code, Nova, BBEdit, any Adobe Creative Suite app, Slack, Discord, Chrome, or any other app I can think of always maintains window state. You have to go out of your way to find counter-examples. Some apps shift views on you, but they are poorly designed.

**Fix**  
There are three options:

1. Always take you to Viewer (what we do today)
2. Always take you to DevTools
3. Default to Viewer, but remember your last tab. If you're in DevTools, you should be returned there the next time you load or reload the page.

We should do number 3 because it's UX best practice.

**Comment by ryanjduffy** [comment]
This would be improved by adding url routes to each view so that the view state is included in the URL and a refresh keeps the user on the same view.

**Comment by jonbell-lot23** [comment]
Agree, but one nuance is with shared links. If I post something to Stack Overflow, everyone should start in the Viewer tab since they're new.

So the URLs are a good start, but we do need a bit of logic:

If new: Viewer
If not new: last tab you were looking at, either Viewer or DevTools

**Comment by ryanjduffy** [comment]
~I think we agree but I wanted to clarify one point.~ (I thought we agreed until I got to the end ... maybe we don't :) )

My assumption is that the sharing link (as generated by our sharing modal) will be to viewer (either explicitly because the URL includes `/viewer` or implicitly because the url doesn't specify). Agree that landing in DevTools without any context is probably too much.

If you're in the app and you click to devtools, the URL will change to `/devtools` (or whatever we decide). As a result, any refresh/reload/reopen a closed tab will land you on the devtools view. Importantly, all of this is driven by the URL and not by the DB/localStorage/cookie remembering if you've seen this replay before.

My inclination would be to only implement the URL part so that refreshes retain the view and stick with always landing on the viewer when opening the replay fresh from the library or via the sharing modal. Then, if we wanted to add some browser-side view state cache, it can operate on the root (`/` vs `/viewer` or `/devtools`) and rely on setting the URL to the desired view.

**Comment by jasonLaster** [comment]
* local state for default
* url will include the modality
* we can use a ref param in the future to measure
* this will be consistent with how the back button will work in the future

**Comment by jaril** [comment]
Final implementation after talking it out with Jon — we're going to do replay specific memory.

User views a replay for the first time => show the viewer
User views a replay for the nth time => show the devtools/viewer from n-1
Non-logged-in user views a replay => show the viewer

Follow-up:
Add a checkbox (ala Youtube) to force yank the person opening the link to DevTools/Viewer.
