### ISSUE TITLE
Share button improvements

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3679]
- [x] #3730
- [x] #3731
- [ ] As a follow-on task, we can explore the "let collaborators add collaborators" flow

Here's a Loom with my design POV: https://www.loom.com/share/631f287359534f0c93b1b8061e2fcfa4

**Comment by jasonLaster** [comment]
Thanks @jonbell-lot23 

I would vote for designing the experience we want here because it won't take eng any more time to do and will avoid another pass next week or whenever...

With that in mind here are some opinions 
* Collaborators should be able to add other collaborators
* Collaborators should not be able to change workspaces nor should they be able to make replays public
* We should show the Replay's author, create date, and current team 
* I quite like the public/private toggle in motif, could we use that in the edit section?

**Comment by jonbell-lot23** [comment]
I see three different issues here, and they each have a different priority:

1. It's a bug that some people can't see a share link (High priority)
2. It would be nice to add collaborators (Medium priority)
3. Maybe we can redesign the screen while we're at it (Low priority)

Happy to hold off on all three to make a unified task, but that'll put it lower in my queue and will take longer to get to.

**Comment by jonbell-lot23** [comment]
This has jumped over here: https://github.com/RecordReplay/devtools/issues/3739
