### ISSUE TITLE
Billing page polish

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3681]
We can make this page look more consistent with other screens:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/9154902/134084607-beba7738-868a-4f18-b767-6c1f3cea413e.png">

**Comment by jonbell-lot23** [comment]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/9154902/134457753-bcfc5d3f-9e0e-4a03-b5fb-636d5afeec5d.png">

1. We don't need a danger zone since no one needs to cancel anything. It's just clutter at this stage.
2. We should special-case the payment method and make it the primary call to action. It shouldn't be a small button (the way it might be if someone already submitted a credit card), it should be THE MAIN EVENT
3. I think the top part just needs to say "This temp plan is running out soon, learn more"

Thoughts? This is less of a visual update and more of a copy thing. I'd like to chat before I fuss with visuals.

**Comment by jasonLaster** [comment]
Thanks @jonbell-lot23.

1. Yes. love getting rid of the danger zone when we dont need it
2. lets discuss the different use cases a bit more

Use Cases
1. beta users should see that they're in the beta plan. We should briefly describe what the beta plan includes and give them the option to upgrade to the paid plan so that they can continue getting new major features as they are released.  
2. team plans should see a summary of the plan and what it includes as well as the number of paid developer seats. They should see that they are currently in a free trial period with N days remaining. We should describe what will happen once the trial expires i.e. cannot see new replays. 

We should only show the cancel subscription to folks who have entered their billing info

**Comment by jonbell-lot23** [comment]
Thanks, @jasonLaster ! Stay tuend

**Comment by jonbell-lot23** [comment]
@jasonLaster and I spoke last week. Here's a low fidelity sketch to push things forward a bit:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/9154902/134842533-274bfa34-5e15-4279-9eb0-5d2a0f141fcf.png">

1. Beta plan just explains you're on a beta plan with a banner. As of today, there's nothing different between beta and paid, so there's nothing in particular to discuss or use as a carrot to upgrade.

2. Trial is easy -- we use a banner at the top to explain when it's expiring, and provide a call to action.

3. Standard has no banner, and nothing particularly interesting.

--

We could put more words on this page by trying to explain what they'd get if they upgraded, but I don't think it really works here. I think it'd be better to have a "learn what's in each plan" link that has some sort of visual feature table. We could use it for anyone looking to upgrade, whether beta testers or trial users.

And then of course another side of the story is what we show when a Replay isn't available due to a lapsed subscription:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/9154902/134843009-32843344-21b0-484b-89e9-7e3bd25769ae.png">

I'd argue that this call to action would go to a page that combines "add credit card" with a "what each plan entails" page as a combined visual.

I'm staying low fidelity in order to align us before we get into ironing out the final visuals. Thoughts?

**Comment by ryanjduffy** [comment]
I'd like to add this some copy to inform the user about the subscription to fulfill the compliance requirements.

https://support.stripe.com/questions/2020-visa-trial-subscription-requirement-changes-guide#:~:text=1.%20Obtain%20express%20consent

**Comment by jonbell-lot23** [comment]
@ryanjduffy and I just talked about the compliance requirements which led to these three screens:

Telling someone what they're about to get into:
![image](https://user-images.githubusercontent.com/9154902/135361465-0d0d1b95-628d-4ea5-a7c8-56b701d1f3d6.png)

The actual credit card gathering step:
![image](https://user-images.githubusercontent.com/9154902/135361488-1e3deb3e-b270-4a9f-b64a-5c72fb09f2e8.png)

Confirmation:
![image](https://user-images.githubusercontent.com/9154902/135361502-838207e7-45e0-4394-8111-ee48381d6272.png)

**Comment by jonbell-lot23** [comment]
Here are the screens from 3 days ago done at higher resolution to get a feel for how they're coming together.

Beta user being gifted a team plan:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/9154902/135368190-d7f5934f-90f0-4db9-8614-f5e3eb673bf6.png">

Trial expiring soon:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/9154902/135368219-87975da8-5222-4da9-ad0e-8ab5916f5c1d.png">

Standard team plan:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/9154902/135368239-f04318e4-0c6a-407e-9117-a929b1b228d0.png">

Ryan and I discussed legal things we need to talk about in our flow, and these three screens were the result.

1/3: telling the person what's about to happen:
<img width="890" alt="image" src="https://user-images.githubusercontent.com/9154902/135368278-89ab2b6c-2ac1-4f17-a04b-06a431bbeee4.png">

2/3: Standard credit card flow
<img width="891" alt="image" src="https://user-images.githubusercontent.com/9154902/135368299-7fea6ef8-c004-4316-aafe-035878adfb44.png">

3/3 Confirmation screen:
<img width="890" alt="image" src="https://user-images.githubusercontent.com/9154902/135368319-e2f2acf0-e463-4d51-a1b1-d0246d0fda97.png">


Next steps:
This is basically a coloured-in wireframe. If we're feeling pretty good about the general idea, then I can make sure the personality is brought in too. For example, adding an illustration on this final page, having confetti burst out from the top of the screen, etc. This is a big moment! It's worth bringing some personality/whimsy.

Curious to hear everyone's thoughts!

**Comment by jasonLaster** [comment]
Love it!

**Comment by ryanjduffy** [comment]
Rough cut of the design in code. There are a couple gaps that need filled like populating the date the subscription will renew which is missing from the db at the moment but this is otherwise wired up.

![image](https://user-images.githubusercontent.com/788456/135383962-db081736-38c9-4b9d-b31a-6660baa74824.png)

![image](https://user-images.githubusercontent.com/788456/135384003-dfa0e7bc-216a-49cc-a216-cee5b353e7fe.png)

![image](https://user-images.githubusercontent.com/788456/135384027-d843bf41-10ac-48bd-a653-a5684f07b5d8.png)

![image](https://user-images.githubusercontent.com/788456/135384071-737bfd4d-dae2-4dfd-b530-5f388d3193c1.png)

**Comment by jasonLaster** [comment]
Looks good. Here's what I propose. 

1. let's flag the expiration off. I'd like to look at the usage data and see if 30 days makes sense anyways
2. lets feature flag the blue billing box lol we can add something joyful soon

**Comment by ryanjduffy** [comment]
I've added the feature flag for showing anything around trial expiration and removed the blue box altogether. We can insert joy when we find it. :)
