### ISSUE TITLE
Selecting one of many comment at a point in time

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3720]
**Description:**
It should be possible to select one comment when there are multiple comments at the same point in time.

Currently the selected marker changes purple, but we should make the comment more prominent as well, perhaps not use the blue border for the other ones...

https://app.replay.io/recording/b1f85807-2074-4336-9ab3-4faedd72e48e?point=13629779253654429810354579876872533&time=6907&hasFrames=true

<img width="1616" alt="Screen Shot 2021-09-23 at 5 25 21 PM" src="https://user-images.githubusercontent.com/254562/134600624-4eacfaf6-985f-470c-bdd7-607aaf892125.png">

**Comment by dave-hawkins** [comment]
I would probably:

1. Remove the blue borders on the comment cards
2.Add a focus outline to active waypoints / comments
https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=6736%3A40852
3. Add an action where clicking on a waypoint scrolls you to the specific comment thread. 

And I think maybe in future look at placing the comment side by side with the waypoint rather than in the left panel. 
UX of this feels not quite right currently, perhaps because i'm used to plotting figma comments so often.
