### ISSUE TITLE
Editing breakpoints shouldn't jump the timeline

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3732]
Right now the toggle between view mode and edit mode causes the timeline to jump ->
<img width="507" alt="image" src="https://user-images.githubusercontent.com/9154902/134765762-1fda8304-4db0-4627-9501-37cefcdb13e8.png">

<img width="507" alt="image" src="https://user-images.githubusercontent.com/9154902/134765883-2f750461-6b59-4189-89e2-6cdd5abdc95c.png">

This seems like a small thing, but it's really important to get right. The timeline needs to stay pixel perfect between each mode or else the illusion breaks and it feels clunky.

**Comment by jasonLaster** [comment]
Thanks. Love this attention to detail.

re labels: I removed *bug* because we're using it for functionality breaking as opposed to ui-polish which is visual glitches... it's kinda abusing the term bug but it is helpful. Also added `feature-debugger` which is useful for filtering and historical accounting, like where did we spend our time

**Comment by jonbell-lot23** [comment]
Let's propose that idea as a separate discussion.

**Comment by jasonLaster** [comment]
https://github.com/RecordReplay/devtools/discussions/3758
