### ISSUE TITLE
Loom Style Sharing

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3739]
Loom does some really great things to keep sharing simple and less stressful

<img width="5131" alt="Frame 1" src="https://user-images.githubusercontent.com/254562/134781737-862b3ed7-91d1-44fe-802a-648928a92f61.png">

I think we should learn from a lot of the human psychology they have here

<img width="2163" alt="Frame 17" src="https://user-images.githubusercontent.com/254562/134781745-21c67775-a8fc-4208-acc2-9be6c736bdb6.png">

1. The copy link is a no brainer, nobody needs to see the whole thing
2. The Add People form is simple and anyone should be able to add a collaborator
3. The privacy settings description is easy to understand. Here only the author and team member should be able to edit. Also tucking it away at the bottom is really nice.

**Comment by jonbell-lot23** [comment]
I think this design is awesome. I made a few slight tweaks:

1. Narrowed the width
2. I propose we make it a dropdown/popover style rather than a giant modal. This will help us align the general pattern with our upload screen, which is also narrow.
3. I added a link icon to the tri-select dropdown menu


<img width="992" alt="image" src="https://user-images.githubusercontent.com/9154902/134846055-ee54463a-2ce0-4aee-87c9-0f908f2df36e.png">

How are we feeling about this approach?

**Comment by jonbell-lot23** [comment]
Ok! I think we have consensus on this. Assigning to Jaril.

**Comment by jaril** [comment]
- anybody from the workspace should be able to change the replay's privacy settings via dropdown

**Comment by jasonLaster** [comment]
1. If the replay belongs to a team, Only show the public/private option
2. If the replay does not belong to a team, give them the ability to add it to one of their teams
