### ISSUE TITLE
Scope variables displayed as `undefined`

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#3760]
**Description:**

https://app.replay.io/recording/6f7e1dfe-3b17-4f4e-9089-b573553822a6

Notice how I hover over stuff and a tooltip with `undefined` in it gets displayed quite often. I think this might be some kind of a source mapping issue as there is a high chance that those `undefined` variables are actually property getters (IIRC) created by webpack, coming from lines like this:
```js
  return /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_0__.createElement(_chakra_ui_system__WEBPACK_IMPORTED_MODULE_1__.chakra.button, _extends({}, buttonProps, {
    className: (0,_chakra_ui_utils__WEBPACK_IMPORTED_MODULE_3__.cx)("chakra-accordion__button", props.className),
    __css: buttonStyles
  }));

```

**Steps to Reproduce:**

I'm not sure

**Expected Result:**

I should see the correct resolved values.

**Comment by jasonLaster** [comment]
cc @hbenl curious what you think 

@Andarist looks like the `_pause` pool is null for the expressions that returned undefined which is super weird

**Comment by hbenl** [comment]
Some `undefined` values are actually correct: `buttonStyles` is undefined because we're paused at the line that sets the value and `props` doesn't contain `className`.

But `React`, `chakra` and `useStyles` shouldn't be `undefined`. This is a transpilation/sourcemap issue: these variables are set by `import` statements, but `webpack` transpiles imports so that they don't show up as variables (you will also not find these anywhere in the scopes). When you switch to the generated source, you can see that for example a `chakra` reference is transpiled to `_chakra_ui_system__WEBPACK_IMPORTED_MODULE_1__.chakra`. In other words, the `chakra` variable doesn't exist in the generated source, instead there is a `chakra` property on the `_chakra_ui_system__WEBPACK_IMPORTED_MODULE_1__` object (which doesn't exist in the original source).

@loganfsmyth do you think there is anything we can do to improve this situation?

**Comment by jasonLaster** [comment]
thanks @hbenl. Replay should be able to map these on original expressions to their generated counterparts. It might be helpful if the Replay backend returned the generated expression along with the result either for debugging purposes or in some scenarios to show the user if they're curious.

**Comment by jcmorrow** [comment]
For now, going to close this in favor of the Issue page for Source Maps (which tracks work that is valid, but not currently on the immediate roadmap): https://www.notion.so/replayio/Source-Map-Issues-e761f8ac000d4bcd94adb9a8c2f74d38
