### ISSUE TITLE
Network Monitor UX

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3844]
**What we're building and why**
Network monitor is our most commonly requested feature, and as a team we intuitively understand why it's so important for debugging.

**Goals and non-goals**
* Goal: a simple MVP network monitor we can build on and learn from
* Non-goal: tons of features

**Feature set**
1. Two columns, status code and URL
2. Ability to mouse-over each item and have it light up in the timeline
3. Fuchsia horizontal line that we use to show current playback location

**What about features x and y?**
Filters and details are two obvious follow-on features. I recommend starting with a true MVP, shipping the bare minimum, then we can add features on to the end of our October tasks if we have time.

Figma link: https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=7368%3A30061

Design guidance:
1. The goal is to use the exact same table style that we use throughout the product, notably our Console. Then we just add the special return code column and we’ve got a pretty good MVP.
2. For loading states I recommend a determinate progress bar across the top of the pane, as used elsewhere.

![image](https://user-images.githubusercontent.com/9154902/137045370-ab70d021-328e-4782-83f6-6645dfea137f.png)

**Comment by jonbell-lot23** [comment]
This has graduated to "design discussion." I have described the design POV and I'm ready to work with @jaril on handoff.

Note: I am consciously not designing features outside the scope of MVP like filtering and showing resource details on hover. We'll get to those, but those are post-MVP features so it's lower on my priority stack.

**Comment by jonbell-lot23** [comment]
Moved over to email + chat so we can march forward with good alignment.

**Comment by kannanvijayan** [comment]
Thoughts on Jason's comment as well as the work in the Parity Network Monitor document.  Just suggestions that came to mind since the document pressed on the availability of column space as an issue:

> Type. The resource type.

The type as shown in the mockup has unnecessarily long names like "document".  That can just be "doc".  In fact, these can be fixed-width mimetype emblems similar to how HTTP status is displayed in the mockup.
 
>     * **Initiator**. The source location where the request was initiated. This is our magic moment.

The mockup shows this column as a text field with the location, but that's not necessary.  A small "outlink" icon that takes you to the source location is sufficient.  The hover text for the icon can be the full text.  This gets rid of a column.

**Comment by jasonLaster** [comment]
Thanks! While we're considering horizontal space, I believe chrome splits up the address into scheme, domain, and name. This lets them show `/upate-card` instead of `https://shopify.com/update-card?slkfjsjflfjlslsjlsfjslfj`
