### ISSUE TITLE
Show console comment button on hover

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3915]
Small nit, but the comment button should be treated consistently as the fast forward and rewind button and only be visible on hover. 

One could make the same argument about print statements, but i feel like that is slightly more important

<img width="631" alt="Screen Shot 2021-10-07 at 7 30 06 AM" src="https://user-images.githubusercontent.com/254562/136407759-803cc9a8-8272-4693-957b-3cb18a1c152f.png">

**Comment by jaril** [comment]
Not sure that we should do this. That comment button used to be a pause indicator. We then changed it to a comment button since clicking on the pause button didn't do anything.

That said, it's still an indicator that we're paused exactly at a console message's execution point. If we remove it, then being paused right before a console message and exactly at a console message would look exactly the same.

I think we need both the ability to 1) add a comment and 2) know when the debugger is paused exactly on a message. Right now that button is doing double duty, so I'm hesitant to only show it on hover until we figure out a separate way to indicate that a message is paused on.

@jonbell-lot23 @jasonLaster Thoughts?

**Comment by jasonLaster** [comment]
closing as the current ux feels pretty good

**Comment by jonbell-lot23** [comment]
And a reminder that we might want to explore the left-hand red line concept, separately
