### ISSUE TITLE
Update the loading screen design

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4000]
Zypsy passed along a loading animation. Can we please put this on our loading screen?
[loader.html.zip](https://github.com/RecordReplay/devtools/files/7335553/loader.html.zip)

**Comment by jonbell-lot23** [comment]
Ping ping! Friendly reminder that we've been holding off on this since 13 October, and the issue predates that by a few months. We know from design psychology that a loading screen goes a long way towards feeling professional, reliable, and fast.

Also see:
https://github.com/RecordReplay/devtools/issues/4541
https://github.com/RecordReplay/devtools/issues/3523

**Comment by jonbell-lot23** [comment]
As we wrap up the year, I'm going through old tickets and this one is turning into Moby Dick. I keep hunting for this! Let's ship it! Or harpoon it! Whatever the right verb is!

@kannanvijayan you mentioned that we're returning more information from the server. 
@abstractalgo you mentioned this in [Discord](https://discord.com/channels/779097926135054346/912494011464421436/918860232740986890). 
@gideonred you +1'd the idea
@jaril you've mentioned in the past that this is blocked, but I think it's less blocked now based on Kannan's comment?
@jasonLaster you've heard me bring this up frequently -- it's not a nice-to-have visual tweak, it literally affects people's perception of slow loading times, making it a top three goal.

So! Let's get this out! It's been delayed since mid-October! Jazz hands!

**Comment by jasonLaster** [comment]
@jonbell-lot23 in a world where we ship #4541, what is needed here? Asking because #4541 has an initial loading ui

**Comment by jonbell-lot23** [comment]
#4541 is definitely the main focus, and then this ticket is the animation cherry on top. Both important, but #4541 is first.

**Comment by jasonLaster** [comment]
Sorry for being slow, but still not sure what you are proposing this should look like?

**Comment by jonbell-lot23** [comment]
This is the design in #4541:
![image](https://user-images.githubusercontent.com/9154902/146727186-db2ccf81-12df-498d-9bc5-7f3736ecca85.png)

Once that's done, we can consider adding this animation. The animation is of our three red triangles, so we would position this animation in place of the current static red triangles.

**Comment by kannanvijayan** [comment]
On the "returning more information":

Currently the client knows which parts of the recording have been processed with basic processing (and less relevant to this discussion, which regions of the recording have been processed with heavyweight indexed processing).

This comes back to the client via events from the backend, delivered in response to the `Session.listenForLoadChanges` request.  The events come back via `Session.loadedRegions` event, with the following structure:

```
Session.loadedRegions {
  loaded: [
    { begin: TimeStampedExecutionPoint, end: TimeStampedExecutionPoint },
    { begin: TimeStampedexecutionPoint, end: TimeStampedExecutionPoint },
    ...
  ],
  loading: [
    { begin: TimeStampedExecutionPoint, end: TimeStampedExecutionPoint },
    { begin: TimeStampedexecutionPoint, end: TimeStampedExecutionPoint },
    ...
  ]
}
```

All the parts of the recording that are within `loading` represent parts of the recording we are intending to process.  Any timespan not represented in that array is a timespan that the controller has decided NOT to load due to resource constraints.

All the parts of the recording that are within the `loaded` array represent parts of the recording that have completed basic processing.

If there was a way to visualize this separately (a different "progress bar" that shows how much of it has been processed?), it would give the user a concrete understanding of the backend working on their recording and an estimate of how much is left before they can view their recording.

**Comment by jonbell-lot23** [comment]
I renamed this bug -- it used to talk about animation, but it's really just an issue of updating the visuals

**Comment by jonbell-lot23** [comment]
Actually, closing in favour of this one: https://github.com/RecordReplay/devtools/issues/4541
