### ISSUE TITLE
Show when there are incomplete results from the backend

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4218]
**Description:**

This is a sibling issue to  https://github.com/RecordReplay/backend/pull/3367#issuecomment-954202186

Where we indicate when protocol results are incomplete using errors and overflow properties

This is new behavior for the backend, and when testing with the devtools it will behave differently in some ways:

* [ ] In frames with too many steps (10,000+) the frame scrubber doesn't show, and resume/stepping commands do not work.
* [ ] Hovering over a breakpoint location with too many hits (10,000+) shows a "Failed" message in the gutter instead of the number of hits.
* [ ] Resume commands in parts of the recording with too many debugger statements (1,000+) do not work.
* [ ] Showing exceptions when there are too many (1,000+ in one part of the recording) doesn't work.

**Comment by bhackett1024** [comment]
The backend changes are done now, and with the changes in https://github.com/RecordReplay/backend/pull/3367 viewing a page with too many console messages (such as the one below) shows a warning in the console, which should become a warning in the devtools console pane.

```
<script>
foo();
function foo() {
  for (let i = 0; i < 2000; i++) {
    console.log("HELLO", i);
  }
}
</script>
```

**Comment by jaril** [comment]
Here's a glitch with that code sample: https://hilarious-typical-binder.glitch.me/

**Comment by jaril** [comment]
This appears to be an error that could be potentially-misleading to the user but is also not actionable. What I'm thinking is:
- Where things still _kind of_ work, we should 1) communicate that what they're seeing is not fully accurate and 2) link to some page that describes why replay behaves the way it does. 
- Where things don't work, we should 1) put them in a disabled state, 2) communicate to the user that that feature is disabled, and 3) link to some page that describes why replay behaves the way it does.

In both cases, replay's not doing what the user expects it to, so we really should document why that is to and provide context. It doesn't fix it for that user at that time, but maybe it adjusts expectations so they're less disappointed the next time it happens, or they know how to work around Replay's quirks.

**Comment by jasonLaster** [comment]
It'd help to visualize this. Could you mock these up in a figma page?

**Comment by jonbell-lot23** [comment]
I'm going though needs-design tickets so I came across this. Let me know if you'd like help drawing this up in Figma.

**Comment by jonbell-lot23** [comment]
Pinging @jaril -- let's talk about how to proceed on this, or let's icebox it if not high enough priority

**Comment by jasonLaster** [comment]
Lets discuss in the design sync

**Comment by jaril** [comment]
Updating this to note the current behavior.

# Audit

- Console stops displaying logs over #979
  - https://app.replay.io/recording/76ff5bc7-fcf7-459b-a711-86b1df46a6f4
  - https://app.replay.io/recording/0cef7f39-04c6-4993-9178-175aa24288ae
- Lines with 10k+ hits will return an error and say "Failed":
  - https://app.replay.io/recording/b7f9e88b-acf2-44c6-8c81-a9b7b3f252f3
  - 9k hits (still works): https://app.replay.io/recording/1139ff01-e7a6-4d7a-b8be-b9d7e30193cd
  - ![image](https://user-images.githubusercontent.com/15959269/148873528-75866abc-0279-4867-a0db-1f174567dd52.png)
  - The UI chokes when hovering on the line because it tries to render a bunch of points on the timeline. Maybe we shouldn't do that.
- Step debugging/frame timeline starts failing somewhere between 3-5k hits.
  - 3k hits: https://app.replay.io/recording/d98daef4-dae3-44a0-ab8d-4738d4ff8548
  - 5k hits: https://app.replay.io/recording/4e0f61e0-05b0-4561-be61-99d5042b4063

**Comment by jaril** [comment]
I'm thinking we should address each limitation as follows:
1) In frames with too many steps (10,000+) the frame scrubber doesn't show, and resume/stepping commands do not work
  - Let's pick a threshold after which we kneecap the pause info panel. We'll still display the non-functioning parts of the UI (commands, call stack, scopes), but we'll gray it out/communicate the limitations.
  - Gonna play with something in Figma.
2) Hovering over a breakpoint location with too many hits (10,000+) shows a "Failed" message in the gutter instead of the number of hits.
  - The error message (Failed) isn't very helpful. If we're reasonably certain that this happens after 10k hits, we could at least say 10k+ hits.
  - There's no recourse in terms of things we can do with a line that has 10k+ hits in terms of helping the user understand what's happening. Maybe we just own up, and/or have a read more link that sends them to a page where we talk about why we can't do anything more/what might be happening to their code/what they can do from their end so that they can debug that line better.
3) Resume commands in parts of the recording with too many debugger statements (1,000+) do not work.
  - If I'm understanding this correctly, this only happens if there are 1k+ debugger statements. That sounds like a very rare edge case. Happy to deprioritize it.
4) Showing exceptions when there are too many (1,000+ in one part of the recording) doesn't work.
  - This potentially allows the console to be misleading. We should call out that 1) there are too many exceptions and 2) that we're not displaying all of them. This isn't the most helpful, but last resort is we could maybe 3) have a read more link where we can explain how not to bump into that situation.

**Comment by jasonLaster** [comment]
Sounds like good suggestions. 

Lets also document these limitations in the docs as well. It'd be good to have a section for hot print statements that you cannot edit or cannot view. And then the upper bounds as well.
