### ISSUE TITLE
Fix hoveredComment

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#4271]
The `hoveredComment` from the redux store is sometimes set even though the mouse doesn't hover over a comment. I noticed this happened after I deleted a comment (https://app.replay.io/recording/0aadb8bb-27a4-4192-a263-5683263e9317).
One outcome was that a click on the Timeline didn't seek (see #4269). I fixed this in #4270 by not relying on `hoveredComment` anymore. However, there are some other places where `hoveredComment` is used, so I think `hoveredComment` still needs to be fixed.

**Comment by jaril** [comment]
We've cut back on places where we use the concept of a `hoveredComment`. Right now it's still being set, but it's really only ever checked for the behavior where hovering on a comment in the sidebar makes the corresponding comment in the screenshot visually flash/ping.

The off-behavior happened in that replay when we delete a comment. The user hovers on a comment, so that sets `hoveredComment` to some `commentId`. Usually we rely on a `mouseleave` event to clear `hoveredComment`. When the user deletes a comment, that `mouseleave` doesn't fire.

Should be a quick fix — just need to make sure we clear hoveredComment when a comment is deleted.
