### ISSUE TITLE
Library button colours are off (also fix the cancel button in our comments confirmation)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4361]
The text here should be blue:
![image](https://user-images.githubusercontent.com/9154902/140660712-27d334f4-0cf2-4cfa-a60a-ea0f0588493f.png)

And the background here should be white:
![image](https://user-images.githubusercontent.com/9154902/140660721-36f3f5b5-dd47-404b-8714-443cc3548417.png)

**Comment by jasonLaster** [comment]
white text would probably help, but also a simple grey border would probably be more standard. Thoughts?

**Comment by jonbell-lot23** [comment]
Copy/pasting reply from 3 weeks ago:
"It's true that grey is a common secondary button, but we don't use grey buttons anywhere (that I'm aware of). I would like us to stick with our design system for now, and then "earn the difference" later. If we can find multiple places to standardise on grey, great. But that should be done holistically later, not on one ticket in a one-off way."

In this case, I wouldn't consider our "Edit" to be a typical secondary action because it's a single action floating in space, rather than paired with a primary one.

Our current design system calls for blue backgrounds or blue borders, but no gray buttons. We can discuss that as an overall design system change, but this particular item is addressing a misalignment with the current system.

**Comment by jasonLaster** [comment]
First of all, kudos for remembering a conversation from 3 weeks ago.

I think the fact that this is coming up in a variety of contexts: Alert, Upload, Library, ... is a good reason to re-consider. It is also hard to have this conversation without more documentation in Figma, Storybook, etc... 

Lastly, at this stage we should also be okay with some experimentation while we sort out what feels right in different cases. Should not be a controversial point :)

Not saying a lighter gray button would look better here, but if we all agreed that it did. And I think it would be more common. Then we should be open to trying it and seeing how that impacts our holistic thinking.

Maybe A lighter grey button would be a lighter standalone button. Maybe we reject it in the future. Maybe we promote to the secondary button...

The larger point, is that the design system should encourage consistency by default, but should not block intentional experimentation. We're way too early for that.

**Comment by jonbell-lot23** [comment]
* I disagree with making it grey on aesthetic grounds (subjective)
* I disagree with making it gray on usability grounds (subjective)
* I disagree with special-casing a single button for nothing more than an aesthetic judgement (objective)
* I disagree with spending this much time on a smell detail

Sometimes we'll disagree on subjective calls. This is one of those times, and I don't think it's worth a bunch of back and forth. Let's disagree and commit because this ticket is specifically about black text + blue border. I recommend we go with the design POV, and if we feel like prioritising a broader conversation about special-casing a single button later, we can do that separately.

**Comment by jasonLaster** [comment]
Sounds good. My assumption was that we had agreement on what would look better and then it was a question of patterns.

Here are two other examples of button issues:

1. The cancel should also be blue
2. The primary focus should probably be primary (red)

<img width="557" alt="Screen Shot 2021-11-08 at 11 29 15 AM" src="https://user-images.githubusercontent.com/254562/140805606-e134a40c-e94d-4260-833e-14d69d7a1a3c.png">

**Comment by jonbell-lot23** [comment]
I agree with both of those, yeah:

1. That cancel button is inconsistent and should be addressed
2. I can see that focus being blue with no problem, but red's fine too

We've been doing a lot of good work in Figma and in discussions like these, and I think they're going to apply straight into our Storybook work. Looking forward to that.

**Comment by jonbell-lot23** [comment]
The edit button got blue text, which is great.

I haven't been able to figure out how to change the background of the "x items selected" button. Sending along to @jaril to address.
