### ISSUE TITLE
The upload screen is cropping off the save button

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4363]
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/9154902/140663412-baa2dd4c-4b44-4f4b-8053-23f95437e3d3.png">

When the upload screen window is too small vertically, we need to use responsive design to make sure the buttons aren't cropped off. Here's the design proposal

1. When we don't have enough space vertically, drop the screenshot.
2. Use an inline scroll so if the window is too small, at least someone can scroll down to it.

**Comment by jasonLaster** [comment]
Thanks. Simplest thing to do would be to offer an inline scroll which i thought we already had. Also there should always be some top/bottom margin

**Comment by jaril** [comment]
Tabling this one until next week, or maybe until later this afternoon in case a lightbulb goes off. 

There's so many layout considerations in the upload screen that this gets super tricky. Tack on the privacy panel that already has a scroller inside and it looks even wonkier.

@jonbell-lot23 We can save ourselves the headache if we just set a breakpoint and show a minimal upload screen instead of fiddling with the overflow. Got an idea of what direction you'd like for that to go in?

I'll probably pick this up later again and just design something basic that exposes the title, picture, team and public/private, like:

![image](https://user-images.githubusercontent.com/15959269/141513382-d45420c6-c985-4a7b-8aec-0e9238e55fe9.png)

**Comment by jasonLaster** [comment]
@jaril I like it, but a bit nervous about the additional complexity of maintaining two UIs. Also the privacy panel, etc...

My instinct is to throw in a scroll bar and call it a day, but dont feel strongly

**Comment by jonbell-lot23** [comment]
I think a few things are true:

* It's not the highest priority
* But an in-line scroll on one of our most important screens would look extremely weaksauce
* Cropping a save button is a non-starter, so we know we'll address this somehow. It's just a matter of how nicely we want to address it.
* It's not hard to add the privacy stuff because it's just a list with inline scrolls.

I think we should do something similar to what you've sketched above, @jaril . I'll think it through next week and we can hold off for now.

**Comment by jonbell-lot23** [comment]
Jaril mentioned that he needs a screen for this because we're dealing with scrolls inside scrolls.

**Comment by jonbell-lot23** [comment]
Check this ticket for the proposed design: https://github.com/RecordReplay/devtools/issues/4542

We keep the exact same layout with two exceptions:
1. Drop the image when the viewport is too small
2. Put the privacy section below, rather than to the right

**Comment by jasonLaster** [comment]
Looks good

**Comment by jonbell-lot23** [comment]
I'm going through old tickets I've filed with design-complete and seeing where we are on them. Ping!

**Comment by jasonLaster** [comment]
re-upping since this is important

**Comment by jonbell-lot23** [comment]
Re-upping further @jaril

**Comment by jonbell-lot23** [comment]
Re-upping
