### ISSUE TITLE
Stuck in loading screen

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4378]
**Description:**

Not sure why it takes awhile to create the store...
https://app.replay.io/recording/80fe060b-998a-4c08-b812-5dc9b1a1fdce?point=973555661944009792458515615320004&time=1107.8318168476665&hasFrames=true

**Comment by ryanjduffy** [comment]
I'm not sure what's going on here. I'm curious if there's a sourcemapping issue because the original file renders strangely, 

![image](https://user-images.githubusercontent.com/788456/140867242-7e27697b-fb36-4734-95fe-64adfa52d106.png)

lines that seem to be breakable are not

![image](https://user-images.githubusercontent.com/788456/140867353-f1df96ce-9596-4ac1-951a-cb691e8206b7.png)

And i can't step past this breakpoint

![image](https://user-images.githubusercontent.com/788456/140867383-f80a1402-7d0f-4b78-b634-583aea88159a.png)

**Comment by hbenl** [comment]
I also noticed strange behavior with this recording. I've added comments showing how you can end up paused at a line that shows "0 Hits", which reminds me of RecordReplay/node#23.

**Comment by jcmorrow** [comment]
For now, going to close this in favor of the Issue page for Source Maps (which tracks work that is valid, but not currently on the immediate roadmap): https://www.notion.so/replayio/Source-Map-Issues-e761f8ac000d4bcd94adb9a8c2f74d38
