### ISSUE TITLE
Inline preview highlights should include the dots

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4425]
Small nit, but other browsers include the dots as part of the expression

<img width="370" alt="Screen Shot 2021-11-09 at 10 49 10 PM" src="https://user-images.githubusercontent.com/254562/141133212-1b365f69-7069-47bb-8800-cb2f7e79fac7.png">

**Comment by jaril** [comment]
This one might be tricky since the way we add highlighting is with a classname, and those parts of the expression (e.g. `.()[]`) are not wrapped in an element.

**Comment by jaril** [comment]
I'm still confused since I haven't noticed this before. I just tested what the behavior of vanilla firefox devtools is — it looks like it only highlights the token being hovered on. Is it possible we added the highlight-the-previous-elements at some point? Either intentionally, or it was broken and then we fixed it with a PR (maybe https://github.com/RecordReplay/devtools/pull/4200 ? )

**Comment by jasonLaster** [comment]
Good question. I think you're right. It's totally fine to just highlight the last token.
