### ISSUE TITLE
Empty state for events panel

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#4653]
[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/?node-id=9165%3A117266)

**Comment by jonbell-lot23** [comment]
![image](https://user-images.githubusercontent.com/9154902/143505265-b65e72fb-a5b9-4720-944e-4b17947a5d09.png)

This is similar to #4676. We need to use a spinner because our new UI doesn't work as well with spinners. #shipit!

**Comment by jasonLaster** [comment]
Should we get rid of "Loading Events..." in the Info panel?

**Comment by jonbell-lot23** [comment]
Good question @jasonLaster -- my understanding was that there are multiple stages of things that need to be loaded. If so, you could end up in a state where events have loaded ... but there are other issues that might make the Replay load slowly.

So two questions:

1. Can this happen? Events loaded but other things slow?
2. If this can happen, are we ok with our global loader (the circle around the play button) and our per-pane loaders (such as in the diagram above) providing enough loading data? I am, but curious to know your thoughts.

Because if so, yeah! I think we can totally drop it.

**Comment by jasonLaster** [comment]
I think we can drop "Loading Events..." in the Info panel.

**Comment by jonbell-lot23** [comment]
Filed a ticket: https://github.com/RecordReplay/devtools/issues/4692
