### ISSUE TITLE
Add a launcher 

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4682]

**Comment by jasonLaster** [comment]
Thinking about this more, we might cover this by doing the command palette embedded in the default editor. We might also find that really making "Find File" obvious is the winner.

**Comment by jonbell-lot23** [comment]
Totally agree. I think there's a range:

1. The slight upgrade that's currently on prod
2. ???
3. A full super awesome palette

It's possible that there's a cool number 2 intermediate stage, and it's possible the answer is just to jump to number 3.

**Comment by jaril** [comment]
I get that sticking default actions in the editor is a common pattern and we've done it as well so it feels right to keep figuring out the right way to do it.

On the other hand, I think it's worth bringing up that it's possible that the important things we're trying to surface is important enough to get its own real estate in the UI. Otherwise, we'll keep bumping into being-in-the-editor-related problems, e.g. how do we display things when the editor gets too small.

Rough version of this idea is a Launch Window, which I used to see all over the place in Adobe products. The basic version being a simple modal with the 3-4 main actions that we're currently displaying in the blank editor. And if we find it to be helpful, start surfacing more things on there (without being overbearing).

Sketch's launch window.
![image](https://user-images.githubusercontent.com/15959269/144456055-0c178dd3-6e39-4e28-81aa-354d55541650.png)

@jonbell-lot23 thoughts?

**Comment by jasonLaster** [comment]
Thanks @jaril I like the idea that we could be more visual here I think it might be more delightful and probably more likely to bring people into the interface we want

**Comment by jonbell-lot23** [comment]
100% and this ties (or could tie) to the command palette

**Comment by jonbell-lot23** [comment]
From a resourcing standpoint, but I don't have cycles to build this just yet, but I love the idea. We can also do low fidelity now and build it out more beautifully later.

**Comment by jaril** [comment]
Figma: https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=8958%3A84248

**Comment by jonbell-lot23** [comment]
Here's a little story I'm telling about how the editor's default state (and the console) can be more helpful:
https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9165%3A91915

Here's a one minute video explaining how the command palette can fit into this default state scenario:
https://www.loom.com/share/f46cd3ba5c1240d4acb9c1e89bd82dcc

**Comment by jasonLaster** [comment]
Here's a rough version of a visual launcher that could go hand-in-hand with the command palette 

https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9446%3A88954

<img width="1440" alt="Frame 308 (2)" src="https://user-images.githubusercontent.com/254562/145118171-d5aa8b49-0706-4f78-b0c5-19461e9eaa96.png">

**Comment by jonbell-lot23** [comment]
Hello! Don't think of this as a long Loom video, think of it as an extremely compact six minute meeting :)
https://www.loom.com/share/695108e83432492c86da7df1799858bf

Here's the Figma page where I drew these up:
https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9456%3A94169

**Comment by jasonLaster** [comment]
launched
