### ISSUE TITLE
Show when no regions loaded

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#4715]
In this recording in this link https://github.com/RecordReplay/ops/issues/376#issuecomment-980378493 (not providing the recording directly because it was shared with us externally) we unloaded large parts of the recording (possibly the entire recording, not sure), but there is no indication of this in the UI.  We have a mock test checking that the UI updates to show unloaded regions.  Is this test not enabled, or not working?

Also, we used to have console logs when the loaded regions from the backend changed.  I found these pretty handy to see what was going on, irrespective of the UI, but they don't seem to be logged anymore.  Can these be added back?

**Comment by jasonLaster** [comment]
It looks like the backend finishes basic processing without sending any regions loading/loaded/unloaded back to the client.

https://app.replay.io/recording/8da1c8cd-27d5-475d-ac6a-56a1b642a514?point=6490371074441831421644261809979895&time=3545.998507184176&hasFrames=true#

**Comment by bhackett1024** [comment]
Oops, it sounds like this is my fault.

**Comment by bhackett1024** [comment]
Some backend changes went out this morning and it looks like loaded/unloaded regions are being sent to the client.  It is not updating the timeline or UI to show when parts of the recording are unloaded, however.  Here is a new recording with comments:

https://app.replay.io/recording/5dc35372-83c2-43b1-8a72-abc92b5e1970?point=95732973347510809735830523888010400&time=33972&hasFrames=true#

**Comment by bhackett1024** [comment]
> It looks like the backend finishes basic processing without sending any regions loading/loaded/unloaded back to the client.
> 
> https://app.replay.io/recording/8da1c8cd-27d5-475d-ac6a-56a1b642a514?point=6490371074441831421644261809979895&time=3545.998507184176&hasFrames=true#
> 
> The client could show an error in this case, but other than that I think it is handled correctly.

Looking more closely at the recording, it looks like the backend was sending correct events.  It did send a loadedRegions event, it's just the case that the loaded/loading region arrays are empty in the event.  That means the entire recording is unloaded.  It is not an error, and the frontend needs to be able to handle this case.  (Now, the fact that we unloaded the entire recording is a backend issue I'll be dealing with, but that's a separate concern.)

**Comment by jaril** [comment]
The loaded/unloaded regions appears to be that we're selective about when we start differentiating the timeline into loaded/unloaded regions. Specifically, we don't show it until `loading` and `loaded` are the same. In this case, we unloaded regions but the `loading` wasn't fully finished so we didn't show any indicators that part of the progress bar was actually unloaded.

The fully transparent way to handle this would be to have two separate indicators for 1) parts that have been unloaded, and 2) parts that are loaded but are currently loading/buffering. Right now our treatment simplifies these two indicators into one by treating them as the same, which only works because that happens to be the case once the actually-loaded regions are fully loaded.

x | Current | Proposed
-- | -- | --
Before region data is received | 🟩🟩🟩🟩🟩🟩🟩 | 🟩🟩🟩🟩🟩🟩🟩
Once we know unloaded regions | 🟩🟩🟩🟩🟩🟩🟩 | 🟥🟨🟨🟨🟨🟨🟥
Once the loading progress for loaded regions starts progressing | 🟩🟩🟩🟩🟩🟩🟩 | 🟥🟩🟩🟩🟨🟨🟥
Once loaded region is fully loaded | 🟥🟩🟩🟩🟩🟩🟥 | 🟥🟩🟩🟩🟩🟩🟥

Separately, we should handle the loading and loaded are empty arrays (like in this [recording](https://app.replay.io/recording/8da1c8cd-27d5-475d-ac6a-56a1b642a514?point=6490371074441831421644261809979895&time=3545.998507184176&hasFrames=true#)).
