### ISSUE TITLE
ObjectInspector component not updating properly

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#476]
This is a tricky issue that took some time to investigate.  We have an automated test that checks that after expanding some nodes in the console, their contents match an expected value.  One of these tests failed, with the recording below.  An object in the graph has its initial contents, before its preview has been loaded.  As seen in the comments on the recording, its preview is loaded, which should update the associated ObjectInspector with the object's fully loaded contents.  After the preview is loaded and the redux state updated, shouldComponentUpdate is called on a bunch of ObjectInspectors, but *not* the one of interest.  So, it never re-renders and the object retains its initial contents.  Figuring out what's going on seems like it requires understanding the associated react state.

A possibly related issue is that the buggy ObjectInspector isn't rendering properly --- it should be expanded but it is rendering as collapsed.  I didn't look into what was happening here.

https://replay.io/view?id=2c705052-0916-4df1-9287-76ed304b2b88

**Comment by hbenl** [comment]
It looks like we're creating 2 sets of pauses for the same points in time.
I set a logpoint at line 34 of `protocol/logpoint.js` and got this:

![Screenshot_2020-09-05_15-59-29](https://user-images.githubusercontent.com/16060807/92306589-88f04c00-ef90-11ea-93c8-29bb841014cd.png)

Setting another logpoint in the `render()` method of `ObjectInspectorItem` with message `"Render " + this.props.item.path` shows that after the second set of pauses is created, only `ObjectInspectorItem`s for those pauses are rendered, I'm guessing that they somehow replace the corresponding `ObjectInspectorItem`s for the first set of pauses (???)
Finally, when the data for updating the `ObjectInspectorItem` that we're interested in arrives, it is outdated because it references one of the pauses from the first set, but the second set of pauses has been created in the meantime.

**Comment by jasonLaster** [comment]
closing as i haven't seen this for awhile. Happy to re-open it if it is still an issue
