### ISSUE TITLE
Full text search should include results for evals

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4804]
I am pretty sure that full text search is not searching the text for evals which means we'll not be able to find the eval'd source for webpacks inline-modules.

https://app.replay.io/recording/072ec812-0002-4e6f-9e68-95d54010d1cf?point=64579192183267684738049115982662221&time=24786&hasFrames=false

**Comment by hbenl** [comment]
I assume that you expected to see the original source in the search results and not only the generated source (the webpack bundle). The reason why it's excluded from the search is that it's a third-party source (because it has `node_modules` in its URL) which we decided to exclude for now, this has nothing to do with eval.
