### ISSUE TITLE
[Tooling] Run tests on CI

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#481]
The local tests should run on CI.

Optimistically in ~5 minutes.

**Comment by bhackett1024** [comment]
We now have a CI/CD pipeline in place that uses github actions.  On pushes to the master branch we run our test suite (recording the viewer itself) and update the production website if all tests pass.  I've been fixing things to get the tests to actually pass, which they are at least capable of now (https://github.com/RecordReplay/devtools/actions/runs/226182369).  I'll continue monitoring this for intermittent failures, but we should try to use this to control deployments instead of doing things manually.

**Comment by bhackett1024** [comment]
Oh, and building the webpack and running all tests takes about 7 minutes, if they all pass.  If there are test failures it can take longer, but not more than 12 minutes or so (there is a hard limit on how long we let a subset of tests run for).
