### ISSUE TITLE
CommandPalette - "Open Viewer" leaves the sidepanel

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4939]
https://app.replay.io/recording/b26df7ad-6a7a-4770-86da-ab841929c159?point=26610521419020861461449900973622165&time=13404&hasFrames=false#

**Comment by ceceliacreates** [comment]
Added some comments to the Replay, can carve out some time to work on this. Looks like moving the setSelectedPrimaryPanel check logic to the reducer for setViewMode would make sense.

**Comment by ceceliacreates** [comment]
There is actually another consideration here which is the toggle animation. Right now there is a delay before switching the view to allow for the animation. When using CommandPalette to switch view, it does not have this delay. If we want to keep this delay it would also need to be pulled out into setViewMode.

**Comment by jasonLaster** [comment]
I think we only need the delay for the toggle button with the animation.

**Comment by ceceliacreates** [comment]
> 

The toggle button still animates when using "Open Viewer".

Three things happen with the UI when switching views using the toggle:

- The toggle animates **THEN**
- The view changes (after delay) AND
- The sidebar updates if needed (after delay)

Right now when using "Open Viewer", the following happens:

- The toggle animates AND
- The view changes (without delay)

I believe we'd want these to be consistent regardless of what triggers the view change.

**Comment by jasonLaster** [comment]
That's fair. I would have expected the toggle to not animate if using the command palette.

**Comment by jaril** [comment]
@ceceliacreates I think you mentioned that you had a code-related to do item at standup yesterday. Is this it?

Added it to the current sprint just in case you're going to work on it. If not, let me know and we can move it/I can get a fix in! :)

**Comment by ceceliacreates** [comment]
@jaril Yes, this is the one! I can work on it, thanks for the reminder and for adding to sprint.

**Comment by ceceliacreates** [comment]
> That's fair. I would have expected the toggle to not animate if using the command palette.

It looks like this happens because we adjust localViewMode when it is out of sync with viewMode. This triggers a refresh of the ViewToggle, which animates to align with the viewMode when it is updated elsewhere. (Added a comment in the replay where this occurs).

Because the ViewToggle animation is reactive to the viewMode change, it will always happen after the layout has already updated. 

I made the changes to fix the sidebar, but will create a separate issue for the toggle animation timing issue.

I believe a potential fix would be to change `localViewMode` to `toggleViewMode` that is tracked in Redux instead of locally. Then, when the setViewMode function is called, we would update `toggleViewMode` to trigger the animation, have a setTimeout to allow for the animation, then move forward with dispatching the `selectedPrimaryPanel` and `viewMode` updates. We'd want to ensure `toggleViewMode` is only ever updated in the same function as `viewMode` to keep them in sync. Not sure if this is the best approach though.
