### ISSUE TITLE
[Recorder] cannot record mastery.games

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#499]
STR:
1. go to https://mastery.games/gridcritters/

https://replay.io/view?id=3466949c-c4d8-4442-8797-ce4f0b42f367

**Comment by bhackett1024** [comment]
The problem here is an exception being thrown when the page creates an AudioContext, which seems to be breaking the page load.  We don't support AudioContext or other Web Audio features yet, see https://github.com/RecordReplay/gecko-dev/issues/55.  I added a comment on the exception in the recording.
