### ISSUE TITLE
Improve login wayfinding

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5065]
The current Auth0 IA has a giant dead end where people try to put in their emails.

https://auth0.com/docs/customize/universal-login-pages/universal-login-page-templates

**Comment by ryanjduffy** [comment]
I experimented with the Auth0 "classic login" experience and I was not impressed. :) AFAICT, you can't do home realm discovery with it and it has limited customization options. Instead, I've found that we can pass the `connection` prop to `loginWithRedirect` to choose the idp so we can implement the login selection on our side as long as we do the home realm discovery (which we can because we have the domain and connection name in the db already).

@jasonLaster, @jonbell-lot23 - Could use some design/copy 👀 on the login flow. I expect we'll want to get this into the design guide too but wanted to throw something out here for feedback.

![image](https://user-images.githubusercontent.com/788456/151870566-9e056458-7916-455f-91a7-fcbcf412923a.png)

**Comment by jonbell-lot23** [comment]
@ryanjduffy This is such an important page that I recommend against putting everything together on a single page (logo, blurb, call to action, header, descriptive text, text field, second call to action). [Hick's Law](https://lawsofux.com/hicks-law/) teaches us that the more we put on the page, the harder it is to comprehend and proceed through.

So I'd recommend it being a text link beneath the button, then we can ask for their email in a modal dialog.

![image](https://user-images.githubusercontent.com/9154902/151872221-8a6f7b35-c106-4ba0-9c6f-0e192b06c854.png)
