### ISSUE TITLE
Improve e2e and mock tests

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#5137]
- fix the tests that are currently skipped
- replace our homegrown test runner with jest
- remove the distinction between e2e and mock tests (all tests should use the GraphQL mocks, the protocol mocks are optional)
- rewrite the tests to not run in the browser anymore

**Comment by bhackett1024** [comment]
>     * rewrite the tests to not run in the browser anymore

Can you elaborate on this point?

**Comment by hbenl** [comment]
@bhackett1024 Currently our test scripts run entirely in the browser and write their results to the browser console, which our test runner script then extracts using playwright. I would like to use playwright the way it's intended to be used: run the test script outside of the browser and control the browser using playwright's API. This is certainly the most controversial part of this issue since the rewrite would require some work without providing an immediate benefit, so it's just a proposal for now.

**Comment by bhackett1024** [comment]
> @bhackett1024 Currently our test scripts run entirely in the browser and write their results to the browser console, which our test runner script then extracts using playwright. I would like to use playwright the way it's intended to be used: run the test script outside of the browser and control the browser using playwright's API. This is certainly the most controversial part of this issue since the rewrite would require some work without providing an immediate benefit, so it's just a proposal for now.

Cool, thanks for explaining!  I agree this would be a really nice architectural change, and I think it's worth doing.  I feel it *does* provide an immediate benefit, which is that it gives us a chance to more effectively dogfood the use of replay+playwright for building a test suite that's easy to debug.  We should make it work in as close a way as we can to what users will want to use playwright for, so that we can make sure this is a good experience for ourselves and so that we can show it to users as an example.

**Comment by abstractalgo** [comment]
@hbenl with the PR merged, do we close this ticket or maybe leave it for some more work?

**Comment by jasonLaster** [comment]
feel free to re-open or open a new issue
