### ISSUE TITLE
Repaint protocol error whenever you load a fully played recording

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#5140]
@hbenl first pointed this out because it was causing some E2E tests to fail. When you load a recording at its end, the frontend requests a paint, and that doesn't work, so the protocol errors. This isn't a huge deal or anything, but it would make sense to me to always request the last paint you have available, rather than one that we know will error and result in a blank player.

**Comment by jasonLaster** [comment]
Absolutely.

**Comment by hbenl** [comment]
>  it would make sense to me to always request the last paint you have available, rather than one that we know will error and result in a blank player

We already request a _recorded_ screenshot first (and AFAIK this works fine even at the end of a recording), so Replay shouldn't show a blank player because of a repaint failure.
Also, I would prefer to see this fixed in the backend rather than assuming that our recordings will always be broken at their endpoint and working around that.

**Comment by hbenl** [comment]
@jaril No, I don't think there is one.
