### ISSUE TITLE
React DevTools error messages UI polish

### ISSUE THREAD

**Issue by abstractalgo** [RecordReplay/devtools#5320]
Messages shown for different React DevTools failed scenarios probably need more UI polish.

This ticket is created following https://github.com/RecordReplay/devtools/pull/5134. To see the state of it, check out [this comment](https://github.com/RecordReplay/devtools/pull/5134#issue-833388625) in there.

**Comment by jaril** [comment]
@jonbell-lot23 any interest in picking this up?

**Comment by jasonLaster** [comment]
@abstractalgo could you add some screenshots of what it looks like nw

**Comment by jonbell-lot23** [comment]
Yup, this is my kind of issue. On it.

**Comment by jonbell-lot23** [comment]
Note while tagging tickets:

Not super important, but also won't take long.

**Comment by jonbell-lot23** [comment]
@abstractalgo a few thoughts and questions:

1. I assume the first image is something that will resolve itself when the page loads, and the second issue is a more critical issue that might not resolve itself?

2. Will the screen automatically fix itself or will it require some sort of manual refresh?

3. Details will depend on the answers to #1 and #2 but it's likely this issue can be closed with a minor copy tweak. (And maybe even making both errors show the same copy) Anything else this issue was looking for?

**Comment by abstractalgo** [comment]
@jonbell-lot23 

For the first case - the user needs to move on the timeline to a further point in time. The second one could be non-fixable if we had a problem init React DevTools, but maybe a reload helps.
