### ISSUE TITLE
Ship the new accordion

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5375]
We should ship the new accordion in style

- [x] Update Replay
  - [x] https://github.com/RecordReplay/devtools/issues/5351
  - [x] https://github.com/RecordReplay/devtools/issues/5378
- [ ] Publish Package
  - [ ] Publish Accordion to NPM 
  - [ ] Publish standalone snazzy website 
  - [x] Move Accordion to its own workspace similar to packages in backend

**Comment by jaril** [comment]
Talked about this earlier and came to the conclusion that the info pane didn't really benefit much from an Accordion since it only has two panes. Since the first pane is fixed (and is relatively small), it's not like there's much of a need to play with the layout just to see all of the second pane's content. We can probably get away with just implementing a fixed version of those panes instead to keep things simpler.

**Comment by jasonLaster** [comment]
closing. we can revisit later
