### ISSUE TITLE
Print statements not working on one line

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5449]
Here's a Replay of me calling out the error: https://app.replay.io/recording/print-statements-not-working-on-one-line--dc561490-ad1b-4119-90a2-f47ffe26517f?point=86646453831483074379778054739199933&time=30481&hasFrames=false

Here's the Replay where you can reproduce the issue yourself: https://app.replay.io/recording/selected-state-is-wrongggggggg--7dd72d83-06d6-4b13-88c4-ffe099db31d2?point=4867778304887162271071340618317989&time=3325&hasFrames=false

Line 57 won't let me add a print statement. Josh confirmed the same issue on his side.

**Comment by jonbell-lot23** [comment]
@jaril and @jasonLaster discussed the issue here: https://discord.com/channels/779097926135054346/869029659751350293/946210098466938930

![image](https://user-images.githubusercontent.com/9154902/155897317-aaf62843-779d-4889-98e2-59946488d512.png)

**Comment by jonbell-lot23** [comment]
Following up on this icebox label -- what's the background here?

**Comment by jasonLaster** [comment]
icebox means it is de-prioritized and probably could be closed and re-opened

**Comment by jonbell-lot23** [comment]
Right, I'm saying part of our process should be explaining rationale so we know why certain things are in inbox.

This particular bug is our most important feature failing outright, so it'd be good to know the background. For example:

* The ROI is bad -- this happens infrequently and is extremely hard to fix
* We absolutely should fix it, just not this month
* Etc

**Comment by jasonLaster** [comment]
Good point. The context behind the decision would be helpful

**Comment by jaril** [comment]
> icebox means it is de-prioritized and probably could be closed and re-opened later

Pretty much. Still working out the heuristics, but after ~3 weeks of regularly reviewing issues, we've found that if something is 1) not going to be worked on in the next ~2mos because of priorities/difficulty and 2) we're reasonably confident that it'll be brought to our attention again after 2mos time (either user feedback or because we personally bump into it), then it gets closed. For things where we're less confident about #2 (i.e. boomerang-ing back), then it gets the icebox label, since otherwise it's easy to unintentionally forget about it.

> This particular bug is our most important feature failing outright, so it'd be good to know the background.

Yep! In this case it's the first one — ROI is bad because it:
- Happens infrequently (first time I've seen it in the wild but we're going off my anecdotal experience so i'm happy to be told otherwise here).
- The fix doesn't seem to be straightforward (issue appears to be linked to an original firefox devtools bug).

There's more investigating that could be done and it's possible that it ends up being a simple fix. But with other things on the plate unless there's increased evidence for it happening, icebox felt the right thing to do here.

**Comment by jonbell-lot23** [comment]
Closing for now
