### ISSUE TITLE
[UX] Fetching network request details in an unloaded region

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#5606]
This is a follow up item to #5605 which addressed #5282.

We need to consider what should happen when the user tries to click on a request that's in an unloaded region.

Things to consider:
- A link to docs about loaded/unloaded regions and why it affects things you can see in the UI.
- If the current unloaded region will eventually be loaded, then some auto-refresh capability so the request details show up immediately once it's ready.
- If the current unloaded region has been permanently yanked away by the backend, some explanation about what had happened and how they should probably use focus mode so that we can load what they're interested in.
- Maybe we shouldn't allow users to click into a request in an unloaded region in the first place.

**Comment by jonbell-lot23** [comment]
Hello! Here's the design proposal.

First, we should allow people to click in rather than disallowing the click at all. This lets us message better.

**1. If it will eventually load**

* Use our standard progress bar across the top
* Text: something like "Loading..."

**If it will never load because it's outside of Focus Mode's window**

* Text: something like "This request is outside of Focus Mode. Click here to resize Focus Mode."

**If it will never load for a reason that the user can't fix**

* Text: "Apologies, this request is not available. Learn more about what can cause this error." <-- link to docs

**Comment by jonbell-lot23** [comment]
Assigning to @jaril for discussion and implementation

**Comment by jaril** [comment]
> Assigning to @jaril for discussion and implementation

Let me take a stab at it the way you proposed and let's feel it out!

**Comment by jaril** [comment]
Carving off #1 — pretend that the unloaded network details will be loaded at some point, and in the meantime we should show the progress bar and loading text. Then swap it out once it's available.

#3 is more difficult so we'll address it separately afterwards.

**Comment by jaril** [comment]
Just noticed that #1 is actually being handled with the current behavior. Will close for now.

**Comment by bvaughn** [comment]
Hey @jaril and @jonbell-lot23!

I think this UX could still use some improvement. (See #6511 where I thought the current behavior was actually a bug/something broken.)

> > 1. **If it will eventually load**
>> Use our standard progress bar across the top
>> Text: something like "Loading..."
>
> Just noticed that https://github.com/RecordReplay/devtools/pull/1 is actually being handled with the current behavior. Will close for now.

I think the spirit of the comment was to show the user that "this is a transient thing and it's expected to change soon". I don't think our current UI does that. "_Request details currently unavailable_" doesn't imply (to me) that they are expected to become available soon. I actually interpreted the current wording more as "something went wrong and this data couldn't be loaded" which is why I filed a bug about it.

https://www.loom.com/share/0c475d66ba174e46b0c0ad2f837f11d1

Can we reopen and revisit this? 😄

**Comment by jaril** [comment]
> Can we reopen and revisit this? 😄 I'll be happy to work on it myself.

Good catch—I think that sounds good!

**Comment by jcmorrow** [comment]
And I'll add it here as well because it looks like it might get lost over on #6511, but there's two other things:

1) network requests that are outside of the focus window disappear, but network requests that get unloaded do *not* disappear. I think this is not great from a consistency standpoint
2) right now, even if a network request is in an unloaded region, we request it's body when the user selects it, and we should not do that, because it will always result in a protocol error.

**Comment by bvaughn** [comment]
> 1. network requests that are outside of the focus window disappear, but network requests that get unloaded do not disappear. I think this is not great from a consistency standpoint

I think this is actually the desirable case– for reasons I mentioned here: https://github.com/RecordReplay/devtools/issues/6511#issuecomment-1106503035

Happy to chat about this though!

right now, even if a network request is in an unloaded region, we request it's body when the user selects it, and we should not do that, because it will always result in a protocol error.

**Comment by bvaughn** [comment]
> right now, even if a network request is in an unloaded region, we request it's body when the user selects it, and we should not do that, because it will always result in a protocol error.

Are we actually doing this? Our actions seem to verify that the request is loading before firing off that request:
https://github.com/RecordReplay/devtools/blob/3ccd585328fbeca847ad0ff7a1d356820daf572c/src/ui/actions/network.ts#L86-L109

And I think this is the only place we call `ThreadFront.fetchRequestBody` or `ThreadFront.fetchResponseBody`

**Comment by jonbell-lot23** [comment]
Just chiming in to say I saw this and I'm following along passively

**Comment by jonbell-lot23** [comment]
Just watched the Loom, and yeah. Messages should never be a dead-end like that. As you said @bvaughn , you always want some sort of progress, and copy that explains that it should eventually work, and in the case of a total failure, you should explain how to fix it. We're on the same page there 100%.

**Comment by bvaughn** [comment]
PR #6534 does not resolve this issue but it is related so I decided to lint it here. I'd be happy to work with Jon on a follow up, more of a "final" solution.

**Comment by bvaughn** [comment]
@jonbell-lot23 I think you and I should chat about what the next steps should be fort his ticket now that PR #6534 has landed. Quick reminder of where things currently stand as of that PR: https://www.loom.com/share/f2366f55c10c4dd3a54b261b27726918

**Comment by jonbell-lot23** [comment]
Sounds good @bvaughn -- also attaching this ticket: https://github.com/RecordReplay/devtools/issues/6622

Will grab you early next week

**Comment by jaril** [comment]
@jonbell-lot23 @bvaughn did you guys end up catching up on this this week yet?

**Comment by jonbell-lot23** [comment]
Here's where the design thinking is happening -> https://github.com/RecordReplay/design/issues/52

**Comment by bvaughn** [comment]
Going to un-assign myself and assign Jon to this one for now. I don't see any mention of "network" or "request" or anything on the linked design ticket (other than the backlink to this issue) so I think it's probably not actionable on this side yet.

Note that #6822 slightly improves the user story here for the comment-to-request flow.

There's still more to be done here though. The UI _dims_ comments that are outside of the focused region, but their "preview" panel (which you can click to select a network request) still shows a hover cursor and highlight even though clicking it does nothing because of code checks like this:
https://github.com/RecordReplay/devtools/blob/ad33e7be3cddfe7520a194a1d1dd407dcf63b8cb/src/ui/actions/network.ts#L90-L99

**Comment by jonbell-lot23** [comment]
@bvaughn are you able to drive forward on this without visuals? It sounds like removing the hover cursor and highlight addresses the bit you're referring to above, but I'm not sure what other items to handle.

I also realise that I might have grouped these tickets incorrectly. I think I saw "network" and "region" and thought it was referring to our other unloaded timeline items. I'm going to go remove that link now.

**Comment by bvaughn** [comment]
If the only thing remaining to be done for this ticket to be completed is to fix the hover/cursor issue– then absolutely I can do that. It just wasn't clear to me what the "ask" was here :)
