### ISSUE TITLE
Handle recording uploading failure (gracefully)

### ISSUE THREAD

**Issue by abstractalgo** [RecordReplay/devtools#5651]
> seems like there's some missing error handling on the save button? If an upload fails it feels like a) the user should see something and b) we should be notified

**Comment by jonbell-lot23** [comment]
Pinging @abstractalgo and @jaril -- can you repro this so I can see what we currently do?

**Comment by jaril** [comment]
> Pinging @abstractalgo and @jaril -- can you repro this so I can see what we currently do?

@abstractalgo do you know enough to provide more details? I think there's multiple ways for an "upload" action to fail and I don't have a good sense of 1) what they are 2) what happens if it fails.

All I know is that after hitting upload, we essentially hit Refresh — and so the recording is loading as if it were opening a regular replay. If something wonky happened during the uploading, then it doesn't show up as a specific uploading-related error, instead it manifests itself in some screw-y loading, e.g. graphql failure (maybe can't find the recording), backend failure (maybe leads to some internal error). 

Then again I'm not sure.

**Comment by abstractalgo** [comment]
I quoted somebody who wrote that in Discord, but I'm lacking the full context as well, sorry.

**Comment by jaril** [comment]
https://discord.com/channels/779097926135054346/869029659751350293/950453149360070736

**Comment by jonbell-lot23** [comment]
Ah ha, here we go. From @jazzdan :

"Whenever I try to save a recording in prod I get this in the JS console: 
ReferenceError: REPLAY_DEMO_URL is not defined"

And then here's a Loom showing it in action:
https://www.loom.com/share/bf1033687da94545a45ae5ee0068830a

I'm going to rename this bug to apply to this issue and assign to @jaril

**Comment by jasonLaster** [comment]
closing since I dont see enough context
