### ISSUE TITLE
"Pause Info" panel does not allow scrolling the entire panel

### ISSUE THREAD

**Issue by markerikson** [RecordReplay/devtools#5855]
**Description:**

The "Pause Info" pane doesn't have an outer scrollbar. I'm currently looking at a very long "Call Stack" accordion panel, and the "Scopes" accordion is smooshed all the way to the bottom.  As long as "Call Stack" is open, I can't view "Scopes" - I have to minimize "Call Stack" first.

**Steps to Reproduce:**

- Open a replay and click the "Pause Info" icon to show the panel with "Call Stack" and "Scopes"
- Pause the UI in a location that has a very deep call stack (15-20 functions)
- Expand "Call Stack"
- Observe that "Scopes" is at the bottom and cannot be viewed until you collapse "Call Stack"

**Expected Result:**

There would be some outer scrollbar allowing the entire panel to scroll while both accordions are open.

**Additional Context:**

* Screenshots: 

![image](https://user-images.githubusercontent.com/1128784/158877531-1efcef6b-0840-4d95-83a6-64b2a91e6ae4.png)

* Replay: TBD

**Comment by jasonLaster** [comment]
@jaril this feels like something that should be an accordion where you can resize the call stack. Also better defaults

**Comment by jaril** [comment]
Yeah it should be. This was supposed to just use the new accordion package, but we stopped short of applying it here because at the time I thought it required some major changes. For example, the accordion should handle panels popping in and out and maintain the user's height preferences throughout, because Print Statements/Breakpoints panels are displayed/hidden based on whether you're on a pause point.

Since then i've realized we may be able to take a shortcut by implementing the two accordions side by side, so keep the debugger commands/frame timeline/breakpoints/print statements on the old accordion, and as a sibling element, add the new accordion with the Scopes/Call Stack.

Sticking it to next sprint/early April!
