### ISSUE TITLE
[RTK/TS] Debugger Sources

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5902]
As part of https://github.com/RecordReplay/devtools/issues/5893, we are going to focus on how sources are stored in the reducer and the thunks / selectors associated with them.

Tasks:

- Investigate and document existing sources logic
- Migrate existing sources logic to TS as-is
- Rewrite sources logic with RTK

**Comment by markerikson** [comment]
This is partially done, but we're going to call it completed for now.

The `sources` and `source-actors` reducers have been converted to TS, but it's all still "hand-written" Redux logic rather than fully migrated to RTK.  As much as I'd love to be using `createSlice` here, doing so would require more effort than we can justify at this moment.

I'll close this issue, and we'll add more issues at some point when we decide it's time to do further RTK migration.
