### ISSUE TITLE
Call Stack shows NextJS incorrectly

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5919]
These frames are not related to NextJS
<img width="376" alt="Screen Shot 2022-03-22 at 7 36 41 AM" src="https://user-images.githubusercontent.com/254562/159507693-50f71e3f-2af7-4f02-acaf-b23cbc828c1e.png">

https://app.replay.io/recording/nextjs-shown-incorrectly--031ab1a7-2820-4762-9064-00510de91c5e

**Comment by bvaughn** [comment]
So this issue is triggered by Next server static/built JavaScript bundles at a path that includes "_next" – which causes a false positive match with this check:
https://github.com/RecordReplay/devtools/blob/f8181e040956da79a589f885645a29cd609e4cea/src/devtools/client/debugger/src/utils/pause/frames/getLibraryFromUrl.js#L109-L112

I'm not sure what path Next actually stores its own code at. I _think_ it's in `/_next/static/chunks/` vs user code which is at `/_next/static/chunks/pages/`
