### ISSUE TITLE
Comment flicker (part 3)

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6138]
We've identified most of the difficult race conditions with comment flickering. I think the remaining ones are fairly straight forward

1. Comments flicker when transitioning from one draft to another ([replay](https://app.replay.io/recording/comments-flicker-when-replacing-a-draft--17018258-f1fd-49e6-8d9d-78d169a533bf?point=105144011415874916729333207047078683&time=38579.125322516105&hasFrames=true))
2. Comments flicker when toggling sidebar panels ([replay](https://app.replay.io/recording/comments-flicker-when-replacing-a-draft--64c9f59d-0939-43ea-88be-7dfc0442657d?point=41213856331603456710710582096957179&time=29137&hasFrames=false))

In both cases, the problem is that the comment card initially renders without the editor. And then the editor comes in. We can probably handle that one of two ways. the first is to animate in the editor, the second is to not show the comment card until we have the editor. This might cause a similar flicker if we simply flipped it and the editor appeared before the rest of the comment, but I think it could work.

**Comment by bvaughn** [comment]
> We can probably handle that one of two ways. the first is to animate in the editor, the second is to not show the comment card until we have the editor. This might cause a similar flicker if we simply flipped it and the editor appeared before the rest of the comment, but I think it could work.

This general pattern sounds like a great use case for Suspense.

I'm not sure I have an end-to-end understanding of the comment data lifetime though, so I'm not sure yet what to propose for the right caching strategy.

**Comment by jasonLaster** [comment]
ooh - i think this would be great for suspense!

**Comment by bvaughn** [comment]
> This might cause a similar flicker if we simply flipped it and the editor appeared before the rest of the comment, but I think it could work.

I'm not sure what you mean by this FWIW.

---

Jotting down some notes for myself to refer back to tomorrow:

I _think_ the thing that's flickering is the `@tiptap/react` [`<EditorContent>`](https://github.com/ueberdosis/tiptap/blob/main/packages/react/src/EditorContent.tsx) component that's rendered inside of **our** `<TipTapEditor>` component. Digging in a little, I see that `TipTapEditor` is re-rendering a bunch when we add a new comment because of state inside of the `@tiptap/react` internal `useEditor` hook. (There's a "force update" `useState` hook that stores a number that's being auto-incremented [every time there's an Editor "transaction"](https://github.com/ueberdosis/tiptap/blob/5b4f3d634fc0fac6edbc94b1db996ba6255fb93a/packages/react/src/useEditor.ts#L16-L26), whatever that means.)

Looking at the React Profiler UI, I see the following sequence that's causing the flicker being reported:
1. `<TipTapEditor>` mounts with two `<PureEditorContent>` children.
2. `<TipTapEditor>` quickly updates because of [this internal state hook](https://github.com/ueberdosis/tiptap/blob/5b4f3d634fc0fac6edbc94b1db996ba6255fb93a/packages/react/src/useEditor.ts#L12) in `useEditor` and **unmounts the nested `<PureEditorContent>` children**.
3.`<TipTapEditor>` quickly updates again because of [this internal "force update" state hook](https://github.com/ueberdosis/tiptap/blob/5b4f3d634fc0fac6edbc94b1db996ba6255fb93a/packages/react/src/useEditor.ts#L13) in `useEditor` and **remounts the nested `<PureEditorContent>` children**.

**Comment by bvaughn** [comment]
The tiptap `EditorContent` just renders an empty `HTMLDivElement` (with a `contenteditable` attribute) and then on mount/update, it imperatively initializes it.

So then I think the reason for the flicker is this:
1. We unmount the `EditorContent` component.
2. We mount a new `EditorContent` _but when we do_, the inner `contenteditable` HTML is empty.
3. A small amount of time passes (because tiptap has some `setTimeout` and `requestAnimationFrame`?) and then the tiptap `Editor` dispatches an "action" that renders another update. When this update is committed, the React wrapper component _reparents_ the HTML elements from `editor.options.element` into the empty `HTMLDivElement` container it rendered (and that's when we see them).

So in order to avoid the flicker, I think we'd have to either...
1. Not unmount the component in the first place, or
2. Reduce the delay between when it mounts and when it copies over its imperatively-created UI. (Not sure if this one is really feasible.)

I've annotated this happening here:
https://app.replay.io/recording/react-devtools-leftright-arrow-functionality-broken--8a21b88e-71d5-4a7c-8c3b-1bc62621164c

Although at this point, I think I'm mostly just caught up to where Jason was when he filed this issue.

**Comment by bvaughn** [comment]
Stepping back and looking a little further up in the Component tree– the top level "click" event causes our `Transcript` component to update, but then the `CommentCard` underneath of it  remounts (which causes the `TipTapEditor` to remount also).

The Profiler shows the reason for this– a changed `key`:

### Before
![](https://user-images.githubusercontent.com/29597/163024371-f793fffd-0155-484d-8f81-658c08e4a643.png)

### After
![](https://user-images.githubusercontent.com/29597/163024373-76f69201-8e19-4297-91b1-5b7e3cf4d464.png)

Typically React component keys are _ids_. Although our _pending comment_ `id` is "pending" – we use a helper function `commentKey` to create a "stable" identifier for `key` that _isn't_ based on the `id` attribute:
https://github.com/RecordReplay/devtools/blob/9c5f66106c69eec34f10acd8141f2a1d40315b45/src/ui/utils/comments.ts#L43-L58

This _inferred_ key includes things that change between clicks (like the `createdAt` timestamp) – which is what causes the unmount and remount.

**Comment by bvaughn** [comment]
My initial intuition was that like updating the `createComment` action to also clear/reset the pending comment would be sufficient for this, but it seems like the existing `clearPendingComment` really works by nulling out the pending comment (and so triggering the unmount/remount scenario):
https://github.com/RecordReplay/devtools/blob/3839e219dfc5e3ff7c275d682a7069599b70eca0/src/ui/actions/comments.ts#L40-L42

This is basically the [derived state scenario](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#anti-pattern-erasing-state-when-props-change) I wrote about a few years ago on the React blog. Using a `key` to force-reset state was one of the recommendations in that blog post. It's just unfortunate that in this case, it also causes a flicker. 😁

**Comment by bvaughn** [comment]
Okay. I think #6335 has the makings of a pretty good solution to this issue. I'll try to have it ready for review by morning.

**Comment by bvaughn** [comment]
I've captured the Apollo cache issue in a Replay recording (although in this example, the cache does eventually fix itself):
https://app.replay.io/recording/replay-useaddcomment-apollo-cache-race-issue--de94c1ae-bd65-44b9-9de0-d0798ef89f91

Here's another recording with caching weirdness:
https://app.replay.io/recording/replay-useaddcomment-apollo-cache-race-issue-alt--9c1c5476-d732-482c-808e-2fd8f7899402

Anecdotally it seems related to first _deleting_ a comment and _then_ creating a new one. If I load a recording and just add comments, they seem to mostly work.
