### ISSUE TITLE
Upload screen is shown a second time

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6168]
**Description:**
I've not been able to repro this while recording a replay, but have seen this a couple of times today.

STR:
1. save a replay
2. set the replay to public in the upload screen
3. click save

ER: go to replay
AR: redirected t the upload screen

**Comment by jasonLaster** [comment]
Here's a 3 minute video of me failing to repro
https://www.loom.com/share/74c7871941af4a6fb776b139bd830425

**Comment by jaril** [comment]
Saw this today too. Will keep an eye on it :/

**Comment by jaril** [comment]
Found it! https://app.replay.io/recording/double-upload-screen--28ad79a7-c964-49a5-bd48-de9983e9138d

**Comment by jaril** [comment]
Didn't see it. Closing this. Might open again we'll see…

**Comment by jaril** [comment]
Spoke too soon. Just saw it in the Replay browser. It might be a coincidence, but what happened was that I recorded a replay, was waiting for the upload screen so I tabbed away, and then came back to it ~2 mins after and hit upload. That's when the bug happened.

Opening that replay (without hitting the upload button again) seems to not bring you back to the upload screen again. Which makes me think that it's not a database-related problem.

**Comment by jaril** [comment]
There's a second navigate event being called out in the console. Something's making that page navigate before the finished-uploading state is persisted in the database so it ends up showing the upload screen again. 

<img width="482" alt="image" src="https://user-images.githubusercontent.com/15959269/162575843-6bc6afb5-7b6d-4544-909b-daa1d1fc4379.png">

**Comment by jaril** [comment]
Just figured it out. When you change the name and hit upload, the URL changes:

`https://app.replay.io/recording/old-title--e98b52c0-4d5e-4eb9-ada2-9f94c84ddf35` ->
`https://app.replay.io/recording/new-title--e98b52c0-4d5e-4eb9-ada2-9f94c84ddf35`

When that happens, looks like something kicks off a re-render of the top-level routing. That resets the state for the upload screen's parent, which is keeping track of whether or not you've clicked "Upload" already. Since it doesn't know whether you've done that yet, it shows it to you again. 🤦‍♂️
