### ISSUE TITLE
Flickering in the recording/…/share routing

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6229]
Check out this Replay:
https://app.replay.io/recording/replay-of-a-replay--8ccec6d3-9d89-40a4-b379-efd6337ee19f?point=46406153187993451429831749081761164&time=30942&hasFrames=false#

It's technically possible to complete this task, so it's not 100% broken ... but it definitely feels like things are very wrong. From a UX/onboarding standpoint, this is high importance to fix and get right.

**Comment by jaril** [comment]
Filling in more details:
- This flow is used in the [Request Access flow](https://github.com/RecordReplay/devtools/issues/5163). User B requested access from User A, so User A gets an email with a link to the recording with an appended `/share` at the end of the URL.

To reproduce, append `/share` after the plain URL for a replay, e.g. `https://app.replay.io/recording/replay-of-a-replay--8ccec6d3-9d89-40a4-b379-efd6337ee19f` -> `https://app.replay.io/recording/replay-of-a-replay--8ccec6d3-9d89-40a4-b379-efd6337ee19f/share`.

Needs some more digging to figure out what's happening here.

**Comment by jaril** [comment]
This looks like this is happening because of the routing that we do in the `/share` route.

https://github.com/RecordReplay/devtools/blob/2e4fed4acd331a1804644fc7a74c4b34b7e945d4/pages/recording/%5Bid%5D/share.tsx#L11

Maybe routing is not the right way to do this since we can't avoid the flickering otherwise.
