### ISSUE TITLE
Comment sticks around

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6233]
Check this out:
https://app.replay.io/recording/adding-comments--d4afaf63-1766-4281-a0ef-b06e03e41a19?point=100925270199248397248981589133626899&time=34817&hasFrames=false

<img width="527" alt="image" src="https://user-images.githubusercontent.com/9154902/162846966-66b06b40-cea4-4b0e-82d7-0f0e89ce13d2.png">

In this example I wrote "Hello" in the comment field and hit enter. Then I hit enter again. But the comment never successfully sticks. It just sits there in edit state.

**Comment by jonbell-lot23** [comment]
Updated, thanks!

**Comment by bvaughn** [comment]
This looks to me like the same bug as #6502 (which I just dug into).

There is a problem in the way the frontend tries to hand off the pending comment from Redux to Apollo when saving:
https://github.com/RecordReplay/devtools/blob/d187caadf0932c485eebb0316a8ba7355b3130a9/src/ui/hooks/comments/useAddComment.tsx#L32-L93

What ends up happening is that there is a copy of the pending comment in the Apollo cache (that doesn't get removed) and then we also add the newly-saved pending comment to that cache as well. This creates visual duplicates and leaves the input field hanging around still visible (because the UI chooses whether to render the new comment input or not based on the magic "PENDING" id).

PR #6335 refactors this logic and should fix this issue along the way, so I'm going to roll this into that.

**Comment by bvaughn** [comment]
Closed via #6335
