### ISSUE TITLE
Better error handling so figuring out who to talk to internally is more clear

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6246]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/15959269/162226884-23ca09d9-38da-4884-a755-cfcd3bcdabd8.png">

We often get error screenshots from customers. Usually it falls on @ceceliacreates to field those inquiries. But then she has to send a general "anybody knows what's up with this bug?" to everybody since it's not narrowed down at all.

There's a version of this where the user's session would be trackable and we can take a look at some error info in the console that would at least narrow down who should be pinged about that error. But afaik that's fairly unreliable.

A simple fix might be to just add the error code in the error message. In this case, `There was an error. Please try recording again.` corresponds to backend code that looks like it's labelled `SessionError.UnknownFatalError`. So just having that information visible in the screenshot would make the initial conversation with the user informative, and reduce some back and forth in Discord.

**Comment by gideonred** [comment]
I am definitely a fan of making somewhat clear where an error came from (in this case the Frontend knows it wasn't the problem and it was the Agent reporting an error back).

We don't necessarily have to expose that to the end user, but we must expose that in Honeycomb. At the moment when devtools gets these problems it doesn't tell Honeycomb much.

Since yesterday this dashboard has helped a lot: https://ui.honeycomb.io/replay/board/p8rzMqyFdwL/User-Fatal-Errors . And we're seeing our users show up in there when the report errors. I'm writing a playbook that anyone can use to then narrow down where the cause could be.

**Comment by jaril** [comment]
Since filing this we've had better info in the user fatal dashboard, so closing this for now:

https://www.notion.so/replayio/User-Fatal-Dashboard-9a0e53a6850d449e96ec6d17563efad5
