### ISSUE TITLE
Unloaded regions not showing on timeline

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6289]
In the replay below, unloaded regions are not shown correctly on the timeline.

https://app.replay.io/recording/loaded-regions-not-showing--ba3e6c6e-a062-46a4-be11-ea7bb7d30908?point=33749929584389312161735533083492352&time=27080&hasFrames=false#

**Comment by jaril** [comment]
Good catch — it's not. The UI's not currently doing anything with the unloaded regions in the timeline.

https://github.com/RecordReplay/devtools/issues/5851#issuecomment-1083240804

It used to be that we would differentiate the loaded vs unloaded regions in the timeline. In that case, regions that have been unloaded by the backend would be obvious because those regions would be shown as unloaded, even though all the other unloaded parts would go from unloaded->loaded. We took that out with the intention of indicating the [loading vs unloading* regions in the timeline](https://github.com/RecordReplay/devtools/issues/5851#issuecomment-1083240804). 

Problem is, we didn't do anything to replace it so right now all of that information is being lost and not expressed through the UI. So there's no indication to the user that parts of the recording have been yanked away by the backend. 

Gonna pull in @jonbell-lot23 for a quick brainstorm later and figure out how we want to address that.

_*The terminology gets a bit fuddled, but in this case, "loading" refers to regions that the backend is intending to load. So, non-loading regions are parts that either the user 1) told the backend to not load via focusing, or 2) the backend decided to unload by itself._

**Comment by jaril** [comment]
@bhackett1024 The best thing to do here (at least in the short term) depends on what the default backend behavior is.

The terms are a bit confusing but for the purpose of this thread, let's say that "loaded"/"unloaded" refers to the `loading` region. So unloaded means that it's not a part of the `loading` region and the backend has no intention to load that span. This is different from the actual use for the `loaded` namespace, which is some subset of the `loading` regions that the backend has loaded.

- Once a region is unloaded, is there some situation in which that region will be loaded again (without user input)?
- Are there some general patterns around how the backend decides which parts of the recording to unload? For example, is it generally closer to the beginning or the end? Or maybe it's just not predictable?
- Is there a duration (e.g. 10s/20s/30s) that, if the user only loaded that much of the recording via focusing, we can guarantee that the backend won't need to unload any parts of the recording?
- Is it possible to recover from a situation where the backend unloads a region without user input? Imagine that there's a 100s replay and the backend chooses to unload the first 90s. Say that the user knows that they're interested only in the first 10s. If that user then focuses such that only 0-10s were loaded, will the backend accommodate that request? Can the user still debug the part that they're trying to debug?

**Comment by bhackett1024** [comment]
>     * Once a region is unloaded, is there some situation in which that region will be loaded again (without user input)?

No.

>     * Are there some general patterns around how the backend decides which parts of the recording to unload? For example, is it generally closer to the beginning or the end? Or maybe it's just not predictable?

Unless part of the recording has been explicitly loaded using the focusing tool, unloaded regions will be earlier in the recording.

>     * Is there a duration (e.g. 10s/20s/30s) that, if the user only loaded that much of the recording via focusing, we can guarantee that the backend won't need to unload any parts of the recording?

When using the long recording support option, currently we guarantee that a minimum of 60 seconds will be loaded regardless of the recording complexity.  Without that option, there isn't a minimum amount we can guarantee we'll load.

>     * Is it possible to recover from a situation where the backend unloads a region without user input? Imagine that there's a 100s replay and the backend chooses to unload the first 90s. Say that the user knows that they're interested only in the first 10s. If that user then focuses such that only 0-10s were loaded, will the backend accommodate that request? Can the user still debug the part that they're trying to debug?

Yeah, when the user uses the focus tool to select part of the recording, the backend will load that part (and only that part) if it's small enough.

**Comment by jaril** [comment]
> > ```
> > * Once a region is unloaded, is there some situation in which that region will be loaded again (without user input)?
> > ```
> 
> No.
> 
> > ```
> > * Are there some general patterns around how the backend decides which parts of the recording to unload? For example, is it generally closer to the beginning or the end? Or maybe it's just not predictable?
> > ```
> 
> Unless part of the recording has been explicitly loaded using the focusing tool, unloaded regions will be earlier in the recording.
> 
> > ```
> > * Is there a duration (e.g. 10s/20s/30s) that, if the user only loaded that much of the recording via focusing, we can guarantee that the backend won't need to unload any parts of the recording?
> > ```
> 
> When using the long recording support option, currently we guarantee that a minimum of 60 seconds will be loaded regardless of the recording complexity. Without that option, there isn't a minimum amount we can guarantee we'll load.
> 
> > ```
> > * Is it possible to recover from a situation where the backend unloads a region without user input? Imagine that there's a 100s replay and the backend chooses to unload the first 90s. Say that the user knows that they're interested only in the first 10s. If that user then focuses such that only 0-10s were loaded, will the backend accommodate that request? Can the user still debug the part that they're trying to debug?
> > ```
> 
> Yeah, when the user uses the focus tool to select part of the recording, the backend will load that part (and only that part) if it's small enough.

Got it, thanks!

For my reference:
- It's possible for the backend to choose not to load regions without any user input.
- When that happens, the video is still playable, but experience around features like analysis (e.g. hits, console evaluations), network requests, DOM elements (maybe?) will be broken/unavailable. 
- If the user is planning to do any serious debugging, I'd be nervous that the UX will feel broken.
- There is a way for the user to get out of this situation, which is by focusing on a smaller part of the recording where it's less likely for the backend to choose not to load regions, i.e. smaller region of the recording.
- Provided that they focus correctly, and that the user has high confidence that the selected focus region they've selected contains all of the relevant information they need, then it's possible to correct the experience and still have a successful debugging session.

**Comment by jonbell-lot23** [comment]
Hey @jaril here's what I'm seeing:

* If we can assume 1 minute is a non-crazy default...
* And we know things are broken when they're unloaded...

Then you should not be able to click into unloaded regions without messaging. When you attempt to, we should throw a customised Focus Mode dialog that says "This Replay is too large, please select a region to focus on." And that selection state should default to one minute.

That means we have a crystal clear boundary between things that work and things that don't work, visually-speaking. And crystal clear messaging about why it's happening because of the copy. And a crystal clear way to resolve it via our Focus Mode set to one minute.

How does that sound?

**Comment by jonbell-lot23** [comment]
Good chat with Jaril today, so moving to design-complete
