### ISSUE TITLE
Comment field sometimes doesn't gain focus

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#6364]
Had a customer re-report #6136. I think the root cause was that the comment field wasn't gaining focus as expected so they started typing as they usually would but since the field isn't focused the keyboard shortcut did its thing.

https://app.replay.io/recording/replay-involuntary-theme-change--4b0f6127-57e1-4fe1-8e37-b74ed43111ee

**Comment by jaril** [comment]
Did a bit more investigating but couldn't get far because of sourcemap issues. Left a comment in the replay. As far as I can tell the way we tell the editor to autofocus as it's rendered is working correctly (autofocus = true being passed into TipTapEditor). But for some reason it doesn't focus the editor's input. Will keep investigating!

**Comment by jasonLaster** [comment]
I think we can safely close this
