### ISSUE TITLE
Clicking is disabled on add print statement button for line with a breakpoint

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6407]
[Replay of the bug](https://app.replay.io/recording/breakpoint-disables-print-statement-button-bug--7f072f14-9327-440d-a022-e448b71fc9ce)

https://user-images.githubusercontent.com/15959269/163583338-1c357748-b7af-40e3-b518-255a55ce3dfd.mov

**Comment by bvaughn** [comment]
I assume also related is– if I have a print statement on a line, and I click to add a breakpoint, it seems like my print statement gets erased/reset. (This is unexpected because I lose any modifications I'd made to it.)

Replay: https://app.replay.io/recording/replay-breakpoints-erase-print-statement-content--e6a9acd1-235b-4a1b-9d48-2cc99e8efb30?point=103845937181064862130652146953103995&time=35314&hasFrames=false
