### ISSUE TITLE
Problems entering comments

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6502]
In the replay with comments below I had several problems trying to enter and delete comments.

https://app.replay.io/recording/comment-problems--dc95a6e4-4ec3-4a08-9150-27a6573f0668?point=333929591741916826111099956837233288&time=116134&hasFrames=false

**Comment by bvaughn** [comment]
Requested access to the replay.

**Comment by bvaughn** [comment]
Out of curiosity, why does this replay not seem to have source maps?

**Comment by bvaughn** [comment]
Summarizing here: After your first comment is added "successfully" (it appears multiple times in the UI but it _does_ at least get created)– the backend rejects subsequent new comments with a 500 status because the frontend isn't sending a `recordingId` value:
> Field \"recordingId\" of required type \"ID!\" was not provided.",

Looking at the recording, I think the thing that's going wrong has to do with the way the frontend is managing pending comments in Redux and then trying to hand them off to Apollo state on save. The bug seems to be in our optimistic mutation code that temporarily stores the "pending" comment in the Apollo cache until the real one comes back:
https://github.com/RecordReplay/devtools/blob/d187caadf0932c485eebb0316a8ba7355b3130a9/src/ui/hooks/comments/useAddComment.tsx#L32-L93

What ends up happening is that there is a copy of the pending comment in the Apollo cache (that doesn't get removed) and we also add the newly-saved pending comment to that cache as well.

PR #6335 refactors how this stuff works so I'm leaning towards leaving this issue sit until that PR lands.

**Comment by bvaughn** [comment]
Closed via #6335
