### ISSUE TITLE
Tabs overflow shouldn't be ellipsis-ized

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6504]
When tab file names overflow in the editor, we currently handle the overflow with ellipsis. We should just let it get clipped so that we're not wasting valuable real estate. This is in line with what VS Code does.

Us:
<img width="480" src="https://user-images.githubusercontent.com/15959269/164499859-aff8f063-34f3-4647-9ae5-051dec9c97ef.png" />

VS Code:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/15959269/164500071-b7a89aeb-fc47-4495-830d-9eab5ceeab8d.png">

**Comment by bvaughn** [comment]
Agreed that VS Code wastes less space here, but I think the bulk of that is because they don't pad on the right side of the tab (and we do). The ellipsis take up extra space so we should probably remove them too, although that looks kind of broken. I wonder if we could show something (alpha gradient on the right side maybe?) so the clipped names are more obviously clipped?

**Comment by jonbell-lot23** [comment]
I support @jaril 's original idea but also like the nuance @bvaughn is bringing up. Even without the gradient fade I'd be fine with that tradeoff.

Like the direction, will follow along!

**Comment by bvaughn** [comment]
Here's my counter proposal (that mimics VS Code)
https://www.loom.com/share/8f93bc1048b047888619a1ccc3e77f9d

**Comment by bvaughn** [comment]
And here's one with the faded overlay:
https://www.loom.com/share/e5b8a8a1e37b42f6a788d19d48fed816
