### ISSUE TITLE
Unable to change default workspace to "Your Library" on upload screen

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#6538]
<img width="753" alt="Screen Shot 2022-04-22 at 3 46 18 PM" src="https://user-images.githubusercontent.com/132260/164815002-b05f249d-b193-4d5d-8c82-567b337e1690.png">

We've regressed this before, can we please fix this UI so IDs and UI strings never overlap?

**Comment by loganfsmyth** [comment]
I assume the issue here is that https://github.com/RecordReplay/devtools/blob/3ccd585328fbeca847ad0ff7a1d356820daf572c/src/ui/components/UploadScreen/Sharing.tsx#L34 should be using the `MY_LIBRARY` constant, which means this regressed in https://github.com/RecordReplay/devtools/pull/5304 which also means it's been broken for 2 months.

We definitely also need to figure out why this error isn't being reported to Sentry

**Comment by ryanjduffy** [comment]
Replay that confirms @loganfsmyth 's theory and points out why this didn't hit sentry.

https://app.replay.io/recording/upload-screen-error-when-selecting-my-library--ce147d99-217c-47e4-908f-5c06c7d0e5fa

The sentry change was intentional but worth debating so i'll open a pair of PRs so we can land a fix for this bug separately from the sentry discussion.
