### ISSUE TITLE
Viewing later parts of loading recording shows wrong graphics

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6546]
When the graphics from the backend haven't fully loaded, clicking on the timeline in later parts of the recording shows images from earlier parts, presumably the last loaded paint.  We should be showing a "loading" indicator or something instead.  I haven't been able to get a recording of this yet.

**Comment by bhackett1024** [comment]
Here is a replay of the problem with comments:

https://app.replay.io/recording/wrong-graphics--e23a115c-aed0-410b-b74c-c523e117668f?point=122668013301792288450695562279259415&time=49139&hasFrames=false

**Comment by jcmorrow** [comment]
So this is an interesting one. I'm curious what others think we should do here. Here's how the current logic is flawed:

- When the user clicks on the timeline, we know the timestamp of that click, but we don't immediately have a `point` to accompany it. Instead, we look backwards in time at our most recent paint or mouse event. Then (I think this is how it works) we create a pause at that point and query the `DOM.repaintGraphics` protocol method. This works when the recording is loaded. When the recording is *not yet* loaded, however, you can imagine the following scenario:
	- We are trying to load a 2-minute long recording. So far, we have successfully loaded the first 45 seconds.
	- The user clicks on the timeline at the 1:45 mark. If we run our algorithm, it will return us the most recent paint or mouse event, which will have happened during the loaded period, a full minute before when the user clicked on the timeline.

Now, there are different things that *could* happen, but here's what I think might be a good take:

- Let's assume there is a global loading promise manager, which you can ask for a promise that resolves when either a span of the recording or a particular point in the recording is loaded.
- When the user clicks on the timeline, we await a promise for the current time, and we show a blank canvas (or something else that strongly suggests that the video for this point is not ready - I don't think our current corner spinner cuts it here).
- When that promise resolves, we run the above algorithm, or, if the user has already moved somewhere else, we bail.

I think we need that global loading promise manager anyways for other stuff, and I think it's pretty straight-forward to make, which is why I am putting it in here as an assumption.

Are there other things we should consider here?

**Comment by markerikson** [comment]
Hmm. I actually did something _sorta_ like this, once upon a time.

In our case: we had a pseudo-VCR-type UI, with "Play/Pause/FF/Rewind" buttons for animating a sequence of highlighting points along a polyline on a globe, with a delay of 3-ish seconds per point.  What this was actually showing was "Line of Sight for each point, in turn".  Showing LOS for a point required a 2-3 second calculation on the backend to ensure the PNG was generated, and returned a final image URL.

When the user hit "Play", we'd send off an initial batch of 5 calculation requests.  By the time point 2 needed to be shown, the rest of points 1-5 were calculated and we had the URLs on the client (and could even potentially pre-fetch them).

If the user hit Pause, and then started dragging the slider around, things got tricky. We had to cancel any outstanding requests, and jump ahead to start calculating a new batch at the time where they stopped dragging the slider.

This _feels_ like it's much the same problem.

FWIW, I originally implemented this logic using Redux sagas, because they were good for cancellation / debouncing / etc.

Today, I might try reaching for the new Redux Toolkit "listener" middleware, which can do most of the same things sagas can but with a simpler API, to manage the "what requests are outstanding" logic.

However, for the _display_ purposes... I almost wonder if React Suspense would help here?

So yeah, we can figure out the actual mechanics that are needed, but some kind of a global cache that maintains the status of each possible fetched image is _probably_ roughly what we want here.

**Comment by jcmorrow** [comment]
We have pretty good cache management when it comes to fetching the paints. I think the core problem is that we don't know what point to request a paint for until that part of the recording has loaded.

**Comment by jcmorrow** [comment]
If, for instance, the whole recording were loaded, we have `prefetchScreenshots` which will do basically what you just described above.

**Comment by markerikson** [comment]
Ah. as in, we literally don't get any of the `"1234567890"`-type point strings until that region is loaded and available?

That... does make it trickier :)

**Comment by jcmorrow** [comment]
Exactly, those come attached to resources that we find in the recording (like paint events or mouse events).

**Comment by jcmorrow** [comment]
Huh... if we only somebody had done some work a few months ago to make sure that of the basic processing resources paints would come back the fastest 🤦  I swear 3 months is like a year in Replay time. Anyways, that's probably a better solution, let's stop using `repaintGraphics` when we haven't even loaded the recording yet, and instead call `precacheScreenshots` starting at the point the user asked for? (Do we actually have to ask for some time *before* when they asked for so we don't accidentally render the future? Eh... I'll worry about that later).

**Comment by jcmorrow** [comment]
Yeah, so looking through at least the recording up top, the problem is that we just don't have the paints for that late in the recording yet, and so instead we show the latest ones that we have. Even though we are trying to get them as fast as possible, they just haven't come in yet in this case.

**Comment by jcmorrow** [comment]
I think a reasonable thing to do would be to not render a super old screenshot, and instead wait until we have paints for that point in the video. I could see a slick thing being something like:

If we are rendering a previous paint point, apply a blur filter that is proportional to how far away it is from the current time, and then update as we get closer, so it's clear that the video is catching up.

**Comment by jcmorrow** [comment]
Also similarly, the events that are coming in on the left bar are all from the beginning of the recording, even though the client says it's trying to load the last minute.

**Comment by jcmorrow** [comment]
@bhackett1024 I'm curious what your opinion is here. Let's say that you knew when loading the recording that kicked off this issue that we only had paint data for 22 seconds into the recording, when you clicked at the 35 second mark, what would you have preferred to happen? Do you think you would have been less surprised if we had moved the timeline forward but not shown any graphics?

**Comment by jcmorrow** [comment]
It's pretty easy to make the change of "Don't show graphics if the user is past the end of the currently loaded paints and we are still getting paints in from the backend", so I'm happy to make that change, but I want to make sure we all agree that would be an improvement.

**Comment by jcmorrow** [comment]
Actually, just spelunking through some comments, I see this:

https://github.com/RecordReplay/devtools/commit/1490cfce3f365852757d4e9078fd7e68fe0ad3ef#diff-0b3b6041213ad0d8eec8fbfb5111600076ab4ab1178b839e802d76a4e8e44689R193-R197

```
      // Seek to the exact time provided, even if it does not match up with a
      // paint event. This can cause some slight UI weirdness: resumes done in
      // the debugger will be relative to the point instead of the time,
      // so e.g. running forward could land at a point before the time itself.
      // This could be fixed but doesn't seem worth worrying about for now.
```

So it seems like we have known that this could cause some bugs for a long time (I'm actually surprised I didn't realize how problematic our seek behavior was before this). Anyways, I'm all for making this better, but it's taken up a lot of my time yesterday and today, so I'm going to punt it to next sprint for now (and maybe we decide to come back to it even later).

**Comment by jcmorrow** [comment]
https://www.loom.com/share/fcdfddf52a43464dae6e864634692e94

**Comment by jasonLaster** [comment]
@jcmorrow yep i think this is related to https://github.com/RecordReplay/devtools/issues/4289 which i just moved into next sprint.

**Comment by jasonLaster** [comment]
@jcmorrow where is this at?

**Comment by jcmorrow** [comment]
I just haven't written the part where we actually use https://github.com/RecordReplay/backend/pull/5565! I think this is actually very easy, so I'll give it a quick shot, and if I don't have it in half an hour I'll just leave some comments for somebody else to pick up tomorrow!
