### ISSUE TITLE
Focus Window modal 🔫 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6706]
https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=12025%3A76141
https://www.loom.com/share/33bbeae6bdcf4e448a1ce33e384a7f81

**Comment by bvaughn** [comment]
Eagerly claiming this one because I'm excited to work on it once @jonbell-lot23 signs off :)

**Comment by jonbell-lot23** [comment]
Yup @jasonLaster @bvaughn now that we've graduated to having proper save/cancel buttons, clearly this is The Right Answer.

There may be some gotchas but yeah, let's gooooo

**Comment by jonbell-lot23** [comment]
I see the Loom mentioned asking for feedback around designing the thing. We do need the new icon in there, but otherwise this feels like what I would do.

I'd also dim the upper region the slightest little bit, like 5%, because it still is a mode, and it's good to visually announce when you're between different modes. 5% dim should do it.

**Comment by jasonLaster** [comment]
@jonbell-lot23 could you help w/ the visuals here?

**Comment by bvaughn** [comment]
Happy to pick this up and run with it at any point btw. (Happy to make up visuals as I go for v1)

**Comment by bvaughn** [comment]
I'm going to take a pass at this. Don't need final graphics/visuals yet. Can get the basic stuff in place with what we have in the Figma :)
