### ISSUE TITLE
Comment ordering

### ISSUE THREAD

**Issue by bvaughn** [RecordReplay/devtools#6720]
Comments should be sorted by their time/point (relative to the recording timeline) but they seem to be sorted by the order they are authored in.

Loom: https://www.loom.com/share/859f60155ba744e8b566fe67a54043dc

Replay: https://app.replay.io/recording/timeline-comments-out-of-order--a3950982-c932-4860-acd9-9f49008b1f29

**Comment by Andarist** [comment]
Hmm, this is actually interesting to me - I've been commenting on this in the past. Maybe the proposed approach is better but I wonder if it's the ideal one. Comments could "form a story" but that is not always progressing in the same way as the timeline. It's another timeline. Of course, maybe that's not the use case worth implementing but at times I've wished that I could reorder comments.

**Comment by bvaughn** [comment]
User re-orderable comments also seems like a nice feature 👍🏼

**Comment by hbenl** [comment]
This was caused by #6728: comments are ordered by `point` and all comments received the same `point` because it was never updated by a Timeline click. This became more confusing due to #4289: the Timeline is actually lying to the user because it uses a `time` that can be different from the `time` that corresponds to the current `point`.
