### ISSUE TITLE
Replay crashes when viewing a recording

### ISSUE THREAD

**Issue by bvaughn** [RecordReplay/devtools#6777]
https://app.replay.io/recording/replay-crashes-when-viewing-recording--56790160-a8d1-45f1-b030-3cdfa560c104

Saw this while trying to record [a Loom demo](https://www.loom.com/share/c4217f31400d4542a77fda8d19815b93) this morning.

**Comment by jasonLaster** [comment]
@bvaughn what iteration do you think makes sense?

**Comment by bvaughn** [comment]
I put it into the next one. Crashes are bad.

**Comment by jaril** [comment]
Tried to investigate quickly in honeycomb by checking events for that `sessionId` but got nothing:

`7b885c1e-e463-41ae-8a19-4eff523ffb66/f31de4b2-5804-417e-b813-ee18ff4d946a`
https://ui.honeycomb.io/replay/datasets/backend/result/ohFTC4yNfRx

@gideonred As far as the frontend's concerned, it _thinks_ that the session has been created since we get a sessionId back. Any thoughts on how to investigate this further?

**Comment by gideonred** [comment]
The backend has crashed several of BrianV's sessions (first graph of go/usererror): https://ui.honeycomb.io/replay/datasets/backend/result/9dywGwovgAf

Unfortunately in the above metric we don't report recordingId (but I think I'll still be able to tell what's going on).

**Comment by gideonred** [comment]
Per the playbook at top of go/usererror, I was able to find the bug this replay ran into:

https://ui.honeycomb.io/replay/datasets/backend/result/zumpjcJsPKY/a/xsuXLJav6ee

This is https://github.com/RecordReplay/backend/issues/473

**Comment by gideonred** [comment]
Since https://github.com/RecordReplay/backend/issues/473 will be tracking the fix, feel free to close this in favor of that.
