### ISSUE TITLE
Backend is getting protocol commands with missing pauseIds

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#6814]
Here's a list of protocol commands that failed because devtools failed to include pauseIds:

https://ui.honeycomb.io/replay/datasets/backend/result/4JYBLFxVvDs

I believe this is a bug on the frontend side.

**Comment by gideonred** [comment]
I agree it's probably not the biggest problem, if it is a quick fix, let's for it. Otherwise, we can reprioritize. Thanks Jaril!

**Comment by jaril** [comment]
Considering it lower priority since it happened <5 times in the last week.

But it looks like it's possible for the backend to send a message or an analysisResults that's missing a pauseId:

https://github.com/RecordReplay/devtools/blob/0ce5639bec4ddaeae11c2aa5f4058b48c63cd3fd/src/protocol/logpoint.ts#L76
https://github.com/RecordReplay/devtools/blob/e89eceb68ea8d9c16db7c348bebe16220e9cbd81/src/protocol/thread/thread.ts

Could go deeper but filing it off for now to prioritize on other things unless we see this crop up more often. That said, I'm replacing the TS assertion with an actual `assert()` call so we can see this pop up in honeycomb.

**Comment by markerikson** [comment]
@jaril fyi I did just refactor `Pause` to take a `ThreadFront` as its argument - previously it was taking a `recordingId` or `sessionId` or something like that.  However, pretty sure it was _not_ getting a `pauseId`.

**Comment by jaril** [comment]
> @jaril fyi I did just refactor `Pause` to take a `ThreadFront` as its argument - previously it was taking a `recordingId` or `sessionId` or something like that. However, pretty sure it was _not_ getting a `pauseId`.

Yeah that appears to have been not connected. Unless I'm missing something—let me know!

**Comment by jcmorrow** [comment]
I'm guessing that some of this might have been resolved by the pause stuff I've been doing over the past week or two.

**Comment by jcmorrow** [comment]
For instance: https://github.com/RecordReplay/devtools/commit/85e046b8d08bfd7f915d65b08f65a6cfe7d36824 should fix some, and https://github.com/RecordReplay/devtools/commit/a303c248836722afde84d135a423a379115d373c should fix others. It's still theoretically possible to run into this, but it should happen way, way less.

**Comment by jasonLaster** [comment]
should we close and re-open when we have a small repro or are ready to implement an architecture fix?

**Comment by gideonred** [comment]
I'll close for now. Happy to re-open **when** I see it again 😉
