### ISSUE TITLE
"0 hits" everywhere

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#6869]
I have a recording where the Outline panel shows "0" for all functions in all sources and the tooltip shows "0 hits" for all lines in all sources.
This recording shows the issue: https://app.replay.io/recording/0-hits-everywhere--780fef9c-6db6-4c74-991c-b86bb0c3111e
The underlying recording (from a failed e2e test that I was investigating): https://app.replay.io/recording/replay-of-devtools-nf5vxx1f2-recordreplayvercelapp--c4f37d8f-a971-41b6-9e0e-9151e751473d
Perhaps this is triggered by the backend unloading the first part of the recording.

**Comment by jaril** [comment]
Yeah this looks like expected behavior. My guess is that those hits are from the unloaded part. Focusing on that area fixes the problem.

What's interesting to me that the backend predictably unloads that first region consistently. 

There's not much we can do here since the backend is just doing its own thing (unloading). I suppose in this situation it would have been nice to have better messaging so that, if you were actually interested in the unloaded regions, the devtools would make sure it's unmistakable that you'd have to edit the focus to that part.

@jonbell-lot23 thoughts??

**Comment by jonbell-lot23** [comment]
I don't have a design prepared, but there's a *concept* that is very much in the radar and gathering speed:

Any place where you're missing things due to unloaded content, we need to show it. This applies to this issue, but also console, network monitor, etc. stay tuned for more on this soon.

cc @jasonLaster

**Comment by jasonLaster** [comment]
@jonbell-lot23 hit data from breakpoints or really anything analysis based comes from `indexing` which would be unloaded. This is different than resources which cme from basic processing.

**Comment by jonbell-lot23** [comment]
That's my understanding, and pretty sure that's what I said.

I said: "Any place where you're missing things due to **unloaded content**, we need to message it."

You said "hit data from breakpoints or really anything analysis based comes from **indexing which would be unloaded**."

We're saying the same thing here, yes?

**Comment by jasonLaster** [comment]
Hmm - i'm not sure. The distinction is that with resources (console logs) we can say 23 have been unloaded, want to reload them? With indexed data we dont know how many have been unloaded.

@jcmorrow and I have discussed future work to fix that, but that is the current state of affairs.

**Comment by jcmorrow** [comment]
> The distinction is that with resources (console logs) we can say 23 have been unloaded

Well, we can only say that because we loaded them before we unloaded them. Technically, we could do the same thing for analyses. When the work that @markerikson is doing on analyses is complete, they will (or will soon) work the same way that console messages do - if ever we load the entire recording's hit record for those points, we will no longer need that indexed data to still be loaded in order to tell you how many you are "missing". However, just like console messages, we don't know what we don't know, so if that region has *never* been loaded (or if console messages have overflowed) we cannot tell you how much you are missing, because if we could you wouldn't be missing it 😉 .

**Comment by jcmorrow** [comment]
My understanding was that involuntary unloading would be much less common now that we are using turbo replays, because each 30-second set of regions should theoretically be on its own controller. I'm surprised we've still been seeing this auto-unloading behavior.

**Comment by hbenl** [comment]
> My guess is that those hits are from the unloaded part. Focusing on that area fixes the problem.

No, there are hits in a loaded region, as you can see when you click on the last comment in the recording (I forgot to mention this in the issue description).

**Comment by jaril** [comment]
@hbenl thanks for clarifying! Missed that the first time, got it now.

@jcmorrow this looks like the heatmap hit count is returning 0 for line 44, which is not at all what I expect since it appears that there's 4 hits that's within the loaded regions. Made a [loom here](https://www.loom.com/share/8d349cd259aa45f7a45b65ffc561c36b), mind letting me know what you think??

**Comment by jcmorrow** [comment]
I missed this comment, sorry @jaril. I think you are close to something, gonna pick up where you left off!

**Comment by jcmorrow** [comment]
This is definitely a backend bug. Going to move over to that repo.
