### ISSUE TITLE
It should be possible to upload sourcemaps

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#692]
At the moment, we only have sourcemaps when a file references them, which is often in local development. 

This is a big limitation for many places where:

1. Our customer support person doesn't use a non-minified environment
2. Local dev doesn't use things like production react, so a lot of performance characteristics are different there

It would be nice if there were an easy way to add a sourcemap after the fact

**Comment by jasonLaster** [comment]
Sentry makes it easy to upload the sourcemaps during build which is nice

https://docs.sentry.io/platforms/javascript/sourcemaps/
https://docs.sentry.io/cli/releases/#sentry-cli-sourcemaps
https://docs.sentry.io/clients/javascript/sourcemaps/

**Comment by bhackett1024** [comment]
The main issue here is that the protocol commands for uploading source maps currently require a specific recording --- we don't have a way to upload source maps and associate them with recordings after the fact.  That wouldn't be hard to add, and the reason I didn't do so earlier is that without user accounts the only real implementation option is to associate the source map with any recording that includes the map's generated sources.  That isn't exactly desirable --- people making recordings of a public website could get access to the original sources if the source map had been uploaded by someone else.

Now that we have user accounts, we should be able to upload source maps but lock them so that they can only be accessed by certain users.  Then, when one of those users visits a recording we see if we have any source maps which that user is allowed to access and which applies to a generated source in the recording.

**Comment by jasonLaster** [comment]
Moving this request to canny so we can track it along side other feature requests

https://replay.canny.io/admin/feedback/feature-requests/p/upload-sourcemaps?boards=feature-requests
