### ISSUE TITLE
[Console] Show timestamps by default

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#719]
One way we can experiment with the jump button being more prominent AND the console feeling more like a timeline is to make a trimmed down timestamp (MM:SS) the default

<img width="446" alt="Screen Shot 2020-09-24 at 11 41 47 AM" src="https://user-images.githubusercontent.com/254562/94187001-3b168780-fe5c-11ea-80f2-7847c38b5e28.png">

**Comment by jaril** [comment]
Adding notes here from my conversation with Janelle.
- She preferred navigating through logs instead since it's easier to click, but said that the seek click behavior should be more obvious. This can be done by making the seek button pop up, or highlighting the entire message.
- She would have liked to see that clicking anywhere in the message would act as a seek action.
- We should add a reason for why you're paused on the right (e.g. logpoint, event logpoints, error, warning) and make it more explicit (e.g. This is here because you added a logpoint on script.js:32).

**Comment by jasonLaster** [comment]
@jaril after your changes i dont think we need the timestamps.
