### ISSUE TITLE
[Debugger] Maximum call stack size exceeded for `setInScopeLines`

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#766]
https://sentry.io/organizations/replay/issues/1869134419/?project=5399075&query=is%3Aunresolved
<img width="887" alt="Screen Shot 2020-09-29 at 2 38 27 PM" src="https://user-images.githubusercontent.com/254562/94619285-77cdee80-0261-11eb-888e-6f8a44e9f9fc.png">

**Comment by hbenl** [comment]
This has happened in 2 recordings:
https://replay.io/view?id=7174e1c6-0c12-4546-84a0-e1a3a0099a38
https://replay.io/view?id=caef4cb5-bcff-46aa-9a74-eb5c6f6e6479

The issue is that lodash's `without` function forces us to convert an array into a list of arguments, which gets too long.
So we should use `difference` instead.
