### ISSUE TITLE
The screenshot is missing on the initial load

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#800]
**Describe the bug**
I've noticed over the past weeks that the viewer does not show any graphics until the user manually seeks to another location

**To Reproduce**
1. go to https://replay.io/view?id=182fe003-a55b-46e2-8ec2-8c36d8ec242e

**Recording**

here is a recording where i annotated some calls to refreshGraphics https://replay.io/view?id=03d5d044-763b-447d-a926-2b16d9716381

**Comment by hbenl** [comment]
That's because the screenshot that is shown initially is taken from the recording's description and for recent recordings, the description doesn't contain a screenshot anymore (see [here](https://github.com/RecordReplay/backend/blob/0b63589f82feac609f9781a329400f5843ff1a26/src/cpp/driver/WebSocket.cpp#L368)).
@jasonLaster should this be fixed in the backend or do we want to remove the screenshot from the description permanently? If so, I'd add some code to fetch and display the last screenshot in the devtools.

**Comment by jasonLaster** [comment]
hmm, lets hold off for now.

**Comment by bhackett1024** [comment]
I think the devtools should be able to deal with the case where there isn't a description with a screen shot.  Even once we are generating screen shots in the descriptions again, there will be cases where we have recordings that either don't have a description at all, or have a description without a screen shot.  This currently happens in our automated tests when we are recording the viewer, as when the test finishes the browser is killed without the recording being explicitly finished by clicking the button.  I'm expecting something similar to happen for other CI/CD type use cases in the future.

**Comment by hbenl** [comment]
Actually the devtools already handled this situation correctly - almost.
When the recording is loaded, the devtools jump to the end of the recording and that triggers the `onPaused` event handler in `ui/actions/timeline.js`. That handler tries to get and paint the graphics for the end of the recording. However, the devtools already added a `paintPoint` for the screenshot from the description, that's what the handler picks up and so it ends up getting an undefined screenshot...
So all I had to do was to prevent that `paintPoint` from being added (if the description doesn't contain a screenshot)...

**Comment by jasonLaster** [comment]
Very cool @hbenl. Thanks for digging a bit deeper
